// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const ARTICULOPRECIOGENERALFRAGMENT = gql`
  fragment ArticuloPrecioGeneralFragment on ArticuloPrecioGeneral {
    _id
    articuloId
    codigoArticulo
    nombreArticulo
    grupoId
    sucursal {
      codigo
      direccion
      telefono
      departamento {
        codigo
        codigoPais
        sigla
        departamento
      }
      municipio
      integracionSiat
    }
    imagen {
      id
      filename
      variants {
        thumbnail
        medium
        square
        public
      }
    }
    precioBase {
      _id
      articuloUnidadMedida {
        _id
        codigoUnidadMedida
        nombreUnidadMedida
        sinUnidadMedida {
          codigoClasificador
          descripcion
        }
        longitud
        ancho
        altura
        peso
        volumen
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      monedaPrimaria {
        moneda {
          _id
          codigo
          descripcion
          sigla
          tipoCambio
          tipoCambioCompra
          activo
          state
          usucre
          usumod
          createdAt
          updatedAt
        }
        precioBase
        precio
        delivery
        precioComparacion
        manual
      }
      monedaAdicional1 {
        # Datos simples (Tipo ya expandido previamente)
        precioBase
        precio
        delivery
        precioComparacion
        manual
      }
      monedaAdicional2 {
        # Datos simples (Tipo ya expandido previamente)
        precioBase
        precio
        delivery
        precioComparacion
        manual
      }
      monedaAdicional3 {
        # Datos simples (Tipo ya expandido previamente)
        precioBase
        precio
        delivery
        precioComparacion
        manual
      }
      cantidadBase
      descuento {
        fechaInicial
        fechaFinal
        porcentaje
        cantidad {
          nro
          porcentaje
        }
      }
      imagen {
        # Datos simples (Tipo ya expandido previamente)
        id
        filename
      }
      factorAjuste
      umVenta
      umInventario
      umCompra
    }
    precioGrupo {
      # Datos simples (Tipo ya expandido previamente)
      _id
      cantidadBase
      factorAjuste
      umVenta
      umInventario
      umCompra
    }
    impresoras {
      _id
      sucursal {
        codigo
        direccion
        telefono
        departamento {
          # Datos simples (Tipo ya expandido previamente)
          codigo
          codigoPais
          sigla
          departamento
        }
        municipio
        integracionSiat
      }
      puntoVenta {
        codigo
        tipoPuntoVenta {
          codigoClasificador
          descripcion
        }
        nombre
        descripcion
      }
      nombre
      descripcion
      atributo1
      atributo2
      state
      usucre
      createdAt
      usumod
      updatedAt
    }
    activo
    verificarStock
    state
    usucre
    createdAt
    usumod
    updatedAt
  }
`
