// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const IMPRESORAFRAGMENT = gql`
  fragment ImpresoraFragment on Impresora {
    _id
    sucursal {
      codigo
      direccion
      telefono
      departamento {
        codigo
        codigoPais
        sigla
        departamento
      }
      municipio
      integracionSiat
    }
    puntoVenta {
      codigo
      tipoPuntoVenta {
        codigoClasificador
        descripcion
      }
      nombre
      descripcion
    }
    nombre
    descripcion
    atributo1
    atributo2
    state
    usucre
    createdAt
    usumod
    updatedAt
  }
`
