#!/usr/bin/env python3
import os
import json
import sys
from pathlib import Path
from datetime import datetime
import requests

# ==========================================
# CONFIGURACIÓN MANDATORIA
# ==========================================
HEADER = "// AUTO-GENERATED BY ISI-GQL developer for Nick Russell"
META_FILE_NAME = ".generator-meta.json"

INTROSPECTION_QUERY = """
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types { ...FullType }
  }
}
fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    isDeprecated
    args { ...InputValue }
    type { ...TypeRef }
  }
  inputFields { ...InputValue }
  interfaces { ...TypeRef }
  enumValues(includeDeprecated: true) { name }
  possibleTypes { ...TypeRef }
}
fragment InputValue on __InputValue {
  name
  type { ...TypeRef }
  defaultValue
}
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
        }
      }
    }
  }
}
"""

class GQLDeterministicGenerator:
    def __init__(self, base_path: str, endpoint_url: str):
        # Resolucion segura: si la ruta es relativa, se resuelve desde el CWD del proceso
        raw = Path(base_path)
        self.base_path = raw.resolve() if raw.is_absolute() else (Path.cwd() / raw).resolve()
        self.endpoint_url = endpoint_url
        self.meta_file = self.base_path / META_FILE_NAME
        self.meta_data = {
            "last_sync": None,
            "fragments": [],
            "queries": [],
            "mutations": [],
            "types": [],
            "client": [],
            "index": []
        }
        self.schema_types = []
        self.load_meta()

    def load_meta(self):
        if self.meta_file.exists():
            try:
                with open(self.meta_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    for k, v in data.items():
                        self.meta_data[k] = v
            except: pass

    def save_meta(self):
        self.meta_data["last_sync"] = datetime.now().isoformat()
        with open(self.meta_file, "w", encoding="utf-8") as f:
            json.dump(self.meta_data, f, indent=2)

    def fetch_schema(self):
        print(f"Obteniendo schema desde {self.endpoint_url}...")
        response = requests.post(
            self.endpoint_url,
            json={"query": INTROSPECTION_QUERY},
            headers={"Content-Type": "application/json"}
        )
        response.raise_for_status()
        data = response.json()
        if "errors" in data:
            raise Exception(f"Errores de GraphQL: {json.dumps(data['errors'])}")
        return data["data"]

    def filter_schema_operations(self, schema_data):
        query_type_name = schema_data.get("__schema", {}).get("queryType", {}).get("name", "Query") if schema_data.get("__schema", {}).get("queryType") else None
        mutation_type_name = schema_data.get("__schema", {}).get("mutationType", {}).get("name", "Mutation") if schema_data.get("__schema", {}).get("mutationType") else None

        operations = []
        self.schema_types = schema_data.get("__schema", {}).get("types", [])

        query_type = None
        mutation_type = None

        for t in self.schema_types:
            if t.get("name") == query_type_name: query_type = t
            elif t.get("name") == mutation_type_name: mutation_type = t

        idx = 1
        if query_type and query_type.get("fields"):
            for f in query_type.get("fields", []):
                operations.append((idx, "Query", f["name"], f, query_type))
                idx += 1

        if mutation_type and mutation_type.get("fields"):
            for f in mutation_type.get("fields", []):
                operations.append((idx, "Mutation", f["name"], f, mutation_type))
                idx += 1

        if not operations: return [], []

        print("\n=== OPERACIONES DISPONIBLES EN EL BACKEND ===")
        for i, optype, name, f, _ in operations:
            desc = f.get("description", "") or ""
            is_dep = f.get("isDeprecated") or "deprecado" in desc.lower()
            warning = " ⚠️ [PELIGRO: DEPRECADO]" if is_dep else ""
            print(f" {i:3d}. [{optype}] {name}{warning}")

        print("\nOpciones de selección: '1, 3, 5' o rangos '1-5' o 'all'")
        if self.meta_data.get("saved_operations"):
            print(" - 'last' : Reutilizar exactamente las mismas operaciones que la última vez.")

        selection = input("\nSelección: ").strip().lower()

        selected_queries = []
        selected_mutations = []

        if selection == 'last' and self.meta_data.get("saved_operations"):
            saved = set(self.meta_data["saved_operations"])
            for i, optype, name, f, t in operations:
                if name in saved:
                    if optype == "Query": selected_queries.append(f)
                    else: selected_mutations.append(f)
            print(f"-> Restauradas {len(selected_queries) + len(selected_mutations)} operaciones de la corrida anterior.")
        else:
            if selection == 'all' or selection == '':
                selected_indices = [op[0] for op in operations]
            else:
                selected_indices = []
                for part in selection.split(","):
                    part = part.strip()
                    if part.isdigit():
                        selected_indices.append(int(part))
                    elif "-" in part:
                        subparts = part.split("-")
                        if len(subparts) == 2 and subparts[0].isdigit() and subparts[1].isdigit():
                            selected_indices.extend(range(int(subparts[0]), int(subparts[1]) + 1))

            for i, optype, name, f, t in operations:
                if i in selected_indices:
                    if optype == "Query": selected_queries.append(f)
                    else: selected_mutations.append(f)

        # Guardamos la selección actual para la próxima vez
        self.meta_data["saved_operations"] = [f["name"] for f in selected_queries + selected_mutations]
        return selected_queries, selected_mutations

    def update_file(self, file_path_str: str, content: str):
        file_path_str = file_path_str.replace("\\", "/")
        full_path = self.base_path / file_path_str
        parts = Path(file_path_str).parts
        category = parts[0] if len(parts) > 1 else "index"

        full_path.parent.mkdir(parents=True, exist_ok=True)
        final_content = f"{HEADER}\n\n{content}"

        with open(full_path, "w", encoding="utf-8") as f:
            f.write(final_content)

        print(f"[VOLCADO] {file_path_str}")
        if category not in self.meta_data: self.meta_data[category] = []
        if file_path_str not in self.meta_data[category]: self.meta_data[category].append(file_path_str)

    # === TYPE HELPERS ===
    def get_base_type_name(self, type_ref):
        curr = type_ref
        while curr and curr.get("kind") in ["NON_NULL", "LIST"]:
            curr = curr.get("ofType")
        return curr.get("name") if curr else "any"

    def is_object_type(self, type_name):
        t = next((x for x in self.schema_types if x.get("name") == type_name), None)
        return t and t.get("kind") in ["OBJECT", "INTERFACE"]

    def is_optional(self, type_ref):
        return type_ref.get("kind") != "NON_NULL"

    def render_ts_type(self, type_ref):
        kind = type_ref.get("kind")
        name = type_ref.get("name")
        oftype = type_ref.get("ofType")

        if kind == "NON_NULL": return self.render_ts_type(oftype)
        if kind == "LIST": return f"{self.render_ts_type(oftype)}[]"

        scalar_map = {
            "String": "string", "Int": "number", "Float": "number",
            "Boolean": "boolean", "ID": "string", "DateTime": "string",
            "Date": "string", "JSON": "any"
        }
        if kind in ["SCALAR", "OBJECT", "INPUT_OBJECT", "ENUM", "INTERFACE", "UNION"]:
            return scalar_map.get(name, name)
        return "any"

    def build_gql_type_str(self, type_ref):
        kind = type_ref.get("kind")
        if kind == "NON_NULL": return f"{self.build_gql_type_str(type_ref.get('ofType'))}!"
        if kind == "LIST": return f"[{self.build_gql_type_str(type_ref.get('ofType'))}]"
        return type_ref.get("name")

    # === GENERATORS ===
    def generate_client(self):
        code = '''import { GraphQLClient, gql } from 'graphql-request';

const endpoint = import.meta.env.ISI_API_URL || '';

export const client = new GraphQLClient(endpoint, {
  headers: () => {
    const token = localStorage.getItem(AccessToken);
    return (token ? { Authorization: `Bearer ${token}` } : {}) as Record<string, string>;
  },
});

export { gql };'''
        if not (self.base_path / "client/index.ts").exists():
            self.update_file("client/index.ts", code)

    def collect_dependencies(self, queries, mutations):
        """Genera un grafo estricto de los tipos usados (Tree Shaking) y los guarda en histórico."""
        used = set()
        queue = []

        def enqueue(type_ref):
            if type_ref:
                base = self.get_base_type_name(type_ref)
                if base and base not in ["String", "Int", "Float", "Boolean", "ID", "any"]:
                    queue.append(base)

        for q in queries + mutations:
            for arg in q.get("args", []):
                enqueue(arg["type"])
            enqueue(q["type"])

        while queue:
            t_name = queue.pop(0)
            if t_name in used:
                continue
            used.add(t_name)

            node = next((t for t in self.schema_types if t.get("name") == t_name), None)
            if not node: continue

            kind = node.get("kind")
            if kind in ["OBJECT", "INPUT_OBJECT", "INTERFACE"]:
                fields = node.get("fields") or node.get("inputFields") or []
                for f in fields:
                    enqueue(f["type"])
            elif kind == "UNION":
                for p in node.get("possibleTypes", []):
                    enqueue(p)

        prev_used = set(self.meta_data.get("used_types", []))
        all_used = list(used | prev_used)
        self.meta_data["used_types"] = all_used
        self.save_meta()
        return set(all_used)

    def generate_types(self, queries, mutations):
        used_types = self.collect_dependencies(queries, mutations)
        lines = []
        for t in self.schema_types:
            name = t.get("name")
            kind = t.get("kind")
            description = t.get("description", "")

            if not name or name.startswith("__") or name in ["Query", "Mutation", "Subscription"]: continue
            if name not in used_types: continue

            if kind == "ENUM":
                if description:
                    lines.append(f"/**\n * {description.replace(chr(10), ' ')}\n */")
                lines.append(f"export enum {name} {{")
                for val in t.get("enumValues", []):
                    val_desc = val.get("description")
                    if val_desc:
                        lines.append(f"  /** {val_desc.replace(chr(10), ' ')} */")
                    lines.append(f"  {val['name']} = '{val['name']}',")
                lines.append("}\n")
            elif kind in ["OBJECT", "INPUT_OBJECT", "INTERFACE"]:
                if description:
                    lines.append(f"/**\n * {description.replace(chr(10), ' ')}\n */")
                lines.append(f"export interface {name} {{")
                fields = t.get("fields") or t.get("inputFields") or []
                for f in fields:
                    f_desc = f.get("description")
                    if f_desc:
                        lines.append(f"  /** {f_desc.replace(chr(10), ' ')} */")
                    opts = "?" if self.is_optional(f["type"]) else ""
                    ts_t = self.render_ts_type(f["type"])
                    lines.append(f"  {f['name']}{opts}: {ts_t};")
                lines.append("}\n")
            elif kind == "SCALAR":
                if name not in ["String", "Int", "Float", "Boolean", "ID"]:
                    if description:
                        lines.append(f"/**\n * {description.replace(chr(10), ' ')}\n */")
                    # Intentar inferir el tipo estricto en TS basado en el nombre del Scalar Custom
                    if "Url" in name:
                        base_mapped = "string"  # URLs son strings en JS
                    else:
                        base_mapped = {"DateTime": "string", "Date": "string", "JSON": "Record<string, unknown>", "Upload": "File"}.get(name, "string")
                    lines.append(f"export type {name} = {base_mapped};")
            elif kind == "UNION":
                if description:
                    lines.append(f"/**\n * {description.replace(chr(10), ' ')}\n */")
                possible_types = " | ".join([p.get("name") for p in t.get("possibleTypes", [])])
                lines.append(f"export type {name} = {possible_types or 'any'};")

        self.update_file("types/index.ts", "\n".join(lines))

    def get_scalar_fields(self, type_name, indent=""):
        """Retorna solo los campos escalares (id, strings, etc.) de un tipo, sin objetos anidados."""
        node = next((t for t in self.schema_types if t.get("name") == type_name), None)
        if not node or node.get("kind") not in ["OBJECT", "INTERFACE"]: return "id"

        scalars = []
        for f in node.get("fields", []):
            base = self.get_base_type_name(f["type"])
            if not self.is_object_type(base):
                # Solo tomamos campos básicos, no pedimos recursión
                scalars.append(f["name"])

        if not scalars: return "id"
        return f"\n{indent}".join(scalars)

    def build_fragment_fields(self, type_name, visited=None, depth=0, max_depth=5, indent=""):
        """Recursión inteligente y robusta.
           Si un tipo ya fue expandido antes en el árbol, solo extrae sus campos simples (para no repetir bloques gigantes).
        """
        if visited is None: visited = set()
        node = next((t for t in self.schema_types if t.get("name") == type_name), None)
        if not node or node.get("kind") not in ["OBJECT", "INTERFACE"]: return ""

        visited.add(type_name)
        lines = []
        for f in node.get("fields", []):
            base = self.get_base_type_name(f["type"])
            if self.is_object_type(base):
                if depth >= max_depth:
                    # Límite máximo alcanzado: solo ID
                    lines.append(f"# Límite de profundidad alcanzado")
                    lines.append(f"{f['name']} {{ id }}")
                elif base in visited:
                    # Tipo ya visto en otra rama: para no triplicar mil líneas, traemos de él solo datos escalares
                    shallow = self.get_scalar_fields(base, indent + "  ")
                    lines.append(f"{f['name']} {{\n{indent}  # Datos simples (Tipo ya expandido previamente)\n{indent}  {shallow}\n{indent}}}")
                else:
                    # Nuevo objeto: Recursión profunda, pasamos el MISMO visited referenciado
                    sub_fields = self.build_fragment_fields(base, visited, depth + 1, max_depth, indent + "  ")
                    if sub_fields:
                        lines.append(f"{f['name']} {{\n{indent}  {sub_fields.replace(chr(10), chr(10)+indent+'  ')}\n{indent}}}")
                    else:
                        lines.append(f"{f['name']} {{ id }}")
            else:
                lines.append(f["name"])

        return f"\n{indent}".join(lines)

    def generate_operation(self, optype, field):
        op_name = field["name"]
        op_capitalized = op_name[0].upper() + op_name[1:]
        args = field.get("args", [])

        gql_args_def = ", ".join([f"${a['name']}: {self.build_gql_type_str(a['type'])}" for a in args])
        gql_args_pass = ", ".join([f"{a['name']}: ${a['name']}" for a in args])

        if gql_args_def: gql_args_def = f"({gql_args_def})"
        if gql_args_pass: gql_args_pass = f"({gql_args_pass})"

        ret_base = self.get_base_type_name(field["type"])
        ret_ts = self.render_ts_type(field["type"])
        is_obj_return = self.is_object_type(ret_base)

        fragment_import = ""
        fragment_spread = ""
        frag_name_upper = ""

        if is_obj_return:
            frag_fields = self.build_fragment_fields(ret_base, max_depth=5)
            if not frag_fields: frag_fields = "id\n" # fallback against empty
            frag_name = f"{ret_base}Fragment"
            frag_name_upper = frag_name.upper()

            # create Fragment file
            frag_content = f"import {{ gql }} from '../client';\n\nexport const {frag_name_upper} = gql`\n  fragment {frag_name} on {ret_base} {{\n    {frag_fields.replace(chr(10), chr(10)+'    ')}\n  }}\n`;"
            self.update_file(f"fragments/{ret_base}Fragments.ts", frag_content)

            fragment_spread = f"{{ ...{frag_name} }}"
            fragment_import = f"import {{ {frag_name_upper} }} from '../fragments/{ret_base}Fragments';\n"

        gql_string = f"export const {op_name.upper()} = gql`\n  {optype.lower()} {op_capitalized}{gql_args_def} {{\n    {op_name}{gql_args_pass} {fragment_spread}\n  }}\n  ${{{frag_name_upper}}}\n`;" if is_obj_return else f"export const {op_name.upper()} = gql`\n  {optype.lower()} {op_capitalized}{gql_args_def} {{\n    {op_name}{gql_args_pass}\n  }}\n`;"

        # Variavles
        vars_iface = f"export interface {op_capitalized}Variables {{\n"
        for a in args:
            opts = "?" if self.is_optional(a["type"]) else ""
            ts_t = self.render_ts_type(a["type"])
            vars_iface += f"  {a['name']}{opts}: {ts_t};\n"
        vars_iface += "}\n"

        import re
        all_text_for_types = f"{vars_iface} {ret_ts}"
        words_in_code = set(re.findall(r'[A-Za-z_]\w*', all_text_for_types))

        schema_type_names = {t.get("name") for t in self.schema_types if t.get("name") and not t.get("name").startswith("__")}
        imports_types = sorted(list(words_in_code.intersection(schema_type_names)))
        types_import = f"import {{ {', '.join(imports_types)} }} from '../types';\n" if imports_types else ""

        hook_name = f"use{op_capitalized}"
        if optype == "Query":
            hook = f"export const {hook_name} = (variables: {op_capitalized}Variables, options?: Omit<UseQueryOptions<{ret_ts}, Error>, 'queryKey' | 'queryFn'>) => {{\n  return useQuery<{ret_ts}, Error>({{\n    queryKey: ['{op_name}', variables],\n    queryFn: async () => {{\n      const response = await client.request<{{ {op_name}: {ret_ts} }}>({op_name.upper()}, variables);\n      return response.{op_name};\n    }},\n    ...options,\n  }});\n}};"
            react_query_import = "import { useQuery, UseQueryOptions } from '@tanstack/react-query';"
            folder = "queries"
        else:
            hook = f"export const {hook_name} = (options?: UseMutationOptions<{ret_ts}, Error, {op_capitalized}Variables>) => {{\n  return useMutation<{ret_ts}, Error, {op_capitalized}Variables>({{\n    mutationFn: async (variables) => {{\n      const response = await client.request<{{ {op_name}: {ret_ts} }}>({op_name.upper()}, variables);\n      return response.{op_name};\n    }},\n    ...options,\n  }});\n}};"
            react_query_import = "import { useMutation, UseMutationOptions } from '@tanstack/react-query';"
            folder = "mutations"

        file_content = f"{react_query_import}\nimport {{ client, gql }} from '../client';\n{fragment_import}{types_import}\n{vars_iface}\n{gql_string}\n\n{hook}"
        self.update_file(f"{folder}/{hook_name}.ts", file_content)

def main():
    print("======================================================")
    print("  ⭐ ENTERPRISE ISI GQL GENERATOR (LOCAL, 100% GRATIS) ⭐")
    print("======================================================")
    print(f"Directorio de trabajo actual: {Path.cwd()}")

    base_path = input("Ingresa la ruta base (ej: ./src/graphql): ").strip()
    if not base_path: sys.exit(1)

    endpoint = input("Ingresa el Endpoint GraphQL (Enter para 'https://sandbox.isipass.net/restaurante'): ").strip()
    if not endpoint: endpoint = "https://sandbox.isipass.net/restaurante"

    gen = GQLDeterministicGenerator(base_path, endpoint)
    print(f"Ruta base del proyecto resuelta: {gen.base_path}")
    schema_data = gen.fetch_schema()
    queries, mutations = gen.filter_schema_operations(schema_data)

    if not queries and not mutations:
        print("No se seleccionaron operaciones.")
        sys.exit(0)

    print("\n[AST] Generando motor de forma instantanea sin IA (profundidad completa automatica)...")
    gen.generate_client()
    gen.generate_types(queries, mutations)

    for q in queries: gen.generate_operation("Query", q)
    for m in mutations: gen.generate_operation("Mutation", m)

    # Export index
    exports = ["export * from './client';\nexport * from './types';"]
    for q in queries:
        op = q['name']
        exports.append(f"export * from './queries/use{op[0].upper() + op[1:]}';")
    for m in mutations:
        op = m['name']
        exports.append(f"export * from './mutations/use{op[0].upper() + op[1:]}';")

    gen.update_file("index.ts", "\n".join(exports))
    gen.save_meta()
    print("\n=== FIN DE LA GENERACIÓN SIN COSTO Y CIERRE EXITOSO ===")

if __name__ == "__main__":
    main()
