// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { IMPRESORAFRAGMENT } from '../fragments/ImpresoraFragments'
import { Impresora } from '../types'

export interface ImpresoraPorSucursalVariables {
  codigoSucursal: number
}

export const IMPRESORAPORSUCURSAL = gql`
  query ImpresoraPorSucursal($codigoSucursal: Int!) {
    impresoraPorSucursal(codigoSucursal: $codigoSucursal) {
      ...ImpresoraFragment
    }
  }
  ${IMPRESORAFRAGMENT}
`

export const useImpresoraPorSucursal = (
  variables: ImpresoraPorSucursalVariables,
  options?: Omit<UseQueryOptions<Impresora[], Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<Impresora[], Error>({
    queryKey: ['impresoraPorSucursal', variables],
    queryFn: async () => {
      const response = await client.request<{ impresoraPorSucursal: Impresora[] }>(
        IMPRESORAPORSUCURSAL,
        variables,
      )
      return response.impresoraPorSucursal
    },
    ...options,
  })
}
