// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { ARQUEOCAJAFRAGMENT } from '../fragments/ArqueoCajaFragments';
import { ArqueoCaja } from '../types';

export interface ArqueoCajaPorIdVariables {
  id: string;
}

export const ARQUEOCAJAPORID = gql`
  query ArqueoCajaPorId($id: ID!) {
    arqueoCajaPorId(id: $id) { ...ArqueoCajaFragment }
  }
  ${ARQUEOCAJAFRAGMENT}
`;

export const useArqueoCajaPorId = (variables: ArqueoCajaPorIdVariables, options?: Omit<UseQueryOptions<ArqueoCaja, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<ArqueoCaja, Error>({
    queryKey: ['arqueoCajaPorId', variables],
    queryFn: async () => {
      const response = await client.request<{ arqueoCajaPorId: ArqueoCaja }>(ARQUEOCAJAPORID, variables);
      return response.arqueoCajaPorId;
    },
    ...options,
  });
};