// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { ARQUEOCAJACONNECTIONFRAGMENT } from '../fragments/ArqueoCajaConnectionFragments'
import { ArqueoCajaConnection } from '../types'

export interface ArqueoCajaListadoVariables {
  limit: number
  page?: number
  reverse?: boolean
  query?: string
}

export const ARQUEOCAJALISTADO = gql`
  query ArqueoCajaListado($limit: Int!, $page: Int, $reverse: Boolean, $query: String) {
    arqueoCajaListado(limit: $limit, page: $page, reverse: $reverse, query: $query) {
      ...ArqueoCajaConnectionFragment
    }
  }
  ${ARQUEOCAJACONNECTIONFRAGMENT}
`

export const useArqueoCajaListado = (
  variables: ArqueoCajaListadoVariables,
  options?: Omit<UseQueryOptions<ArqueoCajaConnection, Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<ArqueoCajaConnection, Error>({
    queryKey: ['arqueoCajaListado', variables],
    queryFn: async () => {
      const response = await client.request<{ arqueoCajaListado: ArqueoCajaConnection }>(
        ARQUEOCAJALISTADO,
        variables,
      )
      return response.arqueoCajaListado
    },
    ...options,
  })
}
