// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { CAJACONNECTIONFRAGMENT } from '../fragments/CajaConnectionFragments';
import { CajaConnection } from '../types';

export interface CajaListadoVariables {
  limit: number;
  page?: number;
  reverse?: boolean;
  query?: string;
}

export const CAJALISTADO = gql`
  query CajaListado($limit: Int!, $page: Int, $reverse: Boolean, $query: String) {
    cajaListado(limit: $limit, page: $page, reverse: $reverse, query: $query) { ...CajaConnectionFragment }
  }
  ${CAJACONNECTIONFRAGMENT}
`;

export const useCajaListado = (variables: CajaListadoVariables, options?: Omit<UseQueryOptions<CajaConnection, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<CajaConnection, Error>({
    queryKey: ['cajaListado', variables],
    queryFn: async () => {
      const response = await client.request<{ cajaListado: CajaConnection }>(CAJALISTADO, variables);
      return response.cajaListado;
    },
    ...options,
  });
};