// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { TURNOCAJAFRAGMENT } from '../fragments/TurnoCajaFragments';
import { TurnoCaja } from '../types';

export interface TurnoCajaListadoVariables {
}

export const TURNOCAJALISTADO = gql`
  query TurnoCajaListado {
    turnoCajaListado { ...TurnoCajaFragment }
  }
  ${TURNOCAJAFRAGMENT}
`;

export const useTurnoCajaListado = (variables: TurnoCajaListadoVariables, options?: Omit<UseQueryOptions<TurnoCaja[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<TurnoCaja[], Error>({
    queryKey: ['turnoCajaListado', variables],
    queryFn: async () => {
      const response = await client.request<{ turnoCajaListado: TurnoCaja[] }>(TURNOCAJALISTADO, variables);
      return response.turnoCajaListado;
    },
    ...options,
  });
};