// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

/**
 * Date in DD/MM/YYYY HH:MM:SS format
 */
export type DateDMYHHMMSS = string;
/**
 * Url de la representación para la obtencion de la representación impresa 
 */
export type UrlRepresentacionGrafica = string;
/**
 * Url de la representación Grafica V2, para la obtención de la representación impresa, uso de Buffer para la generacion de archivos 
 */
export type UrlRepresentacionGraficaV2 = string;
/**
 * Url de la representación S.I.N para la obtencion de la representación impresa 
 */
export type UrlSinRepresentacionGrafica = string;
/**
 * Información para ayudar en la paginación.
 */
export interface PageInfo {
  /** Al paginar hacia adelante, ¿hay más elementos? */
  hasNextPage: boolean;
  /** Al paginar hacia atrás, ¿hay más elementos? */
  hasPrevPage: boolean;
  /** Número total de registros */
  totalDocs?: number;
  /** Agrupador de registros */
  limit?: number;
  /** Pagina Actual de consulta */
  page?: number;
  /** Total de paginas */
  totalPages?: number;
}

/**
 * Actividad económica del S.I.N
 */
export interface SinActividades {
  /** Código de Actividad Económica */
  codigoCaeb: string;
  /** Descripción de Actividad Económica */
  descripcion: string;
  /** Tipo de actividad (Producto o Servicio) */
  tipoActividad: string;
}

/**
 * Se usa para describir el motivo por el cual se anula un determinda documento Eje. Factura, Notas, etc
 */
export interface SinMotivoAnulacion {
  /** Código de Motivo de Anulación */
  codigoClasificador: string;
  /** Descripción del Motivo de Anulación */
  descripcion: string;
}

/**
 * La Homologación de productos y servicios permite al Contribuyente relacionar los códigos utilizados para sus productos y servicios con los códigos genéricos proporcionados por la Administración Tributaria
 */
export interface SinProductoServicio {
  /** Código de Actividad Económica */
  codigoActividad: string;
  /** Código de Producto o Servicio */
  codigoProducto: string;
  /** Descripción genérica del Producto o Servicio */
  descripcionProducto: string;
}

/**
 * Tipos de documentos que se pueden emitir
 */
export interface SinTipoDocumentoIdentidad {
  /** Código de Tipo de Documento */
  codigoClasificador: string;
  /** Descripción del Tipo de Documento */
  descripcion: string;
}

/**
 * Están definidos para que cada Factura Digital pueda ser enviada por un Servicio Web, lo cual asegura la independencia del mismo en caso de modificaciones o ajustes.
 */
export interface SinTipoDocumentoSector {
  /** Código de Tipo de Documento Sector */
  codigoClasificador?: string;
  /** Descripción del Tipo de Documento Sector */
  descripcion?: string;
}

/**
 * Métodos de generación de documentos digitales
 */
export interface SinTipoEmision {
  /** Código de Tipo de Emisión */
  codigoClasificador: string;
  /** Descripción del Tipo de Emisión */
  descripcion: string;
}

/**
 * Tipos de documentos fiscales
 */
export interface SinTipoFactura {
  /** Código de Tipo de Factura */
  codigoClasificador: string;
  /** Descripción del Tipo de Factura */
  descripcion: string;
}

/**
 * Medios por los cuales se hace efectivo un pago a una factura
 */
export interface SinTipoMetodoPago {
  /** Código de Tipo de Método de Pago */
  codigoClasificador: string;
  /** Descripción del Tipo de Método de Pago */
  descripcion: string;
}

/**
 * Cualquier tipo de dinero (monedas, billetes, cheques, entre otros) que se encuentra en circulación en la economía de un territorio en concreto
 */
export interface SinTipoMoneda {
  /** Código de Tipo de Moneda */
  codigoClasificador: number;
  /** Descripción del Tipo de Moneda */
  descripcion: string;
}

/**
 * Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes
 */
export interface SinTipoPuntoVenta {
  /** Código de Tipo de Punto de Venta */
  codigoClasificador: string;
  /** Descripción del Tipo de Punto de Venta */
  descripcion: string;
}

/**
 * Las unidades de medida nos permiten cuantificar claramente las existencias de nuestro inventario, estas nos permiten  la correcta interpretación de las cantidades
 */
export interface SinUnidadMedida {
  /** Código de Unidad de Medida */
  codigoClasificador?: number;
  /** Descripción de Unidad de Medida */
  descripcion?: string;
}

/**
 * El CUIS es un valor generado por la Administración Tributaria y que identifica la relación entre el Sistema Informático de Facturación autorizado, credenciales, Contribuyente, sucursal y opcionalmente al punto de venta, es inalterable en su composición y deberá ser parte del envío de Facturas Digitales.
 */
export interface SinCuis {
  /** Código Único de Inicio de Sistema */
  codigo?: string;
  /** Fecha de vigencia del CUIS */
  fechaVigencia?: DateDMYHHMMSS;
}

/**
 * Código Único de Facturación Diaria (CUFD) para el Sistema Informático de Facturación autorizado debe realizarse diariamente. Este código habilita el sistema del Sujeto Pasivo para la emisión de Facturas Digitales durante un periodo de vigencia de 24 horas
 */
export interface SinCufD {
  /** Código Único de Facturación Diaria */
  codigo?: string;
  /** Código de control del CUFD */
  codigoControl?: string;
  /** Dirección de facturación del CUFD */
  direccion?: string;
  /** Fecha de vigencia del CUFD */
  fechaVigencia?: DateDMYHHMMSS;
  /** Fecha de inicio del CUFD */
  fechaInicial?: DateDMYHHMMSS;
}

/**
 * Entrada de datos paramétricos de la entidad como codigos de sucursal o codigos de puntos de venta - El código de sucursal y punto de venta enviado esta restringido a su la restriccion de sucursal y punto de venta - Para verificar las restricciones consulte el servicio usuarioRestriccion
 */
export interface EntidadParamsInput {
  codigoSucursal: number;
  codigoPuntoVenta: number;
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface ClienteOperacion {
  /** Razon Social del cliente. */
  razonSocial?: string;
  /** Codigo unico que se asigna al cliente. */
  codigoCliente?: string;
  /** Código del clasificador del tipo documento de identidad. */
  tipoDocumentoIdentidad?: SinTipoDocumentoIdentidad;
  /** Numero de documento del cliente */
  numeroDocumento: string;
  /** Si es C.I., y contenga un numero de complemento */
  complemento?: string;
  /** Nombre del  titular de la cuenta. */
  nombres?: string;
  /** Apellidos del titular de la cuenta. */
  apellidos?: string;
  /** Correo electrónico de la persona, este campo es unico en la organización. */
  email?: string;
  /** Telefono de referencia */
  telefono?: string;
  /** Si el cliente tiene linea de credito - true: El cliente puede acceder a una linea de credito - false: El cliente no puede acceder a una linea de credito */
  lineaCredito?: boolean;
  /** Credito minimo para acceder a una linea de credito - 0 o nulo: No hay limite */
  creditoMinimo?: number;
  /** Credito maximo para acceder a una linea de credito - 0 o nulo: No hay limite */
  creditoMaximo?: number;
  /** Direccion de residencia del cliente */
  direccion?: string;
  /** Dirección en el cual el cliente desarrolla sus actividades económicas */
  direccionLaboral?: string;
  /** Nombre de la entidad donde el cliente desarrolla sus actividades económicas */
  entidadLaboral?: string;
  /** Máximo plazo (meses) de duración del un crédito - Se contabiliza en Nro de meses. */
  maximoPlazo?: number;
}

/**
 * Datos del punto de venta, asociado a la factura.
 */
export interface OrgFacturaPuntoVenta {
  /** Codigo del punto de venta. */
  codigo?: number;
  /** Catalogo de Tipo de Punto de Venta. */
  tipoPuntoVenta?: SinTipoPuntoVenta;
  /** Nombre alias del punto de venta. */
  nombre?: string;
  /** Direccion del punto de venta. */
  descripcion?: string;
}

/**
 * Estructura de datos para Departamento
 */
export interface Departamento {
  /** Código segun INE */
  codigo?: number;
  /** Código de Pais segun ISO 3166-1 */
  codigoPais?: number;
  /** Sigla del departamento */
  sigla?: string;
  /** Nombre del departamento */
  departamento?: string;
}

/**
 * Datos de la sucursal asociado a cada factura
 */
export interface OrgFacturaSucursal {
  /** Codigo de la sucursal */
  codigo?: number;
  /** Direccion regitrada en cada sucursal */
  direccion?: string;
  /** Telefono de referencia de la sucursal */
  telefono?: string;
  /** Nombre de departamento de la sucursal */
  departamento?: Departamento;
  /** Nombre de municipio de la sucursal */
  municipio?: string;
  /** Define si existe integración con SISTEMA DE ADMINISTRACIÓN TRIBUTARIA */
  integracionSiat?: boolean;
}

/**
 * Urls para descargar los documentos en formato representacion gráfica
 */
export interface UrlsRepresentacionGrafica {
  pdf: UrlRepresentacionGrafica;
  xml: UrlRepresentacionGrafica;
  rollo: UrlRepresentacionGrafica;
  rolloResumen: UrlRepresentacionGrafica;
  /** Formato rollo super reducido solo disponible para: - Factura Compra Venta */
  rolloReducido: UrlRepresentacionGraficaV2;
  sin: UrlSinRepresentacionGrafica;
}

/**
 * Detalle de items de la Factura Electrónica.
 */
export interface SalidaFacturaDetalle {
  /** Número de item iterativo del detalle la factura. */
  nroItem?: number;
  /** Datos del clasificador de la Actividad Económica. */
  actividadEconomica?: SinActividades;
  /** Catálogo del Producto Servicio enviado por el SIN. */
  productoServicio?: SinProductoServicio;
  /** Código que otorga el contribuyente a su servicio o producto. */
  producto?: string;
  /** Descripción que otorga el contribuyente a su servicio o producto. */
  descripcion?: string;
  /** Cantidad del producto o servicio otorgado. En caso de servicio este valor debe ser 1. */
  cantidad?: number;
  /** Valor de la paramétrica que identifica la unidad de medida. */
  unidadMedida?: SinUnidadMedida;
  /** Precio que otorga el contribuyente a su servicio o producto. */
  precioUnitario?: number;
  /** Monto de descuento sobre el producto o servicio específico,  Si no aplica deberá ser nulo. */
  montoDescuento?: number;
  /** El subtotal es igual a la (cantidad * precio unitario) – descuento. */
  subTotal?: number;
  /** Número de serie correspondiente al producto vendido de línea blanca o negra. Nulo en otro caso. */
  numeroSerie?: string;
  /** Número de Imei del celular vendido. Nulo en otro caso. */
  numeroImei?: string;
  /** Detalle extra asociado al item, texto plano. */
  detalleExtra?: string;
  /** Mensaje de evento o acción que afecta al registro */
  log?: string;
}

/**
 * Documento Fiscal autorizado por la Administración Tributaria cuya emisión física o digital respalda la realización de compra/venta de bienes muebles, contratos de obras, prestación de servicios o toda otra prestación cualquiera fuere su naturaleza alcanzados por el IVA u otro impuesto
 */
export interface SalidaFactura {
  /** Identificador único interno */
  _id: string;
  /** Número de NIT registrado en el Padrón Nacional de Contribuyentes que corresponde a la persona o empresa que emite la factura. */
  nitEmisor: string;
  /** Razón Social o nombre registrado en el Padrón Nacional de Contribuyentes de la persona o empresa que emite la factura. */
  razonSocialEmisor: string;
  /** Numeración propia que se le asigna a la Factura. */
  numeroFactura: number;
  /** Tipos de documentos fiscales */
  tipoFactura?: SinTipoFactura;
  /** Métodos de generación de documentos digitales */
  tipoEmision?: SinTipoEmision;
  /** Código único de facturación (CUF) debe ser generado por el emisor. */
  cuf?: string;
  /** Código Único de Facturación Diaria (CUFD) */
  cufd?: SinCufD;
  /** Codigo único de sistema */
  cuis?: SinCuis;
  /** Establecimientos secundarios donde se realiza alguna de las actividades económicas del Contribuyente, tienen una dirección física y están registradas en el Padrón Nacional de Contribuyentes */
  sucursal?: OrgFacturaSucursal;
  /** Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes */
  puntoVenta?: OrgFacturaPuntoVenta;
  /** Fecha y hora en la cual se emite la factura. Expresada en formato UTC Extendido, por ejemplo: “2020-02-15T08:40:12.215”. */
  fechaEmision?: DateDMYHHMMSS;
  /** Datos del cliente, El email puede variar segun el registro original. */
  cliente: ClienteOperacion;
  /** Identifica el método de pago utilizado para realizar la compra. Por ejemplo el codigo de clasificador 1 que representa a un pago en efectivo. */
  metodoPago?: SinTipoMetodoPago;
  /** Cuando el método de pago es 2 (Tarjeta), debe enviarse este valor pero ofuscado con los primeros y últimos 4 dígitos en claro y ceros al medio. Ej: 4797000000007896,. */
  numeroTarjeta?: string;
  /** Monto total por el cual se realiza el hecho generador. */
  montoTotal?: number;
  /** Monto total en formato literal. */
  montoTotalLiteral?: string;
  /** Monto base para el cálculo del crédito fiscal. */
  montoTotalSujetoIva?: number;
  /** Valor de la paramétrica que identifica la moneda en la cual se realiza la transacción. */
  moneda?: SinTipoMoneda;
  /** Tipo de cambio de acuerdo a la moneda en la que se realiza el hecho generador, si el código de moneda es boliviano deberá ser igual a 1. */
  tipoCambio?: number;
  /** Es el Monto Total expresado en el tipo de moneda, si el código de moneda es boliviano deberá ser igual al monto total. */
  montoTotalMoneda?: number;
  /** Monto a ser cancelado con una Gift Card */
  montoGiftCard?: number;
  /** Monto Adicional al descuento por item */
  descuentoAdicional?: number;
  /** Código de Autorización de Facturas por Contingencia */
  cafc?: string;
  /** Leyenda asociada a la actividad económica. */
  leyenda?: string;
  /** Mensajes conforme a la ley 453, donde se mencionan los derechos de los usuarios. */
  subLeyenda?: string;
  /** Identifica al usuario que emite la factura, deberá ser descriptivo. Por ejemplo INTEGRATE */
  usuario?: string;
  /** Valor de la paramétrica que identifica el tipo de factura que se está emitiendo. Para este tipo de factura este valor es 1. */
  documentoSector?: SinTipoDocumentoSector;
  /** Para la anulación de una Factura emitida, la mencionada factura deberá estar previamente registrada y validada por la Administración Tributaria. Dichos servicios previa validación de los parámetros enviados, registran la solicitud devolviendo un código de estado cuando la misma fue correcta o un código de error y advertencia en caso contrario */
  motivoAnulacion?: SinMotivoAnulacion;
  /** Detalle extra, puede ser un HTML o un texto plano. la información registrada no se envia al servicio de impuestos nacionales */
  detalleExtra?: string;
  /** Detalle de los items a ser facturados */
  detalle?: SalidaFacturaDetalle[];
  /** Código del evento significativo Hechos inherentes al Sistema informático de Facturación que intervienen en su funcionamiento o que podrían afectar la emisión de las Facturas Digitales. Deben ser registrados hasta 48 horas posteriores de finalizada la contingencia, a través del sistema autorizado por la Administración Tributaria y enviados automáticamente a través del servicio Web correspondiente. */
  eventoSignificativo?: string;
  /** Respuesta al consumo del servicio de Facturacion Compra Venta */
  codigoRecepcion?: string;
  /** Representacion PDF, XML, ROLLO, ETC */
  representacionGrafica: UrlsRepresentacionGrafica;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
  /** Estado del registro */
  state?: string;
  /** Referencia con alguna tabla relacionada */
  referencia?: string;
  /** Tipo de referencia - Ej: CREDITO, VENTA, NORMAL, REST, etc - Si es null se asume venta normal por servicio de facturación */
  tipoVenta?: string;
  /** Historial de eventos relacionados al registro - En caso de tener la factura en estado diferente a VALIDADA, ANULADA, se puede consultar el log del registro */
  log?: string;
}

/**
 * Una conexión a una lista de elementos.
 */
export interface RestFacturaConnection {
  /** Información para ayudar en la paginación. */
  pageInfo: PageInfo;
  /** Lista de documentos. */
  docs?: SalidaFactura[];
}
