// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql, GraphQLClient } from 'graphql-request'

const endpoint = import.meta.env.ISI_API_URL || 'https://api.isipass.com/graphql'

// TODO: This client is shared across the entire app, so we need to be careful about how we use it. We should avoid setting any global headers or other configuration that might affect other parts of the app. Instead, we should pass any necessary headers or configuration as options to each request.

export const client = new GraphQLClient(endpoint, {
  headers: () => {
    const token = localStorage.getItem('token')
    const headers: Record<string, string> = {}
    if (token) {
      headers.Authorization = `Bearer ${token}`
    }
    return headers
  },
})

export { gql }
