// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql, GraphQLClient } from 'graphql-request'

import { AccessToken } from '../../../base/models/paramsModel'

const endpoint = import.meta.env.ISI_API_URL || ''

export const client = new GraphQLClient(endpoint, {
  headers: () => {
    const token = localStorage.getItem(AccessToken)
    return (token ? { Authorization: `Bearer ${token}` } : {}) as Record<string, string>
  },
})

export { gql }
