// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

/**
 * Date in DD/MM/YYYY HH:MM:SS format
 */
export type DateDMYHHMMSS = string;
/**
 * Url de la representación Grafica V2, para la obtención de la representación impresa, uso de Buffer para la generacion de archivos 
 */
export type UrlRepresentacionGraficaV2 = string;
/**
 * Url de la representación S.I.N para la obtencion de la representación impresa 
 */
export type UrlSinRepresentacionGrafica = string;
/**
 * Información para ayudar en la paginación.
 */
export interface PageInfo {
  /** Al paginar hacia adelante, ¿hay más elementos? */
  hasNextPage: boolean;
  /** Al paginar hacia atrás, ¿hay más elementos? */
  hasPrevPage: boolean;
  /** Número total de registros */
  totalDocs?: number;
  /** Agrupador de registros */
  limit?: number;
  /** Pagina Actual de consulta */
  page?: number;
  /** Total de paginas */
  totalPages?: number;
}

/**
 * Actividad económica del S.I.N
 */
export interface SinActividades {
  /** Código de Actividad Económica */
  codigoCaeb: string;
  /** Descripción de Actividad Económica */
  descripcion: string;
  /** Tipo de actividad (Producto o Servicio) */
  tipoActividad: string;
}

/**
 * Se usa para describir el motivo por el cual se anula un determinda documento Eje. Factura, Notas, etc
 */
export interface SinMotivoAnulacion {
  /** Código de Motivo de Anulación */
  codigoClasificador: string;
  /** Descripción del Motivo de Anulación */
  descripcion: string;
}

/**
 * La Homologación de productos y servicios permite al Contribuyente relacionar los códigos utilizados para sus productos y servicios con los códigos genéricos proporcionados por la Administración Tributaria
 */
export interface SinProductoServicio {
  /** Código de Actividad Económica */
  codigoActividad: string;
  /** Código de Producto o Servicio */
  codigoProducto: string;
  /** Descripción genérica del Producto o Servicio */
  descripcionProducto: string;
}

/**
 * Tipos de documentos que se pueden emitir
 */
export interface SinTipoDocumentoIdentidad {
  /** Código de Tipo de Documento */
  codigoClasificador: string;
  /** Descripción del Tipo de Documento */
  descripcion: string;
}

/**
 * Están definidos para que cada Factura Digital pueda ser enviada por un Servicio Web, lo cual asegura la independencia del mismo en caso de modificaciones o ajustes.
 */
export interface SinTipoDocumentoSector {
  /** Código de Tipo de Documento Sector */
  codigoClasificador?: string;
  /** Descripción del Tipo de Documento Sector */
  descripcion?: string;
}

/**
 * Métodos de generación de documentos digitales
 */
export interface SinTipoEmision {
  /** Código de Tipo de Emisión */
  codigoClasificador: string;
  /** Descripción del Tipo de Emisión */
  descripcion: string;
}

/**
 * Tipos de documentos fiscales
 */
export interface SinTipoFactura {
  /** Código de Tipo de Factura */
  codigoClasificador: string;
  /** Descripción del Tipo de Factura */
  descripcion: string;
}

/**
 * Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes
 */
export interface SinTipoPuntoVenta {
  /** Código de Tipo de Punto de Venta */
  codigoClasificador: string;
  /** Descripción del Tipo de Punto de Venta */
  descripcion: string;
}

/**
 * Las unidades de medida nos permiten cuantificar claramente las existencias de nuestro inventario, estas nos permiten  la correcta interpretación de las cantidades
 */
export interface SinUnidadMedida {
  /** Código de Unidad de Medida */
  codigoClasificador?: number;
  /** Descripción de Unidad de Medida */
  descripcion?: string;
}

/**
 * El CUIS es un valor generado por la Administración Tributaria y que identifica la relación entre el Sistema Informático de Facturación autorizado, credenciales, Contribuyente, sucursal y opcionalmente al punto de venta, es inalterable en su composición y deberá ser parte del envío de Facturas Digitales.
 */
export interface SinCuis {
  /** Código Único de Inicio de Sistema */
  codigo?: string;
  /** Fecha de vigencia del CUIS */
  fechaVigencia?: DateDMYHHMMSS;
}

/**
 * Código Único de Facturación Diaria (CUFD) para el Sistema Informático de Facturación autorizado debe realizarse diariamente. Este código habilita el sistema del Sujeto Pasivo para la emisión de Facturas Digitales durante un periodo de vigencia de 24 horas
 */
export interface SinCufD {
  /** Código Único de Facturación Diaria */
  codigo?: string;
  /** Código de control del CUFD */
  codigoControl?: string;
  /** Dirección de facturación del CUFD */
  direccion?: string;
  /** Fecha de vigencia del CUFD */
  fechaVigencia?: DateDMYHHMMSS;
  /** Fecha de inicio del CUFD */
  fechaInicial?: DateDMYHHMMSS;
}

/**
 * Entrada de datos paramétricos de la entidad como codigos de sucursal o codigos de puntos de venta - El código de sucursal y punto de venta enviado esta restringido a su la restriccion de sucursal y punto de venta - Para verificar las restricciones consulte el servicio usuarioRestriccion
 */
export interface EntidadParamsInput {
  codigoSucursal?: number;
  codigoPuntoVenta?: number;
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface Cliente {
  /** Identificador único del registro. */
  _id?: string;
  /** Razon Social del cliente. */
  razonSocial?: string;
  /** Codigo unico que se asigna al cliente. */
  codigoCliente?: string;
  /** Código del clasificador del tipo documento de identidad. */
  tipoDocumentoIdentidad?: SinTipoDocumentoIdentidad;
  /** Numero de documento del cliente */
  numeroDocumento: string;
  /** Si es C.I., y contenga un numero de complemento */
  complemento?: string;
  /** Nombre del  titular de la cuenta. */
  nombres?: string;
  /** Apellidos del titular de la cuenta. */
  apellidos?: string;
  /** Correo electrónico de la persona, este campo es unico en la organización. */
  email?: string;
  /** Valor que permite el registro de NIT con error. Por defecto, enviar cero (0) o nulo y uno (1) cuando se autorice el NIT. - 0: Se verifica NIT. - 1: No se verifica NIT. */
  codigoExcepcion?: number;
  /** Telefono de referencia */
  telefono?: string;
  /** Si el cliente tiene linea de credito - true: El cliente puede acceder a una linea de credito - false: El cliente no puede acceder a una linea de credito */
  lineaCredito?: boolean;
  /** Credito minimo para acceder a una linea de credito - 0 o nulo: No hay limite */
  creditoMinimo?: number;
  /** Credito maximo para acceder a una linea de credito - 0 o nulo: No hay limite */
  creditoMaximo?: number;
  /** Dirección de residencia del cliente */
  direccion?: string;
  /** Dirección en el cual el cliente desarrolla sus actividades económicas */
  direccionLaboral?: string;
  /** Nombre de la entidad donde el cliente desarrolla sus actividades económicas */
  entidadLaboral?: string;
  /** Máximo plazo (meses) de duración que puede tener un credito - Se contabiliza en Nro de meses. */
  maximoPlazo?: number;
  /** Estado del registro */
  state?: string;
  /** Usuario de creación */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario modificación */
  usumod?: string;
  /** Fecha de actualización del registro */
  UpdatedAt?: DateDMYHHMMSS;
}

/**
 * Datos del punto de venta, asociado a la factura.
 */
export interface PuntoVentaProps {
  /** Codigo del punto de venta. */
  codigo: number;
  /** Catalogo de Tipo de Punto de Venta. */
  tipoPuntoVenta: SinTipoPuntoVenta;
  /** Nombre alias del punto de venta. */
  nombre: string;
  /** Direccion del punto de venta. */
  descripcion: string;
}

/**
 * Estructura de datos para Departamento
 */
export interface Departamento {
  /** Código segun INE */
  codigo?: number;
  /** Código de Pais segun ISO 3166-1 */
  codigoPais?: number;
  /** Sigla del departamento */
  sigla?: string;
  /** Nombre del departamento */
  departamento?: string;
}

/**
 * Datos de la sucursal asociado a cada factura
 */
export interface SucursalProps {
  /** Codigo de la sucursal */
  codigo: number;
  /** Direccion regitrada en cada sucursal */
  direccion: string;
  /** Telefono de referencia de la sucursal */
  telefono: string;
  /** Nombre de departamento de la sucursal */
  departamento: Departamento;
  /** Nombre de municipio de la sucursal */
  municipio?: string;
  /** Define si existe integración con SISTEMA DE ADMINISTRACIÓN TRIBUTARIA */
  // integracionSiat?: boolean;
}

export interface NotaCreditoDebito {
  /** Número de NIT registrado en el Padrón Nacional de Contribuyentes que corresponde a la persona o empresa que emite la factura. */
  nitEmisor?: string;
  /** Razón Social o nombre registrado en el Padrón Nacional de Contribuyentes de la persona o empresa que emite la factura. */
  razonSocialEmisor?: string;
  /** Numeración asignado a la Nota Crédito Débito. */
  numeroNotaCreditoDebito?: number;
  /** Número asignado a la factura original. */
  numeroFactura?: number;
  /** Código único de facturación (CUF). */
  cuf?: string;
  /** Código único de facturación diario (CUFD), valor único que se obtiene al consumir el servicio web correspondiente. */
  cufd?: SinCufD;
  /** Código único de sistema */
  cuis?: SinCuis;
  /** Tipos de documento fiscale. */
  tipoFactura?: SinTipoFactura;
  /** Métodos de generación de documento digital. */
  tipoEmision?: SinTipoEmision;
  /** Sucursal registrada en el Padrón y en la cual se está emitiendo la factura. */
  sucursal?: SucursalProps;
  /** Punto de Venta creado mediante un servicio web y en el cual se emite la factura.. */
  puntoVenta?: PuntoVentaProps;
  /** Fecha y hora en la cual se emite la nota. */
  fechaEmision?: DateDMYHHMMSS;
  /** Datos del cliente */
  cliente: Cliente;
  /** Número de Cuf asignado a la factura original. */
  numeroAutorizacionCuf?: string;
  /** Fecha en la cual se emitió la factura original. */
  fechaEmisionFactura?: DateDMYHHMMSS;
  /** Monto total Sujeto a Crédito fiscal en la factura Original. */
  montoTotalOriginal?: number;
  /** Monto total que está siendo devuelto. */
  montoTotalDevuelto?: number;
  /** Monto total que está siendo devuelto en formato literal. */
  montoTotalLiteral?: string;
  /** Monto de descuento efectuado. */
  montoDescuentoCreditoDebito?: number;
  /** Trece por ciento (13%) del monto total devuelto. */
  montoEfectivoCreditoDebito?: number;
  /** Leyenda asociada a la actividad económica. */
  leyenda?: string;
  /** Sub leyenda del documento fiscal */
  subLeyenda?: string;
  /** Usuario que realizó la transacción */
  usuario?: string;
  /** Tipo de factura que se está emitiendo de la factura original. */
  documentoSectorFactura?: SinTipoDocumentoSector;
  /** Tipo de factura que se está emitiendo. */
  documentoSector?: SinTipoDocumentoSector;
  /** Detalle de los items del documento fiscal. */
  detalle?: NotaDebitoCreditoDetalle[];
  /** Codigo de respuesta una vez validado en los servicios del SIN. */
  codigoRecepcion?: string;
  /** En caso de anulacion, clasificador del motivo de anulación. */
  motivoAnulacion?: SinMotivoAnulacion;
  /** Representacion PDF, XML, ROLLO, ETC */
  representacionGrafica?: UrlsRepresentacionGraficaV2;
  /** Si el documento ha sido revertido */
  reversion?: boolean;
  /** Usuario de creación. */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Fecha de actualización del registro */
  updatedAt?: DateDMYHHMMSS;
  /** Estado del registro */
  state?: string;
}

/**
 * Detalle de items de la nota de credito debito
 */
export interface NotaDebitoCreditoDetalleInput {
  itemFactura: number;
  cantidad: number;
}

export interface NotaDebitoCreditoDetalle {
  /** Nro de item del detalle de la nota credito debito */
  nroItem?: number;
  /** Nro de item del detalle de la factura original. */
  nroItemFactura?: number;
  /** Actividad económica registrada en el Padrón Nacional de Contribuyentes relacionada al NIT. */
  actividadEconomica?: SinActividades;
  /** Homologado a los códigos de productos genéricos enviados por el SIN a través del servicio de sincronización. */
  productoServicio?: SinProductoServicio;
  /** Código/Descripción del producto o servicio. */
  producto?: string;
  /** Descripcion del producto / servicio */
  descripcion?: string;
  /** Cantidad del producto o servicio otorgado */
  cantidad?: number;
  /** Paramétrica que identifica la unidad de medida. */
  unidadMedida?: SinUnidadMedida;
  /** Precio que otorga el contribuyente a su servicio o producto. */
  precioUnitario?: number;
  /** Monto de descuento sobre el producto o servicio específico. */
  montoDescuento?: number;
  /** El subtotal  es igual a la (cantidad * precio unitario) – descuento. */
  subTotal?: number;
  /** Código que permite especificar si se trata de la transacción original (1) o del monto que está siendo devuelto (2). */
  codigoDetalleTransaccion?: number;
}

/**
 * Urls para descargar los documentos en formato representacion gráfica Version 2, mejorada
 */
export interface UrlsRepresentacionGraficaV2 {
  pdf?: UrlRepresentacionGraficaV2;
  xml?: UrlRepresentacionGraficaV2;
  rollo?: UrlRepresentacionGraficaV2;
  rolloResumen?: UrlRepresentacionGraficaV2;
  /** Formato rollo super reducido solo disponible para: - Factura Compra Venta */
  rolloReducido?: UrlRepresentacionGraficaV2;
  sin?: UrlSinRepresentacionGrafica;
}

/**
 * Una conexión a una lista de elementos.
 */
export interface RestNotaCreditoDebitoConnection {
  /** Información para ayudar en la paginación. */
  pageInfo: PageInfo;
  /** Lista de documentos. */
  docs?: NotaCreditoDebito[];
}

/**
 * Parametros de entrada para el registro de una nueva nota de debito-credito.
 */
export interface RestNotaCreditoDebitoInput {
  facturaCuf: string;
  emailCliente: string;
  detalle: NotaDebitoCreditoDetalleInput[];
}
