// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const ARTICULOCOMPOSICIONVENTAFRAGMENT = gql`
  fragment ArticuloComposicionVentaFragment on ArticuloComposicionVenta {
    articulo {
      _id
    }
    receta {
      _id
      nombre
      tiempoPreparacionMinutos
      ingredientes {
        articuloId
        articulo {
          _id
          codigoArticulo
          articuloPrecioId
          nombreArticulo
          articuloPrecioBase {
            _id
            articuloUnidadMedida {
              _id
              codigoUnidadMedida
              nombreUnidadMedida
            }
            monedaPrimaria {
              moneda {
                codigo
              }
              precio
            }
            cantidadBase
            factorAjuste
            umVenta
            umInventario
            umCompra
          }
          articuloPrecio {
            _id
            articuloUnidadMedida {
              _id
              codigoUnidadMedida
              nombreUnidadMedida
            }
            monedaPrimaria {
              precio
            }
            cantidadBase
            factorAjuste
            umVenta
            umInventario
            umCompra
          }
          inventario {
            totalDisponible
            verificarStock
            detalle {
              almacen {
                _id
                codigoAlmacen
                activo
                prioridad
              }
              disponible
              orden
            }
          }
          verificarStock
        }
        cantidadBase
        esRemovible
        permiteExtra
        articuloUnidadMedida {
          _id
          codigoUnidadMedida
          nombreUnidadMedida
        }
      }
    }
    modificadores {
      _id
      nombre
      minSeleccion
      maxSeleccion
      opcionesGratuitas
      opciones {
        articulo {
          _id
          codigoArticulo
          articuloPrecioId
          nombreArticulo
          articuloPrecioBase {
            _id
            articuloUnidadMedida {
              _id
              codigoUnidadMedida
              nombreUnidadMedida
            }
            monedaPrimaria {
              moneda {
                codigo
              }
              precio
            }
            cantidadBase
            factorAjuste
            umVenta
            umInventario
            umCompra
          }
          articuloPrecio {
            _id
            articuloUnidadMedida {
              _id
              codigoUnidadMedida
              nombreUnidadMedida
            }
            monedaPrimaria {
              precio
            }
            cantidadBase
            factorAjuste
            umVenta
            umInventario
            umCompra
          }
          inventario {
            totalDisponible
            verificarStock
            detalle {
              almacen {
                _id
                codigoAlmacen
                activo
                prioridad
              }
              disponible
              orden
            }
          }
          verificarStock
        }
        articuloUnidadMedida {
          _id
          codigoUnidadMedida
          nombreUnidadMedida
        }
        nombreOpcion
        cantidadIncluida
        elegibleParaGratis
        esOpcionAncla
      }
    }
  }
`
