// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const ARTICULOCONNECTIONFRAGMENT = gql`
  fragment ArticuloConnectionFragment on ArticuloConnection {
    pageInfo {
      hasNextPage
      hasPrevPage
      totalDocs
      limit
      page
      totalPages
    }
    docs {
      _id
      codigoArticulo
      articuloPrecioId
      nombreArticulo
      descripcionArticulo
      actividadEconomica {
        codigoCaeb
        descripcion
        tipoActividad
      }
      sinProductoServicio {
        codigoActividad
        codigoProducto
        descripcionProducto
      }
      tipoArticulo {
        _id
        codigo
        descripcion
        grupoUnidadMedida {
          _id
          codigoGrupo
          nombreGrupo
          unidadMedidaBase {
            _id
            codigoUnidadMedida
            nombreUnidadMedida
            sinUnidadMedida {
              codigoClasificador
              descripcion
            }
            longitud
            ancho
            altura
            peso
            volumen
            state
            usucre
            createdAt
            usumod
            updatedAt
          }
          definicion {
            unidadMedida {
              # Datos simples (Tipo ya expandido previamente)
              _id
              codigoUnidadMedida
              nombreUnidadMedida
              longitud
              ancho
              altura
              peso
              volumen
              state
              usucre
              createdAt
              usumod
              updatedAt
            }
            cantidadBase
          }
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        notas
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      proveedor {
        _id
        codigo
        nombre
        direccion
        ciudad
        contacto
        correo
        telefono
        notas
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      imagen {
        id
        filename
        variants {
          thumbnail
          medium
          square
          public
        }
      }
      codigoGrupoUnidadMedida
      grupoUnidadMedida {
        # Datos simples (Tipo ya expandido previamente)
        _id
        codigoGrupo
        nombreGrupo
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      articuloPrecioBase {
        articuloUnidadMedida {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoUnidadMedida
          nombreUnidadMedida
          longitud
          ancho
          altura
          peso
          volumen
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        monedaPrimaria {
          moneda {
            _id
            codigo
            descripcion
            sigla
            tipoCambio
            tipoCambioCompra
            activo
            state
            usucre
            usumod
            createdAt
            updatedAt
          }
          precioBase
          precio
          delivery
          precioComparacion
          manual
        }
        monedaAdicional1 {
          # Datos simples (Tipo ya expandido previamente)
          precioBase
          precio
          delivery
          precioComparacion
          manual
        }
        monedaAdicional2 {
          # Datos simples (Tipo ya expandido previamente)
          precioBase
          precio
          delivery
          precioComparacion
          manual
        }
        monedaAdicional3 {
          # Datos simples (Tipo ya expandido previamente)
          precioBase
          precio
          delivery
          precioComparacion
          manual
        }
        cantidadBase
        descuento {
          fechaInicial
          fechaFinal
          porcentaje
          cantidad {
            nro
            porcentaje
          }
        }
        imagen {
          # Datos simples (Tipo ya expandido previamente)
          id
          filename
        }
        factorAjuste
        umVenta
        umInventario
        umCompra
      }
      articuloPrecio {
        # Datos simples (Tipo ya expandido previamente)
        cantidadBase
        factorAjuste
        umVenta
        umInventario
        umCompra
      }
      articuloVenta
      articuloInventario
      articuloCompra
      inventario {
        _id
        codigoArticulo
        nombreArticulo
        tipoArticulo
        sucursal {
          codigo
          direccion
          telefono
          departamento {
            codigo
            codigoPais
            sigla
            departamento
          }
          municipio
          integracionSiat
        }
        kardexPeriodo {
          codigo
          descripcion
          documentoSector {
            codigoClasificador
            descripcion
          }
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        grupoUnidadMedida {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoGrupo
          nombreGrupo
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        unidadMedida {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoUnidadMedida
          nombreUnidadMedida
          longitud
          ancho
          altura
          peso
          volumen
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        unidadMedidaVentas {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoUnidadMedida
          nombreUnidadMedida
          longitud
          ancho
          altura
          peso
          volumen
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        unidadMedidaInventario {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoUnidadMedida
          nombreUnidadMedida
          longitud
          ancho
          altura
          peso
          volumen
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        unidadMedidaCompras {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoUnidadMedida
          nombreUnidadMedida
          longitud
          ancho
          altura
          peso
          volumen
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        detalle {
          almacen {
            _id
            codigoAlmacen
            nombre
            ubicacion
            sucursal {
              # Datos simples (Tipo ya expandido previamente)
              codigo
              direccion
              telefono
              municipio
              integracionSiat
            }
            tipo
            activo
            prioridad
            state
            usucre
            createdAt
            usumod
            updatedAt
          }
          stock
          comprometido
          solicitado
          disponible
          orden
          lotes {
            codigoLote
            lote {
              _id
              codigoLote
              descripcion
              codigoArticulo
              # Límite de profundidad alcanzado
              sucursal {
                id
              }
              atributo1
              atributo2
              atributo3
              fechaAdmision
              fechaFabricacion
              fechaVencimiento
              state
              usucre
              createdAt
              usumod
              updatedAt
            }
            stock
            comprometido
            solicitado
            disponible
          }
        }
        totalStock
        totalComprometido
        totalSolicitado
        totalDisponible
        verificarStock
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      claseArticulo
      impresoras {
        _id
        sucursal {
          codigo
          direccion
          telefono
          departamento {
            # Datos simples (Tipo ya expandido previamente)
            codigo
            codigoPais
            sigla
            departamento
          }
          municipio
          integracionSiat
        }
        puntoVenta {
          codigo
          tipoPuntoVenta {
            codigoClasificador
            descripcion
          }
          nombre
          descripcion
        }
        nombre
        descripcion
        atributo1
        atributo2
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      grupoArticulo {
        codigoGrupoArticulo
        nombreGrupoArticulo
      }
      gestionArticulo
      verificarStock
      activo
      complemento
      listaComplemento {
        id
        codigoArticulo
        nombreArticulo
      }
      state
      usucre
      createdAt
      usumod
      updatedAt
    }
  }
`
