// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const METODOPAGOFRAGMENT = gql`
  fragment MetodoPagoFragment on MetodoPago {
    codigoClasificador
    descripcion
  }
`
