// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const RESTPEDIDOMESASOCUPADASFRAGMENT = gql`
  fragment restPedidoMesasOcupadasFragment on restPedidoMesasOcupadas {
    _id
    mesa {
      nombre
      nroComensales
      ubicacion
    }
    puntoVenta {
      codigo
      tipoPuntoVenta {
        codigoClasificador
        descripcion
      }
      nombre
      descripcion
    }
    numeroPedido
    numeroOrden
    pedidoId
    codigoSucursal
    codigoPuntoVenta
    usucre
  }
`
