// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const RESTPEDIDOFRAGMENT = gql`
  fragment RestPedidoFragment on RestPedido {
    _id
    numeroPedido
    numeroOrden
    marcaKardex
    sucursal {
      codigo
      direccion
      telefono
      departamento {
        codigo
        codigoPais
        sigla
        departamento
      }
      municipio
      integracionSiat
    }
    puntoVenta {
      codigo
      tipoPuntoVenta {
        codigoClasificador
        descripcion
      }
      nombre
      descripcion
    }
    kardexPeriodo {
      codigo
      descripcion
      documentoSector {
        codigoClasificador
        descripcion
      }
      state
      usucre
      createdAt
      usumod
      updatedAt
    }
    mesa {
      nombre
      nroComensales
      ubicacion
    }
    productos {
      articuloId
      nroItem
      tipoArticulo {
        codigo
        descripcion
      }
      claseArticulo
      gestionArticulo
      grupoArticulo {
        codigoGrupoArticulo
        nombreGrupoArticulo
      }
      codigoArticulo
      nombreArticulo
      almacen {
        _id
        codigoAlmacen
        nombre
        ubicacion
        sucursal {
          # Datos simples (Tipo ya expandido previamente)
          codigo
          direccion
          telefono
          municipio
          integracionSiat
        }
        tipo
        activo
        prioridad
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      lote {
        _id
        codigoLote
        descripcion
        codigoArticulo
        sucursal {
          # Datos simples (Tipo ya expandido previamente)
          codigo
          direccion
          telefono
          municipio
          integracionSiat
        }
        atributo1
        atributo2
        atributo3
        fechaAdmision
        fechaFabricacion
        fechaVencimiento
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      codigoGrupo
      sinProductoServicio {
        codigoActividad
        codigoProducto
        descripcionProducto
      }
      articuloPrecioBase {
        articuloUnidadMedida {
          _id
          codigoUnidadMedida
          nombreUnidadMedida
          sinUnidadMedida {
            codigoClasificador
            descripcion
          }
          longitud
          ancho
          altura
          peso
          volumen
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        monedaPrecio {
          moneda {
            _id
            codigo
            descripcion
            sigla
            tipoCambio
            tipoCambioCompra
            activo
            state
            usucre
            usumod
            createdAt
            updatedAt
          }
          precioBase
          precio
        }
        moneda {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigo
          descripcion
          sigla
          tipoCambio
          tipoCambioCompra
          activo
          state
          usucre
          usumod
          createdAt
          updatedAt
        }
        tipoCambio
        estructuraValor {
          tipoOperacion
          valorBase
          valorBaseAnterior
          descuento
          descuentoAdicional
          valorNeto
          impuestoUnitario
          gastoAdicional
          variacion
          valorFinal
          totales {
            subtotalBruto
            totalDescuento
            subtotalNeto
            totalImpuestos
            totalGasto
            totalFinal
          }
        }
        tipoOperacion
        valor
        cantidadBase
        cantidad
        cantidadFactor
        descuento
        descuentoAdicional
        otrosCostos
        impuesto
        incluyeImpuesto
        esDescuentoTotal
        factorAjuste
      }
      articuloPrecio {
        # Datos simples (Tipo ya expandido previamente)
        tipoCambio
        tipoOperacion
        valor
        cantidadBase
        cantidad
        cantidadFactor
        descuento
        descuentoAdicional
        otrosCostos
        impuesto
        incluyeImpuesto
        esDescuentoTotal
        factorAjuste
      }
      detalleExtra
      nota
      notaRapida {
        cantidad
        valor
        atributo1
        atributo2
      }
      verificarStock
      complementos {
        articuloId
        nroItem
        tipoArticulo {
          # Datos simples (Tipo ya expandido previamente)
          codigo
          descripcion
        }
        claseArticulo
        grupoArticulo {
          # Datos simples (Tipo ya expandido previamente)
          codigoGrupoArticulo
          nombreGrupoArticulo
        }
        codigoArticulo
        nombreArticulo
        almacen {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoAlmacen
          nombre
          ubicacion
          tipo
          activo
          prioridad
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        lote {
          # Datos simples (Tipo ya expandido previamente)
          _id
          codigoLote
          descripcion
          codigoArticulo
          atributo1
          atributo2
          atributo3
          fechaAdmision
          fechaFabricacion
          fechaVencimiento
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        codigoGrupo
        sinProductoServicio {
          # Datos simples (Tipo ya expandido previamente)
          codigoActividad
          codigoProducto
          descripcionProducto
        }
        articuloPrecioBase {
          # Datos simples (Tipo ya expandido previamente)
          tipoCambio
          tipoOperacion
          valor
          cantidadBase
          cantidad
          cantidadFactor
          descuento
          descuentoAdicional
          otrosCostos
          impuesto
          incluyeImpuesto
          esDescuentoTotal
          factorAjuste
        }
        articuloPrecio {
          # Datos simples (Tipo ya expandido previamente)
          tipoCambio
          tipoOperacion
          valor
          cantidadBase
          cantidad
          cantidadFactor
          descuento
          descuentoAdicional
          otrosCostos
          impuesto
          incluyeImpuesto
          esDescuentoTotal
          factorAjuste
        }
        detalleExtra
        nota
        verificarStock
      }
      impresoras {
        _id
        sucursal {
          codigo
          direccion
          telefono
          departamento {
            # Datos simples (Tipo ya expandido previamente)
            codigo
            codigoPais
            sigla
            departamento
          }
          municipio
          integracionSiat
        }
        puntoVenta {
          codigo
          tipoPuntoVenta {
            # Datos simples (Tipo ya expandido previamente)
            codigoClasificador
            descripcion
          }
          nombre
          descripcion
        }
        nombre
        descripcion
        atributo1
        atributo2
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      cortesia
      state
    }
    productosEliminados {
      # Datos simples (Tipo ya expandido previamente)
      articuloId
      nroItem
      claseArticulo
      gestionArticulo
      codigoArticulo
      nombreArticulo
      codigoGrupo
      detalleExtra
      nota
      verificarStock
      cortesia
      state
    }
    ultimaTransaccionProductos {
      # Datos simples (Tipo ya expandido previamente)
      articuloId
      nroItem
      claseArticulo
      gestionArticulo
      codigoArticulo
      nombreArticulo
      codigoGrupo
      detalleExtra
      nota
      verificarStock
      cortesia
      state
    }
    moneda {
      # Datos simples (Tipo ya expandido previamente)
      _id
      codigo
      descripcion
      sigla
      tipoCambio
      tipoCambioCompra
      activo
      state
      usucre
      usumod
      createdAt
      updatedAt
    }
    tipoCambio
    tipo
    descuentoAdicional
    otrosCostos
    descripcionOtrosCostos
    fechaDocumento
    fechaContable
    cliente {
      razonSocial
      codigoCliente
      tipoDocumentoIdentidad {
        codigoClasificador
        descripcion
      }
      numeroDocumento
      complemento
      nombres
      apellidos
      email
      telefono
      lineaCredito
      creditoMinimo
      creditoMaximo
      direccion
      direccionLaboral
      entidadLaboral
      maximoPlazo
    }
    metodoPago {
      codigoClasificador
      descripcion
    }
    numeroTarjeta
    metodoPagoVenta {
      metodoPago {
        # Datos simples (Tipo ya expandido previamente)
        codigoClasificador
        descripcion
      }
      monto
    }
    montoTotal
    montoTotalBase
    fechaEntrega
    direccionEntrega
    detalleExtra
    tipoDocumento
    refNroDocumento
    refDocumento
    nota
    notaRapida {
      # Datos simples (Tipo ya expandido previamente)
      cantidad
      valor
      atributo1
      atributo2
    }
    terminos
    representacionGrafica {
      pdf
      xml
      rollo
      sin
    }
    motivoAnulacion {
      codigoClasificador
      descripcion
    }
    descripcionAnulacion
    espacio
    atributo1
    atributo2
    atributo3
    atributo4
    state
    usucre
    createdAt
    usumod
    updatedAt
    historial {
      nro
      articuloOperacion {
        # Datos simples (Tipo ya expandido previamente)
        articuloId
        nroItem
        claseArticulo
        gestionArticulo
        codigoArticulo
        nombreArticulo
        codigoGrupo
        detalleExtra
        nota
        verificarStock
        cortesia
        state
      }
      fecha
    }
    arqueoCajaId
  }
`
