// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const RESTESPACIOFRAGMENT = gql`
  fragment RestEspacioFragment on RestEspacio {
    _id
    descripcion
    nroMesas
    sucursal {
      codigo
      direccion
      telefono
      departamento {
        codigo
        codigoPais
        sigla
        departamento
      }
      municipio
      integracionSiat
    }
    puntoVenta {
      codigo
      tipoPuntoVenta {
        codigoClasificador
        descripcion
      }
      nombre
      descripcion
    }
    atributo1
    atributo2
    atributo3
    atributo4
    default
    state
    usucre
    createdAt
    usumod
    updatedAt
  }
`
