// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client'

export const RESTPEDIDOFACTURAFRAGMENT = gql`
  fragment RestPedidoFacturaFragment on RestPedidoFactura {
    factura {
      _id
      nitEmisor
      razonSocialEmisor
      numeroFactura
      tipoFactura {
        codigoClasificador
        descripcion
      }
      tipoEmision {
        codigoClasificador
        descripcion
      }
      cuf
      cufd {
        codigo
        codigoControl
        direccion
        fechaVigencia
        fechaInicial
      }
      cuis {
        codigo
        fechaVigencia
      }
      sucursal {
        codigo
        direccion
        telefono
        departamento {
          codigo
          codigoPais
          sigla
          departamento
        }
        municipio
        integracionSiat
      }
      puntoVenta {
        codigo
        tipoPuntoVenta {
          codigoClasificador
          descripcion
        }
        nombre
        descripcion
      }
      fechaEmision
      cliente {
        razonSocial
        codigoCliente
        tipoDocumentoIdentidad {
          codigoClasificador
          descripcion
        }
        numeroDocumento
        complemento
        nombres
        apellidos
        email
        telefono
        lineaCredito
        creditoMinimo
        creditoMaximo
        direccion
        direccionLaboral
        entidadLaboral
        maximoPlazo
      }
      metodoPago {
        codigoClasificador
        descripcion
      }
      numeroTarjeta
      montoTotal
      montoTotalLiteral
      montoTotalSujetoIva
      moneda {
        codigoClasificador
        descripcion
      }
      tipoCambio
      montoTotalMoneda
      montoGiftCard
      descuentoAdicional
      cafc
      leyenda
      subLeyenda
      usuario
      documentoSector {
        codigoClasificador
        descripcion
      }
      motivoAnulacion {
        codigoClasificador
        descripcion
      }
      detalleExtra
      detalle {
        nroItem
        actividadEconomica {
          codigoCaeb
          descripcion
          tipoActividad
        }
        productoServicio {
          codigoActividad
          codigoProducto
          descripcionProducto
        }
        producto
        descripcion
        cantidad
        unidadMedida {
          codigoClasificador
          descripcion
        }
        precioUnitario
        montoDescuento
        subTotal
        numeroSerie
        numeroImei
        detalleExtra
        log
      }
      eventoSignificativo
      codigoRecepcion
      representacionGrafica {
        pdf
        xml
        rollo
        rolloResumen
        rolloReducido
        sin
      }
      usucre
      createdAt
      usumod
      updatedAt
      state
      referencia
      tipoVenta
      log
    }
    pedido {
      _id
      numeroPedido
      numeroOrden
      marcaKardex
      sucursal {
        # Datos simples (Tipo ya expandido previamente)
        codigo
        direccion
        telefono
        municipio
        integracionSiat
      }
      puntoVenta {
        # Datos simples (Tipo ya expandido previamente)
        codigo
        nombre
        descripcion
      }
      kardexPeriodo {
        codigo
        descripcion
        documentoSector {
          # Datos simples (Tipo ya expandido previamente)
          codigoClasificador
          descripcion
        }
        state
        usucre
        createdAt
        usumod
        updatedAt
      }
      mesa {
        nombre
        nroComensales
        ubicacion
      }
      productos {
        articuloId
        nroItem
        tipoArticulo {
          codigo
          descripcion
        }
        claseArticulo
        gestionArticulo
        grupoArticulo {
          codigoGrupoArticulo
          nombreGrupoArticulo
        }
        codigoArticulo
        nombreArticulo
        almacen {
          _id
          codigoAlmacen
          nombre
          ubicacion
          sucursal {
            # Datos simples (Tipo ya expandido previamente)
            codigo
            direccion
            telefono
            municipio
            integracionSiat
          }
          tipo
          activo
          prioridad
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        lote {
          _id
          codigoLote
          descripcion
          codigoArticulo
          sucursal {
            # Datos simples (Tipo ya expandido previamente)
            codigo
            direccion
            telefono
            municipio
            integracionSiat
          }
          atributo1
          atributo2
          atributo3
          fechaAdmision
          fechaFabricacion
          fechaVencimiento
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        codigoGrupo
        sinProductoServicio {
          # Datos simples (Tipo ya expandido previamente)
          codigoActividad
          codigoProducto
          descripcionProducto
        }
        articuloPrecioBase {
          articuloUnidadMedida {
            _id
            codigoUnidadMedida
            nombreUnidadMedida
            sinUnidadMedida {
              # Datos simples (Tipo ya expandido previamente)
              codigoClasificador
              descripcion
            }
            longitud
            ancho
            altura
            peso
            volumen
            state
            usucre
            createdAt
            usumod
            updatedAt
          }
          monedaPrecio {
            moneda {
              _id
              codigo
              descripcion
              sigla
              tipoCambio
              tipoCambioCompra
              activo
              state
              usucre
              usumod
              createdAt
              updatedAt
            }
            precioBase
            precio
          }
          moneda {
            # Datos simples (Tipo ya expandido previamente)
            _id
            codigo
            descripcion
            sigla
            tipoCambio
            tipoCambioCompra
            activo
            state
            usucre
            usumod
            createdAt
            updatedAt
          }
          tipoCambio
          estructuraValor {
            tipoOperacion
            valor
            valorAnterior
            descuento
            descuentoAdicional
            descuentoTotal
            descuentoP
            descuentoAdicionalP
            descuentoTotalP
            valorNeto
            impuestoUnitario
            gastoAdicional
            variacion
            valorFinal
            totales {
              subtotalBruto
              totalDescuento
              totalDescuentoP
              totalDescuentoAdicional
              totalDescuentoGeneral
              totalDescuentoAdicionalP
              totalDescuentoGeneralP
              subtotalNeto
              totalImpuestos
              totalGasto
              totalFinal
            }
          }
          tipoOperacion
          valor
          cantidadBase
          cantidad
          cantidadFactor
          descuento
          descuentoAdicional
          otrosCostos
          impuesto
          incluyeImpuesto
          esDescuentoTotal
          factorAjuste
        }
        articuloPrecio {
          # Datos simples (Tipo ya expandido previamente)
          tipoCambio
          tipoOperacion
          valor
          cantidadBase
          cantidad
          cantidadFactor
          descuento
          descuentoAdicional
          otrosCostos
          impuesto
          incluyeImpuesto
          esDescuentoTotal
          factorAjuste
        }
        detalleExtra
        nota
        notaRapida {
          cantidad
          valor
          atributo1
          atributo2
        }
        verificarStock
        complementos {
          articuloId
          nroItem
          tipoArticulo {
            # Datos simples (Tipo ya expandido previamente)
            codigo
            descripcion
          }
          claseArticulo
          grupoArticulo {
            # Datos simples (Tipo ya expandido previamente)
            codigoGrupoArticulo
            nombreGrupoArticulo
          }
          codigoArticulo
          nombreArticulo
          almacen {
            # Datos simples (Tipo ya expandido previamente)
            _id
            codigoAlmacen
            nombre
            ubicacion
            tipo
            activo
            prioridad
            state
            usucre
            createdAt
            usumod
            updatedAt
          }
          lote {
            # Datos simples (Tipo ya expandido previamente)
            _id
            codigoLote
            descripcion
            codigoArticulo
            atributo1
            atributo2
            atributo3
            fechaAdmision
            fechaFabricacion
            fechaVencimiento
            state
            usucre
            createdAt
            usumod
            updatedAt
          }
          codigoGrupo
          sinProductoServicio {
            # Datos simples (Tipo ya expandido previamente)
            codigoActividad
            codigoProducto
            descripcionProducto
          }
          articuloPrecioBase {
            # Datos simples (Tipo ya expandido previamente)
            tipoCambio
            tipoOperacion
            valor
            cantidadBase
            cantidad
            cantidadFactor
            descuento
            descuentoAdicional
            otrosCostos
            impuesto
            incluyeImpuesto
            esDescuentoTotal
            factorAjuste
          }
          articuloPrecio {
            # Datos simples (Tipo ya expandido previamente)
            tipoCambio
            tipoOperacion
            valor
            cantidadBase
            cantidad
            cantidadFactor
            descuento
            descuentoAdicional
            otrosCostos
            impuesto
            incluyeImpuesto
            esDescuentoTotal
            factorAjuste
          }
          detalleExtra
          nota
          verificarStock
        }
        impresoras {
          _id
          sucursal {
            codigo
            direccion
            telefono
            departamento {
              # Datos simples (Tipo ya expandido previamente)
              codigo
              codigoPais
              sigla
              departamento
            }
            municipio
            integracionSiat
          }
          puntoVenta {
            codigo
            tipoPuntoVenta {
              # Datos simples (Tipo ya expandido previamente)
              codigoClasificador
              descripcion
            }
            nombre
            descripcion
          }
          nombre
          descripcion
          atributo1
          atributo2
          state
          usucre
          createdAt
          usumod
          updatedAt
        }
        cortesia
        state
      }
      productosEliminados {
        # Datos simples (Tipo ya expandido previamente)
        articuloId
        nroItem
        claseArticulo
        gestionArticulo
        codigoArticulo
        nombreArticulo
        codigoGrupo
        detalleExtra
        nota
        verificarStock
        cortesia
        state
      }
      ultimaTransaccionProductos {
        # Datos simples (Tipo ya expandido previamente)
        articuloId
        nroItem
        claseArticulo
        gestionArticulo
        codigoArticulo
        nombreArticulo
        codigoGrupo
        detalleExtra
        nota
        verificarStock
        cortesia
        state
      }
      moneda {
        # Datos simples (Tipo ya expandido previamente)
        _id
        codigo
        descripcion
        sigla
        tipoCambio
        tipoCambioCompra
        activo
        state
        usucre
        usumod
        createdAt
        updatedAt
      }
      tipoCambio
      tipo
      descuentoAdicional
      otrosCostos
      descripcionOtrosCostos
      fechaDocumento
      fechaContable
      cliente {
        # Datos simples (Tipo ya expandido previamente)
        razonSocial
        codigoCliente
        numeroDocumento
        complemento
        nombres
        apellidos
        email
        telefono
        lineaCredito
        creditoMinimo
        creditoMaximo
        direccion
        direccionLaboral
        entidadLaboral
        maximoPlazo
      }
      metodoPago {
        codigoClasificador
        descripcion
      }
      numeroTarjeta
      metodoPagoVenta {
        metodoPago {
          # Datos simples (Tipo ya expandido previamente)
          codigoClasificador
          descripcion
        }
        monto
      }
      montoTotal
      montoTotalBase
      totales {
        operacion {
          # Datos simples (Tipo ya expandido previamente)
          subtotalBruto
          totalDescuento
          totalDescuentoP
          totalDescuentoAdicional
          totalDescuentoGeneral
          totalDescuentoAdicionalP
          totalDescuentoGeneralP
          subtotalNeto
          totalImpuestos
          totalGasto
          totalFinal
        }
        sistema {
          # Datos simples (Tipo ya expandido previamente)
          subtotalBruto
          totalDescuento
          totalDescuentoP
          totalDescuentoAdicional
          totalDescuentoGeneral
          totalDescuentoAdicionalP
          totalDescuentoGeneralP
          subtotalNeto
          totalImpuestos
          totalGasto
          totalFinal
        }
      }
      fechaEntrega
      direccionEntrega
      detalleExtra
      tipoDocumento
      refNroDocumento
      refDocumento
      nota
      notaRapida {
        # Datos simples (Tipo ya expandido previamente)
        cantidad
        valor
        atributo1
        atributo2
      }
      terminos
      representacionGrafica {
        pdf
        xml
        rollo
        sin
      }
      motivoAnulacion {
        # Datos simples (Tipo ya expandido previamente)
        codigoClasificador
        descripcion
      }
      descripcionAnulacion
      espacio
      atributo1
      atributo2
      atributo3
      atributo4
      state
      usucre
      createdAt
      usumod
      updatedAt
      historial {
        nro
        articuloOperacion {
          # Datos simples (Tipo ya expandido previamente)
          articuloId
          nroItem
          claseArticulo
          gestionArticulo
          codigoArticulo
          nombreArticulo
          codigoGrupo
          detalleExtra
          nota
          verificarStock
          cortesia
          state
        }
        fecha
      }
      arqueoCajaId
    }
  }
`
