// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const MONEDA_FRAGMENT = gql`
  fragment MonedaFields on Moneda {
    _id
    codigo
    descripcion
    sigla
    tipoCambio
  }
`;

export const ARTICULO_OPERACION_FRAGMENT = gql`
  fragment ArticuloOperacionFields on ArticuloOperacion {
    articuloId
    nroItem
    codigoArticulo
    nombreArticulo
    articuloPrecio {
      articuloUnidadMedida {
        _id
        codigoUnidadMedida
        nombreUnidadMedida
      }
      moneda {
        ...MonedaFields
      }
      tipoCambio
      valor
      cantidad
      cantidadFactor
      descuento
      impuesto
    }
    state
  }
  ${MONEDA_FRAGMENT}
`;

export const REST_PEDIDO_FRAGMENT = gql`
  fragment RestPedidoFields on RestPedido {
    _id
    numeroPedido
    numeroOrden
    mesa {
      nombre
      nroComensales
      ubicacion
    }
    productos {
      ...ArticuloOperacionFields
    }
    montoTotal
    montoTotalBase
    state
    createdAt
    updatedAt
  }
  ${ARTICULO_OPERACION_FRAGMENT}
`;