// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const SINMOTIVOANULACIONFRAGMENT = gql`
  fragment SinMotivoAnulacionFragment on SinMotivoAnulacion {
    codigoClasificador
    descripcion
  }
`;