// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const TIPOARTICULOCONNECTIONFRAGMENT = gql`
  fragment TipoArticuloConnectionFragment on TipoArticuloConnection {
    docs {
      _id
        codigo
        descripcion
        grupoUnidadMedida {
          _id
              codigoGrupo
              nombreGrupo
              unidadMedidaBase {
                _id
                      codigoUnidadMedida
                      nombreUnidadMedida
                      sinUnidadMedida {
                        codigoClasificador
                                descripcion
                      }
                      longitud
                      ancho
                      altura
                      peso
                      volumen
                      state
                      usucre
                      createdAt
                      usumod
                      updatedAt
              }
              definicion {
                unidadMedida {
                        # Datos simples (Tipo ya expandido previamente)
                        _id
                        codigoUnidadMedida
                        nombreUnidadMedida
                        longitud
                        ancho
                        altura
                        peso
                        volumen
                        state
                        usucre
                        createdAt
                        usumod
                        updatedAt
                      }
                      cantidadBase
              }
              state
              usucre
              createdAt
              usumod
              updatedAt
        }
        notas
        state
        usucre
        createdAt
        usumod
        updatedAt
    }
    pageInfo {
      hasNextPage
        hasPrevPage
        totalDocs
        limit
        page
        totalPages
    }
  }
`;