// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const WAAPIFRAGMENT = gql`
  fragment WaapiFragment on Waapi {
    _id
    codigoSucursal
    codigoPuntoVenta
    mensaje
    mediaName
    mediaUrl
    codigoArea
    telefono
    glosa
    waapiStatus
    state
    usucre
    usumod
    createdAt
    updatedAt
  }
`;