// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

/**
 * Date in DD/MM/YYYY HH:MM:SS format
 */
export type DateDMYHHMMSS = string;
/**
 * Url de consulta documentos de inventarios, para la obtención de la representación impresa, uso de Buffer para la generacion de archivos 
 */
export type UrlInvConsultaDocumento = string;
/**
 * Información para ayudar en la paginación.
 */
export interface PageInfo {
  /** Al paginar hacia adelante, ¿hay más elementos? */
  hasNextPage: boolean;
  /** Al paginar hacia atrás, ¿hay más elementos? */
  hasPrevPage: boolean;
  /** Número total de registros */
  totalDocs?: number;
  /** Agrupador de registros */
  limit?: number;
  /** Pagina Actual de consulta */
  page?: number;
  /** Total de paginas */
  totalPages?: number;
}

/**
 * Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes
 */
export interface SinTipoPuntoVenta {
  /** Código de Tipo de Punto de Venta */
  codigoClasificador: string;
  /** Descripción del Tipo de Punto de Venta */
  descripcion: string;
}

/**
 * Datos de la moneda asignado a datos personales del usuario, ejemplo PERFIL
 */
export interface MonedaParams {
  /** Código del clasificador de monedas */
  codigo?: number;
  /** Descripción de la moneda */
  descripcion?: string;
  /** Sigla de la moneda */
  sigla?: string;
}

/**
 * Entrada de datos paramétricos de la entidad como codigos de sucursal o codigos de puntos de venta - El código de sucursal y punto de venta enviado esta restringido a su la restriccion de sucursal y punto de venta - Para verificar las restricciones consulte el servicio usuarioRestriccion
 */
export interface EntidadParamsInput {
  /** Codigo de sucursal */
  codigoSucursal?: number;
  /** Código de punto de venta */
  codigoPuntoVenta?: number;
}

/**
 * Datos del punto de venta minificados
 */
export interface PuntoVenta {
  /** Código único del punto de venta */
  codigo?: number;
  /** - Comisionistas de acuerdo a normativa vigente; - Ventanilla de Cobranza autorizada por la ASFI según normativa; - Puntos de Ventas Móviles para venta de bienes o prestación de servicios; - Puntos de Venta YPFB para la venta de combustible a precio internacional; - Puntos de Venta (Cajeros o similares) para la venta de otros bienes y/o prestación de servicios. - Puntos de Venta conjunta, habilitada para emisión conjunta de documentos fiscales. */
  tipoPuntoVenta?: SinTipoPuntoVenta;
  /** Nombre, Alias del punto de venta */
  nombre?: string;
  /** Descripción del punto de venta */
  descripcion?: string;
}

/**
 * Las sucursales son establecimientos secundarios donde se realiza alguna de las actividades económicas del Contribuyente, tienen una dirección física y están registradas en el Padrón Nacional de Contribuyentes. En el Sistema de Facturación, la emisión de las facturas se realiza por sucursal o casa matriz (sucursal 0).
 */
export interface Sucursal {
  /** Codigo único de la sucursal */
  codigo?: number;
  /** Direccion de la sucursal */
  direccion?: string;
  /** Teléfono de referencia */
  telefono?: string;
  /** Datos del departamento */
  departamento?: Departamento;
  /** Municipio donde se encuentra la sucursal */
  municipio?: string;
  /** Si cuenta con integracion SIAT */
  integracionSiat?: boolean;
}

/**
 * Estructura de datos para Departamento
 */
export interface Departamento {
  /** Código segun INE */
  codigo?: number;
  /** Código de Pais segun ISO 3166-1 */
  codigoPais?: number;
  /** Sigla del departamento */
  sigla?: string;
  /** Nombre del departamento */
  departamento?: string;
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface MetodoPago {
  /** Razon Social del cliente. */
  codigoClasificador?: number;
  /** Codigo unico que se asigna al cliente. */
  descripcion?: string;
}

/**
 * Una conexión a una lista de elementos.
 */
export interface CajaConnection {
  /** Información para ayudar en la paginación. */
  pageInfo: PageInfo;
  /** Lista de documentos. */
  docs?: Caja[];
}

/**
 * Responsable por turno en la caja
 */
export interface CajaUsuario {
  /** Nombre de usuario responsable */
  usuario?: string;
}

/**
 * Datos del esquema Caja
 */
export interface Caja {
  /** Identificador interno del registro */
  _id?: string;
  /** Código Único que identifica a la caja */
  codigo?: string;
  /** Sucursal asociado a la caja */
  sucursal?: Sucursal;
  /** Listado de puntos de venta asociados a la caja */
  puntoVenta?: PuntoVenta[];
  /** Dominio de usuarios que pueden realizar la apertura de caja */
  usuarios?: CajaUsuario[];
  /** Saldo inicial en caja antes de ingresar a operaciones */
  saldoInicial?: number;
  /** Saldo actual según la ultima apertura de caja */
  saldoActual?: number;
  /** Nombre de usuario del responsable de caja según los turnos */
  responsable?: CajaUsuario[];
  /** Nombre del ultimo usuario de apertura de caja */
  usuarioApertura?: string;
  /** Fecha de ultimo cierre de caja */
  fechaUltimoCierre?: DateDMYHHMMSS;
  /** Relación con el ultimo arqueo de caja */
  ultimoArqueoCajaId?: string;
  /** Ubicación física de la caja */
  ubicacion?: string;
  /** Estado del registro * ELABORADO = Estado inerte del registro antes de ingresar a operaciones * ABIERTO = Ocupado para transacciones * CERRADO = Libre para asignación * ARQUEO = Conteo de dinero */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Una conexión a una lista de elementos.
 */
export interface ArqueoCajaConnection {
  /** Información para ayudar en la paginación. */
  pageInfo: PageInfo;
  /** Lista de documentos. */
  docs?: ArqueoCaja[];
}

/**
 * Comprobante de retiro de caja
 */
export interface ArqueoCajaComprobante {
  /** Tipo de comprobante - FACTURA O NOTA_VENTA - Número referencial del comprobante */
  tipo?: string;
  numero?: string;
}

/**
 * Datos de entrada para la apertura de caja
 */
export interface AperturaCajaRegistroInput {
  /** Mótivo del retiro */
  montoInicial: number;
  /** Monto retirado */
  observacion?: string;
  /** Identificador interno del turno de la caja */
  turnoCajaId: string;
}

/**
 * Metodos de pago para el arqueo de caja
 */
export interface ArqueoCajaMetodoPago {
  /** Según el clasificador de métodos de pago */
  metodoPago?: MetodoPago;
  /** Monto de pago generado por el sistema */
  monto?: number;
  /** Monto registrado por el usuario */
  montoUsuario?: number;
}

/**
 * Datos del esquema para el retiro de efectivo en caja
 */
export interface ArqueoCajaRetiro {
  /** Mótivo del retiro */
  motivo?: string;
  /** Monto retirado */
  monto?: number;
  /** Quien es el beneficiario del retiro */
  beneficiario?: string;
  /** Usuario que realiza el retiro de caja */
  usuario?: string;
  /** Usuario que aprueba el retiro de Caja */
  aprobador?: string;
  /** Detalle de comprobante de retiro */
  comprobante?: ArqueoCajaComprobante;
  /** Fecha y hora de retiro */
  fecha?: DateDMYHHMMSS;
  /** Representación grafica del reporte de ventas */
  representacionGrafica?: ArqueoCajaRepresentacionGrafica;
}

/**
 * Datos del esquema para el retiro de efectivo en caja
 */
export interface ArqueoCajaIngreso {
  /** Mótivo del retiro */
  motivo?: string;
  /** Monto retirado */
  monto?: number;
  /** Usuario que realiza el ingreso de caja */
  usuario?: string;
  /** Usuario que aprueba el retiro de Caja */
  aprobador?: string;
  /** Fecha y hora de retiro */
  fecha?: DateDMYHHMMSS;
}

/**
 * Estructura de cortesias para el reporte de arqueo de caja
 */
export interface ArqueoCajaCortesia {
  /** Número de ventas realizadas que contienen al menos 1 cortesia. */
  conteoPedidos?: number;
  /** Número total de articulos de venta por cortesia */
  conteoArticulos?: number;
  /** Monto total de perdida por cortesia */
  montoTotal?: number;
}

/**
 * Estructura de observaciones para los arqueos de caja
 */
export interface ArqueoCajaObservacion {
  /** Fecha de la observacion */
  fecha?: DateDMYHHMMSS;
  /** Acción generada por el backend, en función a tipo de servicio ejecutado */
  accion?: string;
  /** Usuario que realizó la acción */
  usuario?: string;
  /** Observacion registrada por el usuario */
  observacion?: string;
}

/**
 * Datos del esquema Caja
 */
export interface ArqueoCaja {
  /** Identificador interno del registro */
  _id?: string;
  /** Referencia a la caja */
  cajaId?: string;
  /** Código de la caja Asociado */
  cajaCodigo?: string;
  /** Sucursal asociado a la caja */
  sucursal?: Sucursal;
  /** Punto de venta asociado a la caja */
  puntoVenta?: PuntoVenta;
  /** Usuarios responsables del arqueo de caja */
  usuario?: string[];
  /** Dominio de usuarios de caja que tienen permitido ingresar al arqueo */
  usuariosCaja?: string[];
  /** Usuario que realiza la apertura de la caja */
  usuarioApertura?: string;
  /** Usuario que realiza el cierre de la caja */
  usuarioCierre?: string;
  /** Módulo al que pertenece el arqueo de caja - Valores admitidos: REST, POS */
  modulo?: string;
  /** Usuario encargado de la supervision de caja - Un elemento de supervisor pertenece al dominio de responsables. */
  supervisor?: string[];
  /** Responsables de aprobación o acción realizadas en apertura caja */
  responsables?: string[];
  /** Monto inicial de apertura de caja */
  montoInicial?: number;
  /** Número total de ventas */
  nroVentas?: number;
  /** Monto Total de ventas en efectivo */
  totalVentas?: number;
  /** Monto Total de ventas solo en efectivo */
  totalVentasEfectivo?: number;
  /** Total de retiros en efectivo */
  totalRetiros?: number;
  /** Monto Total de ingreso a caja */
  totalIngresos?: number;
  /** (Inicial + VentasEfectivo - Retiros) - Calculo automático */
  montoTeorico?: number;
  /** Monto que registra el operador según el arqueo */
  montoReal?: number;
  /** diferencia entre el monto teorico y el monto real */
  diferencia?: number;
  /** Detalle de totales según el método de pago */
  metodoPagoVenta?: ArqueoCajaMetodoPago[];
  /** Detalle de retiros realizados de la caja */
  retiros?: ArqueoCajaRetiro[];
  /** Detalle de ingresos realizados de la caja */
  ingresos?: ArqueoCajaIngreso[];
  /** Detalle de ventas realizadas por cortesia */
  cortesia?: ArqueoCajaCortesia;
  /** Observaciones en el periodo de operacion */
  observaciones?: ArqueoCajaObservacion[];
  /** Fecha y hora de apertura de Caja */
  fechaApertura?: DateDMYHHMMSS;
  /** Fecha y hora de cierre de Caja */
  fechaCierre?: DateDMYHHMMSS;
  /** Turno de operación */
  turnoCaja?: TurnoCaja;
  /** Representación grafica del reporte de ventas */
  representacionGrafica?: ArqueoCajaRepresentacionGrafica;
  /** Moneda principal de sistema - Tipo de cambio siempre será 1 */
  moneda?: MonedaParams;
  /** Estado del registro * ELABORADO = Estado de operaciones de caja. * ARQUEO = Estado de Cuente de dinero de la caja. * FINALIZADO = Cuando ya se cierra la caja. */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Url de representación gráfica para los arqueos de caja
 */
export interface ArqueoCajaRepresentacionGrafica {
  /** PDF Formato Medio Oficio */
  pdf?: UrlInvConsultaDocumento;
  /** PDF Formato Rollo */
  rollo?: UrlInvConsultaDocumento;
}

/**
 * Datos del esquema de turnos para las aperturas y cierres de caja
 */
export interface TurnoCaja {
  /** Identificador interno del registro */
  _id?: string;
  /** Nombre único del turno Ejemplo: Mañana, Tarde, Noche, etc. */
  nombre?: string;
  /** Hora de inicio del turno - Admite valores entre 0 - 24 */
  horaInicio?: number;
  /** Hora de fin del turno - Admite valores entre 0 - 24 */
  horaCierre?: number;
  /** Bloquea las ventas en el turno - true: Bloquea o fuerza que se finalicen las ventas para ingreso a arqueo. - false o null: No bloquea las ventas, es posible realizar arqueos aun si no se tienen las ventas finalizadas. */
  bloquearVentas?: boolean;
  /** Estado del registro * ELABORADO = Estado general */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}
