// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const NOTACREDITODEBITOFRAGMENT = gql`
  fragment NotaCreditoDebitoFragment on NotaCreditoDebito {
    nitEmisor
    razonSocialEmisor
    numeroNotaCreditoDebito
    numeroFactura
    cuf
    cufd {
      codigo
        codigoControl
        direccion
        fechaVigencia
        fechaInicial
    }
    cuis {
      codigo
        fechaVigencia
    }
    tipoFactura {
      codigoClasificador
        descripcion
    }
    tipoEmision {
      codigoClasificador
        descripcion
    }
    sucursal {
      codigo
        direccion
        telefono
        departamento {
          codigo
              codigoPais
              sigla
              departamento
        }
        municipio
        integracionSiat
    }
    puntoVenta {
      codigo
        tipoPuntoVenta {
          codigoClasificador
              descripcion
        }
        nombre
        descripcion
    }
    fechaEmision
    cliente {
      _id
        razonSocial
        codigoCliente
        tipoDocumentoIdentidad {
          codigoClasificador
              descripcion
        }
        numeroDocumento
        complemento
        nombres
        apellidos
        email
        codigoExcepcion
        telefono
        lineaCredito
        creditoMinimo
        creditoMaximo
        direccion
        direccionLaboral
        entidadLaboral
        maximoPlazo
        state
        usucre
        createdAt
        usumod
        UpdatedAt
    }
    numeroAutorizacionCuf
    fechaEmisionFactura
    montoTotalOriginal
    montoTotalDevuelto
    montoTotalLiteral
    montoDescuentoCreditoDebito
    montoEfectivoCreditoDebito
    leyenda
    subLeyenda
    usuario
    documentoSectorFactura {
      codigoClasificador
        descripcion
    }
    documentoSector {
      # Datos simples (Tipo ya expandido previamente)
      codigoClasificador
      descripcion
    }
    detalle {
      nroItem
        nroItemFactura
        actividadEconomica {
          codigoCaeb
              descripcion
              tipoActividad
        }
        productoServicio {
          codigoActividad
              codigoProducto
              descripcionProducto
        }
        producto
        descripcion
        cantidad
        unidadMedida {
          codigoClasificador
              descripcion
        }
        precioUnitario
        montoDescuento
        subTotal
        codigoDetalleTransaccion
    }
    codigoRecepcion
    motivoAnulacion {
      codigoClasificador
        descripcion
    }
    representacionGrafica {
      pdf
        xml
        rollo
        rolloResumen
        rolloReducido
        sin
    }
    reversion
    usucre
    createdAt
    updatedAt
    state
  }
`;