// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

/**
 * Date in DD/MM/YYYY HH:MM:SS format
 */
export type DateDMYHHMMSS = string
/**
 * Fecha en formato DD/MM/YYYY HH:MM (Dia/Mes/Anio Hora:Minuto)
 */
export type DateDMYHHMM = string
/**
 * Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes
 */
export interface SinTipoPuntoVenta {
  /** Código de Tipo de Punto de Venta */
  codigoClasificador: string
  /** Descripción del Tipo de Punto de Venta */
  descripcion: string
}

/**
 * Las unidades de medida nos permiten cuantificar claramente las existencias de nuestro inventario, estas nos permiten  la correcta interpretación de las cantidades
 */
export interface SinUnidadMedida {
  /** Código de Unidad de Medida */
  codigoClasificador?: number
  /** Descripción de Unidad de Medida */
  descripcion?: string
}

/**
 * Estructura de url de consulta de imagenes que se encuentran en cloud
 */
export interface ImagenCloudVariant {
  /** Path Imagen pequeña, se usa para mostrar en los listados */
  thumbnail?: string
  /** Path Imagen mediana */
  medium?: string
  /** Path Imagen cuadrada adaptativa */
  square?: string
  /** Path Imagen original */
  public?: string
}

/**
 * Estructura de url de consulta de imagenes que se encuentran en cloud
 */
export interface ImagenCloud {
  /** Identificador unico de la imagen - para realizar el proceso de eliminación se usa este campo */
  id?: string
  /** Nombre del archivo que se usa */
  filename?: string
  /** Variantes de la imagen */
  variants?: ImagenCloudVariant
}

/**
 * Entrada de datos paramétricos de la entidad como codigos de sucursal o codigos de puntos de venta - El código de sucursal y punto de venta enviado esta restringido a su la restriccion de sucursal y punto de venta - Para verificar las restricciones consulte el servicio usuarioRestriccion
 */
export interface EntidadParamsInput {
  codigoSucursal?: number
  codigoPuntoVenta?: number
}

/**
 * Datos del punto de venta minificados
 */
export interface PuntoVenta {
  /** Código único del punto de venta */
  codigo?: number
  /** - Comisionistas de acuerdo a normativa vigente; - Ventanilla de Cobranza autorizada por la ASFI según normativa; - Puntos de Ventas Móviles para venta de bienes o prestación de servicios; - Puntos de Venta YPFB para la venta de combustible a precio internacional; - Puntos de Venta (Cajeros o similares) para la venta de otros bienes y/o prestación de servicios. - Puntos de Venta conjunta, habilitada para emisión conjunta de documentos fiscales. */
  tipoPuntoVenta?: SinTipoPuntoVenta
  /** Nombre, Alias del punto de venta */
  nombre?: string
  /** Descripción del punto de venta */
  descripcion?: string
}

/**
 * Las sucursales son establecimientos secundarios donde se realiza alguna de las actividades económicas del Contribuyente, tienen una dirección física y están registradas en el Padrón Nacional de Contribuyentes. En el Sistema de Facturación, la emisión de las facturas se realiza por sucursal o casa matriz (sucursal 0).
 */
export interface Sucursal {
  /** Codigo único de la sucursal */
  codigo?: number
  /** Direccion de la sucursal */
  direccion?: string
  /** Teléfono de referencia */
  telefono?: string
  /** Datos del departamento */
  departamento?: Departamento
  /** Municipio donde se encuentra la sucursal */
  municipio?: string
  /** Si cuenta con integracion SIAT */
  integracionSiat?: boolean
}

/**
 * Estructura de datos para Departamento
 */
export interface Departamento {
  /** Código segun INE */
  codigo?: number
  /** Código de Pais segun ISO 3166-1 */
  codigoPais?: number
  /** Sigla del departamento */
  sigla?: string
  /** Nombre del departamento */
  departamento?: string
}

/**
 * Datos de la sucursal asociado a cada factura
 */
export interface OrgFacturaSucursal {
  /** Codigo de la sucursal */
  codigo?: number
  /** Direccion regitrada en cada sucursal */
  direccion?: string
  /** Telefono de referencia de la sucursal */
  telefono?: string
  /** Nombre de departamento de la sucursal */
  departamento?: Departamento
  /** Nombre de municipio de la sucursal */
  municipio?: string
  /** Define si existe integración con SISTEMA DE ADMINISTRACIÓN TRIBUTARIA */
  integracionSiat?: boolean
}

/**
 * Listado de monedas de uso para la empresa
 */
export interface Moneda {
  /** Identificador único interno del registro */
  _id?: string
  /** Codigo de moneda */
  codigo?: number
  /** Descripcion de la nueva moneda a adicionar */
  descripcion?: string
  /** Sigla de la moneda BS, USD, etc */
  sigla?: string
  /** Tipo de cambio de la moneda para la venta, BS: 1 */
  tipoCambio?: number
  /** Tipo de cambio de la moneda para la compra, BS: 1 */
  tipoCambioCompra?: number
  /** 1 = activo 0 = inactivo */
  activo?: number
  /** Estado del registro */
  state?: string
  /** Usuario que creo el registro */
  usucre?: string
  /** Ultimo usuario que modificó el registro */
  usumod?: string
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS
  /** Ultima fecha de actualizacion del registro */
  updatedAt?: DateDMYHHMMSS
}

/**
 * Conjugación de moneda y precio
 */
export interface MonedaPrecio {
  /** Clasificador sin tipo Moneda */
  moneda?: Moneda
  /** Precio base inicial - Se usa como base para calcular las variaciones de precio en función al factor de ajuste */
  precioBase?: number
  /** Precio calculado del articulo */
  precio?: number
  /** Precio de entrega para delivery */
  delivery?: number
  /** Precio de comparacion según el argumento precio */
  precioComparacion?: number
  /** Si es true, cambia el precio segun el factor de ajuste - Si es false, el precio no cambia */
  manual?: boolean
}

/**
 * Datos de entrada para la asociación de articulo precio con las impresoras
 */
export interface ArticuloPrecioImpresoraInput {
  impresoraId?: string[]
}

export interface ArticuloPrecioGeneral {
  /** Identificador interno de articulo Precio */
  _id?: string
  /** referencia al id interno del articulo */
  articuloId?: string
  /** Código del articulo relacionado */
  codigoArticulo?: string
  /** Nombre del articulo */
  nombreArticulo?: string
  /** Identicador interno de grupo unidad de medida - null, no pertenece a un ningún grupo de unidades de medida - Si pertenece a un grupo de unidades de medida */
  grupoId?: string
  /** Sucursal a la que pertenece el precio */
  sucursal?: OrgFacturaSucursal
  /** Imagen referencial a la sucursal */
  imagen?: ImagenCloud
  /** Precio Báse del articulo */
  precioBase?: ArticuloPrecio
  /** Arrays de equivalencias entre precios, unidades de medida y monedas */
  precioGrupo?: ArticuloPrecio[]
  /** Asociacion de impresoras al articulo, por sucursal */
  impresoras?: Impresora[]
  /** Activo para la sucursal */
  activo?: boolean
  /** Si el articulo contiene verificar stock */
  verificarStock?: boolean
  /** Estado del registro */
  state?: string
  /** Usuario de creación */
  usucre?: string
  /** Fecha de creación */
  createdAt?: DateDMYHHMMSS
  /** Ultimo usuario de modificación */
  usumod?: string
  /** Ultima fecha de actualización */
  updatedAt?: DateDMYHHMMSS
}

export interface ArticuloDescuento {
  fechaInicial?: DateDMYHHMM
  fechaFinal?: DateDMYHHMM
  porcentaje?: number
  cantidad?: ArticuloDescuentoCantidad[]
}

export interface ArticuloDescuentoCantidad {
  nro?: number
  porcentaje?: number
}

/**
 * Datos de entrada para el registro / actualización de articulo unidad de medida
 */
export interface ArticuloPrecio {
  /** Código interno de articulo Precio */
  _id?: string
  /** Datos de la unidad de medida */
  articuloUnidadMedida?: ArticuloUnidadMedida
  /** Datos de la moneda principal */
  monedaPrimaria?: MonedaPrecio
  /** Datos de la moneda adicional 1 */
  monedaAdicional1?: MonedaPrecio
  /** Datos de la moneda adicional 2 */
  monedaAdicional2?: MonedaPrecio
  /** Datos de la moneda adicional 3 */
  monedaAdicional3?: MonedaPrecio
  /** Cantidad Base segun la Unidad de Medida Base */
  cantidadBase?: number
  /** Descuento Asociado al Articulo */
  descuento?: ArticuloDescuento
  /** Path de la imagen asociada al documento sector En caso no exista, se asume la imagen del pariente superior */
  imagen?: ImagenCloud
  /** Factor de ajuste que modifica el precio de venta */
  factorAjuste?: number
  /** Es un articulo de venta? */
  umVenta?: boolean
  /** Es articulo de inventario? */
  umInventario?: boolean
  /** articulo de compra? */
  umCompra?: boolean
}

/**
 * Datos del articulo Unidad de medida, tambien se contempla la homologación del mismo.
 */
export interface ArticuloUnidadMedida {
  /** Identificador único interno del registro */
  _id?: string
  /** Código que identifica a la unidad de medida */
  codigoUnidadMedida?: string
  /** Nombre de la unidad de medida */
  nombreUnidadMedida?: string
  /** Nombre de la unidad de medida */
  sinUnidadMedida?: SinUnidadMedida
  /** Longitud del articulo según la unidad de medida */
  longitud?: number
  /** Ancho del articulo según la unidad de medida */
  ancho?: number
  /** Altura del articulo según la unidad de medida */
  altura?: number
  /** Peso del articulo según la unidad de medida */
  peso?: number
  /** Volumen del articulo según la unidad de medida */
  volumen?: number
  /** Estado del registro */
  state?: string
  /** Usuario de creación del registro */
  usucre?: string
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS
  /** Usuario de modificación del registro */
  usumod?: string
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS
}

/**
 * Datos de entrada para el registro / actualización del registro
 */
export interface ImpresoraInput {
  nombre: string
  descripcion?: string
  atributo1?: string
  atributo2?: string
}

/**
 * Datos del tipo de articulo.
 */
export interface Impresora {
  /** Identificador único del registro */
  _id?: string
  /** Ubicación de la impresora */
  sucursal?: Sucursal
  /** Rastro de punto de venta */
  puntoVenta?: PuntoVenta
  /** Nombre de la impresora */
  nombre?: string
  /** Descripcion adicional de la impresora */
  descripcion?: string
  /** Atributo adicional 1 */
  atributo1?: string
  /** Atributo adicional 2 */
  atributo2?: string
  /** Estado del registro */
  state?: string
  /** Usuario de creación del registro */
  usucre?: string
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS
  /** Usuario de modificación del registro */
  usumod?: string
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS
}
