// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

/**
 * Date in DD/MM/YYYY format
 */
export type DateDMY = string
/**
 * Date in DD/MM/YYYY HH:MM:SS format
 */
export type DateDMYHHMMSS = string
/**
 * Fecha en formato DD/MM/YYYY HH:MM (Dia/Mes/Anio Hora:Minuto)
 */
export type DateDMYHHMM = string
/**
 * Url de consulta documentos, para la obtención de la representación impresa, uso de Buffer para la generacion de archivos
 */
export type UrlConsultaDocumento = string
/**
 * Información para ayudar en la paginación.
 */
export interface PageInfo {
  hasNextPage: boolean
  hasPrevPage: boolean
  totalDocs?: number
  limit?: number
  page?: number
  totalPages?: number
}

/**
 * Se usa para describir el motivo por el cual se anula un determinda documento Eje. Factura, Notas, etc
 */
export interface SinMotivoAnulacion {
  codigoClasificador: string
  descripcion: string
}

/**
 * La Homologación de productos y servicios permite al Contribuyente relacionar los códigos utilizados para sus productos y servicios con los códigos genéricos proporcionados por la Administración Tributaria
 */
export interface SinProductoServicio {
  codigoActividad: string
  codigoProducto: string
  descripcionProducto: string
}

/**
 * Tipos de documentos que se pueden emitir
 */
export interface SinTipoDocumentoIdentidad {
  codigoClasificador: string
  descripcion: string
}

/**
 * Están definidos para que cada Factura Digital pueda ser enviada por un Servicio Web, lo cual asegura la independencia del mismo en caso de modificaciones o ajustes.
 */
export interface SinTipoDocumentoSector {
  codigoClasificador?: string
  descripcion?: string
}

/**
 * Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes
 */
export interface SinTipoPuntoVenta {
  codigoClasificador: string
  descripcion: string
}

/**
 * Las unidades de medida nos permiten cuantificar claramente las existencias de nuestro inventario, estas nos permiten  la correcta interpretación de las cantidades
 */
export interface SinUnidadMedida {
  codigoClasificador?: number
  descripcion?: string
}

/**
 * Urls de consulta de documentos, impresiones boletos, etc
 */
export interface UrlsConsultaDocumento {
  pdf?: UrlConsultaDocumento
  xml?: UrlConsultaDocumento
  rollo?: UrlConsultaDocumento
  sin?: UrlConsultaDocumento
}

/**
 * Entrada de datos paramétricos de la entidad como codigos de sucursal o codigos de puntos de venta - El código de sucursal y punto de venta enviado esta restringido a su la restriccion de sucursal y punto de venta - Para verificar las restricciones consulte el servicio usuarioRestriccion
 */
export interface EntidadParamsInput {
  codigoSucursal?: number
  codigoPuntoVenta?: number
}

/**
 * Datos de entrada de un cliente registrado en base de datos
 */
export interface ClienteOperacionInput {
  codigoCliente: string
  razonSocial?: string
  email?: string
  telefono?: string
  direccion?: string
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface ClienteOperacion {
  razonSocial?: string
  codigoCliente?: string
  tipoDocumentoIdentidad?: SinTipoDocumentoIdentidad
  numeroDocumento?: string
  complemento?: string
  nombres?: string
  apellidos?: string
  email?: string
  telefono?: string
  lineaCredito?: boolean
  creditoMinimo?: number
  creditoMaximo?: number
  direccion?: string
  direccionLaboral?: string
  entidadLaboral?: string
  maximoPlazo?: number
}

/**
 * Datos del punto de venta minificados
 */
export interface PuntoVenta {
  codigo?: number
  tipoPuntoVenta?: SinTipoPuntoVenta
  nombre?: string
  descripcion?: string
}

/**
 * Datos del punto de venta, asociado a la factura.
 */
export interface OrgFacturaPuntoVenta {
  codigo?: number
  tipoPuntoVenta?: SinTipoPuntoVenta
  nombre?: string
  descripcion?: string
}

/**
 * Las sucursales son establecimientos secundarios donde se realiza alguna de las actividades económicas del Contribuyente, tienen una dirección física y están registradas en el Padrón Nacional de Contribuyentes. En el Sistema de Facturación, la emisión de las facturas se realiza por sucursal o casa matriz (sucursal 0).
 */
export interface Sucursal {
  codigo?: number
  direccion?: string
  telefono?: string
  departamento?: Departamento
  municipio?: string
  integracionSiat?: boolean
}

/**
 * Estructura de datos para Departamento
 */
export interface Departamento {
  codigo?: number
  codigoPais?: number
  sigla?: string
  departamento?: string
}

/**
 * Datos de la sucursal asociado a cada factura
 */
export interface OrgFacturaSucursal {
  codigo?: number
  direccion?: string
  telefono?: string
  departamento?: Departamento
  municipio?: string
  integracionSiat?: boolean
}

/**
 * Listado de monedas de uso para la empresa
 */
export interface Moneda {
  _id?: string
  codigo?: number
  descripcion?: string
  sigla?: string
  tipoCambio?: number
  tipoCambioCompra?: number
  activo?: number
  state?: string
  usucre?: string
  usumod?: string
  createdAt?: DateDMYHHMMSS
  updatedAt?: DateDMYHHMMSS
}

/**
 * Conjugacion de moneda precio para articulo precio operacion
 */
export interface MonedaPrecioOperacion {
  moneda?: Moneda
  precioBase?: number
  precio?: number
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface MetodoPago {
  codigoClasificador?: number
  descripcion?: string
}

/**
 * Periodo de inventario.
 */
export interface KardexPeriodo {
  codigo?: number
  descripcion?: string
  documentoSector?: SinTipoDocumentoSector
  state?: string
  usucre?: string
  createdAt?: DateDMYHHMMSS
  usumod?: string
  updatedAt?: DateDMYHHMMSS
}

/**
 * Datos del tipo de articulo.
 */
export interface Lote {
  _id?: string
  codigoLote?: string
  descripcion?: string
  codigoArticulo?: string
  sucursal?: OrgFacturaSucursal
  atributo1?: string
  atributo2?: string
  atributo3?: string
  fechaAdmision?: DateDMYHHMMSS
  fechaFabricacion?: DateDMY
  fechaVencimiento?: DateDMY
  state?: string
  usucre?: string
  createdAt?: DateDMYHHMMSS
  usumod?: string
  updatedAt?: DateDMYHHMMSS
}

/**
 * Datos del tipo de articulo.
 */
export interface Almacen {
  _id?: string
  codigoAlmacen?: string
  nombre?: string
  ubicacion?: string
  sucursal?: OrgFacturaSucursal
  tipo?: string
  activo?: boolean
  prioridad?: number
  state?: string
  usucre?: string
  createdAt?: DateDMYHHMMSS
  usumod?: string
  updatedAt?: DateDMYHHMMSS
}

/**
 * Cálculos operaciones para el item.
 */
export interface TotalesPrecioCostoOperacion {
  subtotalBruto?: number
  totalDescuento?: number
  subtotalNeto?: number
  totalImpuestos?: number
  totalGasto?: number
  totalFinal?: number
}

/**
 * - Distribución de precios para almacen - De aquí se obtiene información del Margen de Utilidad Real = PrecioFinalEmpresa - CostoFinal
 */
export interface PrecioCostoOperacion {
  tipoOperacion?: string
  valorBase?: number
  valorBaseAnterior?: number
  descuento?: number
  descuentoAdicional?: number
  valorNeto?: number
  impuestoUnitario?: number
  gastoAdicional?: number
  variacion?: number
  valorFinal?: number
  totales?: TotalesPrecioCostoOperacion
}

/**
 * Datos del articulo precio y operacion
 */
export interface ArticuloPrecioOperacion {
  articuloUnidadMedida?: ArticuloUnidadMedida
  monedaPrecio?: MonedaPrecioOperacion
  moneda?: Moneda
  tipoCambio?: number
  estructuraValor?: PrecioCostoOperacion
  tipoOperacion?: string
  valor?: number
  cantidadBase?: number
  cantidad?: number
  cantidadFactor?: number
  descuento?: number
  descuentoAdicional?: number
  otrosCostos?: number
  impuesto?: number
  incluyeImpuesto?: boolean
  esDescuentoTotal?: boolean
  factorAjuste?: number
}

/**
 * Datos de entrada de la unidad de medida montos monedas y precios
 */
export interface ArticuloPrecioOperacionInput {
  codigoArticuloUnidadMedida: string
  cantidad: number
  precio: number
  descuento: number
  esDescuentoTotal?: boolean
  impuesto: number
}

/**
 * Datos del articulo Unidad de medida, tambien se contempla la homologación del mismo.
 */
export interface ArticuloUnidadMedida {
  _id?: string
  codigoUnidadMedida?: string
  nombreUnidadMedida?: string
  sinUnidadMedida?: SinUnidadMedida
  longitud?: number
  ancho?: number
  altura?: number
  peso?: number
  volumen?: number
  state?: string
  usucre?: string
  createdAt?: DateDMYHHMMSS
  usumod?: string
  updatedAt?: DateDMYHHMMSS
}

/**
 * Datos del tipo de articulo.
 */
export interface TipoArticuloOperacion {
  codigo?: string
  descripcion?: string
}

/**
 * Grupo de articulo Ejemplo impresora, cables, computadoras, etc
 */
export interface GrupoArticulo {
  codigoGrupoArticulo?: string
  nombreGrupoArticulo?: string
}

export interface ArticuloOperacionComplemento {
  articuloId?: string
  nroItem?: number
  tipoArticulo?: TipoArticuloOperacion
  claseArticulo?: string
  grupoArticulo?: GrupoArticulo
  codigoArticulo?: string
  nombreArticulo?: string
  almacen?: Almacen
  lote?: Lote
  codigoGrupo?: string
  sinProductoServicio?: SinProductoServicio
  articuloPrecioBase?: ArticuloPrecioOperacion
  articuloPrecio?: ArticuloPrecioOperacion
  detalleExtra?: string
  nota?: string
  verificarStock?: boolean
}

/**
 * Datos de articulo minimizado para operaciones entre todas la tablas
 */
export interface ArticuloOperacion {
  articuloId?: string
  nroItem?: number
  tipoArticulo?: TipoArticuloOperacion
  claseArticulo?: string
  gestionArticulo?: string
  grupoArticulo?: GrupoArticulo
  codigoArticulo?: string
  nombreArticulo?: string
  almacen?: Almacen
  lote?: Lote
  codigoGrupo?: string
  sinProductoServicio?: SinProductoServicio
  articuloPrecioBase?: ArticuloPrecioOperacion
  articuloPrecio?: ArticuloPrecioOperacion
  detalleExtra?: string
  nota?: string
  notaRapida?: NotaRapida[]
  verificarStock?: boolean
  complementos?: ArticuloOperacionComplemento[]
  impresoras?: Impresora[]
  cortesia?: boolean
  state?: string
}

/**
 * Historial de transacciones para articulo precio
 */
export interface HistorialArticuloOperacion {
  nro?: number
  articuloOperacion?: ArticuloOperacion[]
}

/**
 * Nota rapida asociada al articulo
 */
export interface NotaRapida {
  cantidad?: number
  valor?: string
  atributo1?: string
  atributo2?: string
}

/**
 * Datos de entrada para asociar el articulo a las tablas relacionales
 */
export interface ArticuloOperacionInput {
  nroItem?: number
  codigoArticulo: string
  codigoAlmacen: string
  codigoLote?: string
  articuloPrecio: ArticuloPrecioOperacionInput
  complementos?: ArticuloOperacionComplementoInput[]
  detalleExtra?: string
  nota?: string
  notaRapida?: NotaRapidaInput[]
  cortesia?: boolean
}

/**
 * Nota rapida asociadas al articulo
 */
export interface NotaRapidaInput {
  cantidad?: number
  valor?: string
  atributo1?: string
  atributo2?: string
}

export interface ArticuloOperacionComplementoInput {
  codigoArticulo: string
  codigoAlmacen: string
  codigoLote?: string
  articuloPrecio: ArticuloPrecioOperacionInput
  detalleExtra?: string
  nota?: string
}

/**
 * Metodo de pago segun la operacion
 */
export interface MetodoPagoVenta {
  metodoPago?: MetodoPago
  monto?: number
}

/**
 * Datos del tipo de articulo.
 */
export interface Impresora {
  _id?: string
  sucursal?: Sucursal
  puntoVenta?: PuntoVenta
  nombre?: string
  descripcion?: string
  atributo1?: string
  atributo2?: string
  state?: string
  usucre?: string
  createdAt?: DateDMYHHMMSS
  usumod?: string
  updatedAt?: DateDMYHHMMSS
}

/**
 * Una conexión a una lista de elementos.
 */
export interface RestPedidoConnection {
  pageInfo: PageInfo
  docs?: RestPedido[]
}

/**
 * Datos de entrada para registro de una mesa
 */
export interface RestMesaInput {
  nombre?: string
  nroComensales?: number
  ubicacion?: string
}

/**
 * Datos e identificacion de la mesa para los comenzales
 */
export interface RestMesa {
  nombre?: string
  nroComensales?: number
  ubicacion?: string
}

export interface RestPedidoExpressInput {
  mesa: RestMesaInput
  productos: ArticuloOperacionInput[]
  codigoMoneda: number
  tipoCambio: number
  tipo?: string
  nota?: string
  notaRapida?: NotaRapidaInput[]
  terminos?: string
  fechaEntrega?: DateDMYHHMM
  direccionEntrega?: string
  espacioId?: string
  atributo1?: string
  atributo2?: string
  atributo3?: string
  atributo4?: string
}

/**
 * Datos del pedido
 */
export interface RestPedido {
  _id?: string
  numeroPedido?: number
  numeroOrden?: number
  marcaKardex?: string
  sucursal?: OrgFacturaSucursal
  puntoVenta?: OrgFacturaPuntoVenta
  kardexPeriodo?: KardexPeriodo
  mesa?: RestMesa
  productos?: ArticuloOperacion[]
  productosEliminados?: ArticuloOperacion[]
  ultimaTransaccionProductos?: ArticuloOperacion[]
  moneda?: Moneda
  tipoCambio?: number
  tipo?: string
  descuentoAdicional?: number
  otrosCostos?: number
  descripcionOtrosCostos?: string
  fechaDocumento?: DateDMYHHMM
  fechaContable?: DateDMYHHMM
  cliente?: ClienteOperacion
  metodoPago?: MetodoPago
  numeroTarjeta?: string
  metodoPagoVenta?: MetodoPagoVenta[]
  montoTotal?: number
  montoTotalBase?: number
  fechaEntrega?: DateDMYHHMM
  direccionEntrega?: string
  detalleExtra?: string
  tipoDocumento?: string
  refNroDocumento?: string
  refDocumento?: string
  nota?: string
  notaRapida?: NotaRapida[]
  terminos?: string
  representacionGrafica?: UrlsConsultaDocumento
  motivoAnulacion?: SinMotivoAnulacion
  descripcionAnulacion?: string
  espacio?: string
  atributo1?: string
  atributo2?: string
  atributo3?: string
  atributo4?: string
  state?: string
  usucre?: string
  createdAt?: DateDMYHHMMSS
  usumod?: string
  updatedAt?: DateDMYHHMMSS
  historial?: HistorialArticuloOperacion[]
  arqueoCajaId?: string
}
