// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { ARTICULOFRAGMENT } from '../fragments/ArticuloFragments';
import { Articulo, EntidadParamsInput } from '../types';

export interface ArticuloInventarioListadoVariables {
  cds: number;
  entidad: EntidadParamsInput;
  verificarPrecio?: boolean;
  verificarInventario?: boolean;
  query?: string;
  queryExtra?: string;
}

export const ARTICULOINVENTARIOLISTADO = gql`
  query ArticuloInventarioListado($cds: Int!, $entidad: EntidadParamsInput!, $verificarPrecio: Boolean, $verificarInventario: Boolean, $query: String, $queryExtra: String) {
    articuloInventarioListado(cds: $cds, entidad: $entidad, verificarPrecio: $verificarPrecio, verificarInventario: $verificarInventario, query: $query, queryExtra: $queryExtra) { ...ArticuloFragment }
  }
  ${ARTICULOFRAGMENT}
`;

export const useArticuloInventarioListado = (variables: ArticuloInventarioListadoVariables, options?: Omit<UseQueryOptions<Articulo[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<Articulo[], Error>({
    queryKey: ['articuloInventarioListado', variables],
    queryFn: async () => {
      const response = await client.request<{ articuloInventarioListado: Articulo[] }>(ARTICULOINVENTARIOLISTADO, variables);
      return response.articuloInventarioListado;
    },
    ...options,
  });
};