// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { ARTICULOCONNECTIONFRAGMENT } from '../fragments/ArticuloConnectionFragments'
import { ArticuloConnection, EntidadParamsInput } from '../types'

export interface ArticuloInventarioV2ListadoVariables {
  cds: number
  entidad: EntidadParamsInput
  verificarPrecio?: boolean
  verificarInventario?: boolean
  limit: number
  page?: number
  reverse?: boolean
  query?: string
  queryExtra?: string
}

export const ARTICULOINVENTARIOV2LISTADO = gql`
  query ArticuloInventarioV2Listado(
    $cds: Int!
    $entidad: EntidadParamsInput!
    $verificarPrecio: Boolean
    $verificarInventario: Boolean
    $limit: Int!
    $page: Int
    $reverse: Boolean
    $query: String
    $queryExtra: String
  ) {
    articuloInventarioV2Listado(
      cds: $cds
      entidad: $entidad
      verificarPrecio: $verificarPrecio
      verificarInventario: $verificarInventario
      limit: $limit
      page: $page
      reverse: $reverse
      query: $query
      queryExtra: $queryExtra
    ) {
      ...ArticuloConnectionFragment
    }
  }
  ${ARTICULOCONNECTIONFRAGMENT}
`

export const useArticuloInventarioV2Listado = (
  variables: ArticuloInventarioV2ListadoVariables,
  options?: Omit<UseQueryOptions<ArticuloConnection, Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<ArticuloConnection, Error>({
    queryKey: ['articuloInventarioV2Listado', variables],
    queryFn: async () => {
      const response = await client.request<{ articuloInventarioV2Listado: ArticuloConnection }>(
        ARTICULOINVENTARIOV2LISTADO,
        variables,
      )
      return response.articuloInventarioV2Listado
    },
    ...options,
  })
}
