// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { ARTICULOFRAGMENT } from '../fragments/ArticuloFragments'
import { Articulo, EntidadParamsInput } from '../types'

export interface ArticuloInventarioComplementoListadoVariables {
  cds: number
  entidad: EntidadParamsInput
  query?: string
  ids?: string[]
}

export const ARTICULOINVENTARIOCOMPLEMENTOLISTADO = gql`
  query ArticuloInventarioComplementoListado(
    $cds: Int!
    $entidad: EntidadParamsInput!
    $query: String
    $ids: [String]
  ) {
    articuloInventarioComplementoListado(cds: $cds, entidad: $entidad, query: $query, ids: $ids) {
      ...ArticuloFragment
    }
  }
  ${ARTICULOFRAGMENT}
`

export const useArticuloInventarioComplementoListado = (
  variables: ArticuloInventarioComplementoListadoVariables,
  options?: Omit<UseQueryOptions<Articulo[], Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<Articulo[], Error>({
    queryKey: ['articuloInventarioComplementoListado', variables],
    queryFn: async () => {
      const response = await client.request<{ articuloInventarioComplementoListado: Articulo[] }>(
        ARTICULOINVENTARIOCOMPLEMENTOLISTADO,
        variables,
      )
      return response.articuloInventarioComplementoListado
    },
    ...options,
  })
}
