// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { ARTICULOCOMPOSICIONVENTAFRAGMENT } from '../fragments/ArticuloComposicionVentaFragments'
import { ArticuloComposicionVenta } from '../types'

export interface ArticuloComposicionVentaVariables {
  codigoSucursal: number
  articuloId: string
  esReceta: boolean
  tieneModificadores: boolean
}

export const ARTICULOCOMPOSICIONVENTA = gql`
  query ArticuloComposicionVenta(
    $codigoSucursal: Int!
    $articuloId: ID!
    $esReceta: Boolean!
    $tieneModificadores: Boolean!
  ) {
    articuloComposicionVenta(
      codigoSucursal: $codigoSucursal
      articuloId: $articuloId
      esReceta: $esReceta
      tieneModificadores: $tieneModificadores
    ) {
      ...ArticuloComposicionVentaFragment
    }
  }
  ${ARTICULOCOMPOSICIONVENTAFRAGMENT}
`

export const useArticuloComposicionVenta = (
  variables: ArticuloComposicionVentaVariables,
  options?: Omit<UseQueryOptions<ArticuloComposicionVenta, Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<ArticuloComposicionVenta, Error>({
    queryKey: ['articuloComposicionVenta', variables],
    queryFn: async () => {
      const response = await client.request<{ articuloComposicionVenta: ArticuloComposicionVenta }>(
        ARTICULOCOMPOSICIONVENTA,
        variables,
      )
      return response.articuloComposicionVenta
    },
    ...options,
  })
}
