// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'
import { client, gql } from '../client'
import { METODOPAGOFRAGMENT } from '../fragments/MetodoPagoFragments'
import { MetodoPago } from '../types'

export interface MetodosPagoVariables {}

export const METODOSPAGO = gql`
  query MetodosPago {
    metodosPago {
      ...MetodoPagoFragment
    }
  }
  ${METODOPAGOFRAGMENT}
`

export const useMetodosPago = (
  variables: MetodosPagoVariables,
  options?: Omit<UseQueryOptions<MetodoPago[], Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<MetodoPago[], Error>({
    queryKey: ['metodosPago', variables],
    queryFn: async () => {
      const response = await client.request<{ metodosPago: MetodoPago[] }>(METODOSPAGO, variables)
      return response.metodosPago
    },
    ...options,
  })
}
