// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { RESTPEDIDOCONNECTIONFRAGMENT } from '../fragments/RestPedidoConnectionFragments'
import { EntidadParamsInput, RestPedidoConnection } from '../types'

export interface RestPedidoListadoVariables {
  entidad: EntidadParamsInput
  limit: number
  page?: number
  reverse?: boolean
  query?: string
}

export const RESTPEDIDOLISTADO = gql`
  query RestPedidoListado(
    $entidad: EntidadParamsInput!
    $limit: Int!
    $page: Int
    $reverse: Boolean
    $query: String
  ) {
    restPedidoListado(entidad: $entidad, limit: $limit, page: $page, reverse: $reverse, query: $query) {
      ...RestPedidoConnectionFragment
    }
  }
  ${RESTPEDIDOCONNECTIONFRAGMENT}
`

export const useRestPedidoListado = (
  variables: RestPedidoListadoVariables,
  options?: Omit<UseQueryOptions<RestPedidoConnection, Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<RestPedidoConnection, Error>({
    queryKey: ['restPedidoListado', variables],
    queryFn: async () => {
      const response = await client.request<{ restPedidoListado: RestPedidoConnection }>(
        RESTPEDIDOLISTADO,
        variables,
      )
      return response.restPedidoListado
    },
    ...options,
  })
}
