// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { RESTFACTURACONNECTIONFRAGMENT } from '../fragments/RestFacturaConnectionFragments'
import { EntidadParamsInput, RestFacturaConnection } from '../types'

export interface RestFacturaListadoVariables {
  entidad: EntidadParamsInput
  limit: number
  page?: number
  reverse?: boolean
  query?: string
}

export const RESTFACTURALISTADO = gql`
  query RestFacturaListado(
    $entidad: EntidadParamsInput!
    $limit: Int!
    $page: Int
    $reverse: Boolean
    $query: String
  ) {
    restFacturaListado(entidad: $entidad, limit: $limit, page: $page, reverse: $reverse, query: $query) {
      ...RestFacturaConnectionFragment
    }
  }
  ${RESTFACTURACONNECTIONFRAGMENT}
`

export const useRestFacturaListado = (
  variables: RestFacturaListadoVariables,
  options?: Omit<UseQueryOptions<RestFacturaConnection, Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<RestFacturaConnection, Error>({
    queryKey: ['restFacturaListado', variables],
    queryFn: async () => {
      const response = await client.request<{ restFacturaListado: RestFacturaConnection }>(
        RESTFACTURALISTADO,
        variables,
      )
      return response.restFacturaListado
    },
    ...options,
  })
}
