// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { RESTPEDIDOMESASOCUPADASFRAGMENT } from '../fragments/restPedidoMesasOcupadasFragments'
import { restPedidoMesasOcupadas } from '../types'

export interface RestPedidoMesasOcupadasVariables {
  codigoSucursal: number
  espacioId?: string
}

export const RESTPEDIDOMESASOCUPADAS = gql`
  query RestPedidoMesasOcupadas($codigoSucursal: Int!, $espacioId: ID) {
    restPedidoMesasOcupadas(codigoSucursal: $codigoSucursal, espacioId: $espacioId) {
      ...restPedidoMesasOcupadasFragment
    }
  }
  ${RESTPEDIDOMESASOCUPADASFRAGMENT}
`

export const useRestPedidoMesasOcupadas = (
  variables: RestPedidoMesasOcupadasVariables,
  options?: Omit<UseQueryOptions<restPedidoMesasOcupadas[], Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<restPedidoMesasOcupadas[], Error>({
    queryKey: ['restPedidoMesasOcupadas', variables],
    queryFn: async () => {
      const response = await client.request<{ restPedidoMesasOcupadas: restPedidoMesasOcupadas[] }>(
        RESTPEDIDOMESASOCUPADAS,
        variables,
      )
      return response.restPedidoMesasOcupadas
    },
    ...options,
  })
}
