// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTPEDIDOAUDITORIAFRAGMENT } from '../fragments/RestPedidoAuditoriaFragments';
import { RestPedidoAuditoria } from '../types';

export interface RestPedidoAuditoriaPorPedidoIdVariables {
  pedidoId: string;
}

export const RESTPEDIDOAUDITORIAPORPEDIDOID = gql`
  query RestPedidoAuditoriaPorPedidoId($pedidoId: ID!) {
    restPedidoAuditoriaPorPedidoId(pedidoId: $pedidoId) { ...RestPedidoAuditoriaFragment }
  }
  ${RESTPEDIDOAUDITORIAFRAGMENT}
`;

export const useRestPedidoAuditoriaPorPedidoId = (variables: RestPedidoAuditoriaPorPedidoIdVariables, options?: Omit<UseQueryOptions<RestPedidoAuditoria[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestPedidoAuditoria[], Error>({
    queryKey: ['restPedidoAuditoriaPorPedidoId', variables],
    queryFn: async () => {
      const response = await client.request<{ restPedidoAuditoriaPorPedidoId: RestPedidoAuditoria[] }>(RESTPEDIDOAUDITORIAPORPEDIDOID, variables);
      return response.restPedidoAuditoriaPorPedidoId;
    },
    ...options,
  });
};