// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';

import { client, gql } from '../client';
import { RESTESPACIOFRAGMENT } from '../fragments/RestEspacioFragments';
import { RestEspacio } from '../types';

export interface RestEspacioPorSucursalVariables {
  codigoSucursal: number;
}

export const RESTESPACIOPORSUCURSAL = gql`
  query RestEspacioPorSucursal($codigoSucursal: Int!) {
    restEspacioPorSucursal(codigoSucursal: $codigoSucursal) { ...RestEspacioFragment }
  }
  ${RESTESPACIOFRAGMENT}
`;

export const useRestEspacioPorSucursal = (variables: RestEspacioPorSucursalVariables, options?: Omit<UseQueryOptions<RestEspacio[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestEspacio[], Error>({
    queryKey: ['restEspacioPorSucursal', variables],
    queryFn: async () => {
      const response = await client.request<{ restEspacioPorSucursal: RestEspacio[] }>(RESTESPACIOPORSUCURSAL, variables);
      return response.restEspacioPorSucursal;
    },
    ...options,
  });
};