// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import { client, gql } from '../client'
import { SINMOTIVOANULACIONFRAGMENT } from '../fragments/SinMotivoAnulacionFragments'
import { SinMotivoAnulacion } from '../types'

export interface SinMotivoAnulacionVariables {}

export const SINMOTIVOANULACION = gql`
  query SinMotivoAnulacion {
    sinMotivoAnulacion {
      ...SinMotivoAnulacionFragment
    }
  }
  ${SINMOTIVOANULACIONFRAGMENT}
`

export const useSinMotivoAnulacion = (
  variables: SinMotivoAnulacionVariables,
  options?: Omit<UseQueryOptions<SinMotivoAnulacion[], Error>, 'queryKey' | 'queryFn'>,
) => {
  return useQuery<SinMotivoAnulacion[], Error>({
    queryKey: ['sinMotivoAnulacion', variables],
    queryFn: async () => {
      const response = await client.request<{ sinMotivoAnulacion: SinMotivoAnulacion[] }>(
        SINMOTIVOANULACION,
        variables,
      )
      return response.sinMotivoAnulacion
    },
    ...options,
  })
}
