// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { TIPOARTICULOCONNECTIONFRAGMENT } from '../fragments/TipoArticuloConnectionFragments';
import { TipoArticuloConnection } from '../types';

export interface TipoArticuloListadoVariables {
  limit: number;
  page?: number;
  reverse?: boolean;
  query?: string;
}

export const TIPOARTICULOLISTADO = gql`
  query TipoArticuloListado($limit: Int!, $page: Int, $reverse: Boolean, $query: String) {
    tipoArticuloListado(limit: $limit, page: $page, reverse: $reverse, query: $query) { ...TipoArticuloConnectionFragment }
  }
  ${TIPOARTICULOCONNECTIONFRAGMENT}
`;

export const useTipoArticuloListado = (variables: TipoArticuloListadoVariables, options?: Omit<UseQueryOptions<TipoArticuloConnection, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<TipoArticuloConnection, Error>({
    queryKey: ['tipoArticuloListado', variables],
    queryFn: async () => {
      const response = await client.request<{ tipoArticuloListado: TipoArticuloConnection }>(TIPOARTICULOLISTADO, variables);
      return response.tipoArticuloListado;
    },
    ...options,
  });
};