// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const RESTFACTURACONNECTIONFRAGMENT = gql`
  fragment RestFacturaConnectionFragment on RestFacturaConnection {
    pageInfo {
      hasNextPage
        hasPrevPage
        totalDocs
        limit
        page
        totalPages
    }
    docs {
      _id
        nitEmisor
        razonSocialEmisor
        numeroFactura
        tipoFactura {
          codigoClasificador
              descripcion
        }
        tipoEmision {
          codigoClasificador
              descripcion
        }
        cuf
        cufd {
          codigo
              codigoControl
              direccion
              fechaVigencia
              fechaInicial
        }
        cuis {
          codigo
              fechaVigencia
        }
        sucursal {
          codigo
              direccion
              telefono
              departamento {
                codigo
                      codigoPais
                      sigla
                      departamento
              }
              municipio
              integracionSiat
        }
        puntoVenta {
          codigo
              tipoPuntoVenta {
                codigoClasificador
                      descripcion
              }
              nombre
              descripcion
        }
        fechaEmision
        cliente {
          razonSocial
              codigoCliente
              tipoDocumentoIdentidad {
                codigoClasificador
                      descripcion
              }
              numeroDocumento
              complemento
              nombres
              apellidos
              email
              telefono
              lineaCredito
              creditoMinimo
              creditoMaximo
              direccion
              direccionLaboral
              entidadLaboral
              maximoPlazo
        }
        metodoPago {
          codigoClasificador
              descripcion
        }
        numeroTarjeta
        montoTotal
        montoTotalLiteral
        montoTotalSujetoIva
        moneda {
          codigoClasificador
              descripcion
        }
        tipoCambio
        montoTotalMoneda
        montoGiftCard
        descuentoAdicional
        cafc
        leyenda
        subLeyenda
        usuario
        documentoSector {
          codigoClasificador
              descripcion
        }
        motivoAnulacion {
          codigoClasificador
              descripcion
        }
        detalleExtra
        detalle {
          nroItem
              actividadEconomica {
                codigoCaeb
                      descripcion
                      tipoActividad
              }
              productoServicio {
                codigoActividad
                      codigoProducto
                      descripcionProducto
              }
              producto
              descripcion
              cantidad
              unidadMedida {
                codigoClasificador
                      descripcion
              }
              precioUnitario
              montoDescuento
              subTotal
              numeroSerie
              numeroImei
              detalleExtra
              log
        }
        eventoSignificativo
        codigoRecepcion
        representacionGrafica {
          pdf
              xml
              rollo
              rolloResumen
              rolloReducido
              sin
        }
        usucre
        createdAt
        usumod
        updatedAt
        state
        referencia
        tipoVenta
        log
    }
  }
`;