// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTANOMALIAFRAGMENT } from '../fragments/RestAnomaliaFragments';
import { RestAnomalia } from '../types';

export interface RestAnomaliaPorSucursalVariables {
  codigoSucursal?: number;
}

export const RESTANOMALIAPORSUCURSAL = gql`
  query RestAnomaliaPorSucursal($codigoSucursal: Int) {
    restAnomaliaPorSucursal(codigoSucursal: $codigoSucursal) { ...RestAnomaliaFragment }
  }
  ${RESTANOMALIAFRAGMENT}
`;

export const useRestAnomaliaPorSucursal = (variables: RestAnomaliaPorSucursalVariables, options?: Omit<UseQueryOptions<RestAnomalia, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestAnomalia, Error>({
    queryKey: ['restAnomaliaPorSucursal', variables],
    queryFn: async () => {
      const response = await client.request<{ restAnomaliaPorSucursal: RestAnomalia }>(RESTANOMALIAPORSUCURSAL, variables);
      return response.restAnomaliaPorSucursal;
    },
    ...options,
  });
};