// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTPEDIDOAUDITORIACONNECTIONFRAGMENT } from '../fragments/RestPedidoAuditoriaConnectionFragments';
import { EntidadParamsInput, RestPedidoAuditoriaConnection } from '../types';

export interface RestPedidoAuditoriaListadoVariables {
  entidad: EntidadParamsInput;
  limit: number;
  page?: number;
  reverse?: boolean;
  query?: string;
}

export const RESTPEDIDOAUDITORIALISTADO = gql`
  query RestPedidoAuditoriaListado($entidad: EntidadParamsInput!, $limit: Int!, $page: Int, $reverse: Boolean, $query: String) {
    restPedidoAuditoriaListado(entidad: $entidad, limit: $limit, page: $page, reverse: $reverse, query: $query) { ...RestPedidoAuditoriaConnectionFragment }
  }
  ${RESTPEDIDOAUDITORIACONNECTIONFRAGMENT}
`;

export const useRestPedidoAuditoriaListado = (variables: RestPedidoAuditoriaListadoVariables, options?: Omit<UseQueryOptions<RestPedidoAuditoriaConnection, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestPedidoAuditoriaConnection, Error>({
    queryKey: ['restPedidoAuditoriaListado', variables],
    queryFn: async () => {
      const response = await client.request<{ restPedidoAuditoriaListado: RestPedidoAuditoriaConnection }>(RESTPEDIDOAUDITORIALISTADO, variables);
      return response.restPedidoAuditoriaListado;
    },
    ...options,
  });
};