// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTREPORTEPEDIDOVENTASPORARTICULOPUNTOVENTAFRAGMENT } from '../fragments/RestReportePedidoVentasPorArticuloPuntoVentaFragments';
import { DateDMY, RestReportePedidoVentasPorArticuloPuntoVenta } from '../types';

export interface RestReportePedidoVentasPorArticuloPuntoVentaVariables {
  fechaInicial: DateDMY;
  fechaFinal: DateDMY;
  codigoSucursal: number;
  codigoPuntoVenta?: number[];
  mostrarTodos?: boolean;
  limit?: number;
}

export const RESTREPORTEPEDIDOVENTASPORARTICULOPUNTOVENTA = gql`
  query RestReportePedidoVentasPorArticuloPuntoVenta($fechaInicial: DateDMY!, $fechaFinal: DateDMY!, $codigoSucursal: Int!, $codigoPuntoVenta: [Int], $mostrarTodos: Boolean, $limit: Int) {
    restReportePedidoVentasPorArticuloPuntoVenta(fechaInicial: $fechaInicial, fechaFinal: $fechaFinal, codigoSucursal: $codigoSucursal, codigoPuntoVenta: $codigoPuntoVenta, mostrarTodos: $mostrarTodos, limit: $limit) { ...RestReportePedidoVentasPorArticuloPuntoVentaFragment }
  }
  ${RESTREPORTEPEDIDOVENTASPORARTICULOPUNTOVENTAFRAGMENT}
`;

export const useRestReportePedidoVentasPorArticuloPuntoVenta = (variables: RestReportePedidoVentasPorArticuloPuntoVentaVariables, options?: Omit<UseQueryOptions<RestReportePedidoVentasPorArticuloPuntoVenta[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestReportePedidoVentasPorArticuloPuntoVenta[], Error>({
    queryKey: ['restReportePedidoVentasPorArticuloPuntoVenta', variables],
    queryFn: async () => {
      const response = await client.request<{ restReportePedidoVentasPorArticuloPuntoVenta: RestReportePedidoVentasPorArticuloPuntoVenta[] }>(RESTREPORTEPEDIDOVENTASPORARTICULOPUNTOVENTA, variables);
      return response.restReportePedidoVentasPorArticuloPuntoVenta;
    },
    ...options,
  });
};