// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTPEDIDOAUDITORIAFRAGMENT } from '../fragments/RestPedidoAuditoriaFragments';
import { DateDMYHHMMSS, RestPedidoAuditoria } from '../types';

export interface RestPedidoAuditoriaReporteAnomaliaVariables {
  codigoSucursal: number;
  fechaInicial: DateDMYHHMMSS;
  fechaFinal: DateDMYHHMMSS;
}

export const RESTPEDIDOAUDITORIAREPORTEANOMALIA = gql`
  query RestPedidoAuditoriaReporteAnomalia($codigoSucursal: Int!, $fechaInicial: DateDMYHHMMSS!, $fechaFinal: DateDMYHHMMSS!) {
    restPedidoAuditoriaReporteAnomalia(codigoSucursal: $codigoSucursal, fechaInicial: $fechaInicial, fechaFinal: $fechaFinal) { ...RestPedidoAuditoriaFragment }
  }
  ${RESTPEDIDOAUDITORIAFRAGMENT}
`;

export const useRestPedidoAuditoriaReporteAnomalia = (variables: RestPedidoAuditoriaReporteAnomaliaVariables, options?: Omit<UseQueryOptions<RestPedidoAuditoria[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestPedidoAuditoria[], Error>({
    queryKey: ['restPedidoAuditoriaReporteAnomalia', variables],
    queryFn: async () => {
      const response = await client.request<{ restPedidoAuditoriaReporteAnomalia: RestPedidoAuditoria[] }>(RESTPEDIDOAUDITORIAREPORTEANOMALIA, variables);
      return response.restPedidoAuditoriaReporteAnomalia;
    },
    ...options,
  });
};