// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTREPORTEPEDIDOVENTASPORARTICULOFRAGMENT } from '../fragments/RestReportePedidoVentasPorArticuloFragments';
import { DateDMY, RestReportePedidoVentasPorArticulo } from '../types';

export interface RestReportePedidoVentasPorArticuloComercioVariables {
  fechaInicial: DateDMY;
  fechaFinal: DateDMY;
  codigoSucursal?: number[];
}

export const RESTREPORTEPEDIDOVENTASPORARTICULOCOMERCIO = gql`
  query RestReportePedidoVentasPorArticuloComercio($fechaInicial: DateDMY!, $fechaFinal: DateDMY!, $codigoSucursal: [Int]) {
    restReportePedidoVentasPorArticuloComercio(fechaInicial: $fechaInicial, fechaFinal: $fechaFinal, codigoSucursal: $codigoSucursal) { ...RestReportePedidoVentasPorArticuloFragment }
  }
  ${RESTREPORTEPEDIDOVENTASPORARTICULOFRAGMENT}
`;

export const useRestReportePedidoVentasPorArticuloComercio = (variables: RestReportePedidoVentasPorArticuloComercioVariables, options?: Omit<UseQueryOptions<RestReportePedidoVentasPorArticulo[], Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestReportePedidoVentasPorArticulo[], Error>({
    queryKey: ['restReportePedidoVentasPorArticuloComercio', variables],
    queryFn: async () => {
      const response = await client.request<{ restReportePedidoVentasPorArticuloComercio: RestReportePedidoVentasPorArticulo[] }>(RESTREPORTEPEDIDOVENTASPORARTICULOCOMERCIO, variables);
      return response.restReportePedidoVentasPorArticuloComercio;
    },
    ...options,
  });
};