// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { NOTACREDITODEBITOFRAGMENT } from '../fragments/NotaCreditoDebitoFragments';
import { NotaCreditoDebito } from '../types';

export interface RestNotaCreditoDebitoVariables {
  cuf: string;
}

export const RESTNOTACREDITODEBITO = gql`
  query RestNotaCreditoDebito($cuf: ID!) {
    restNotaCreditoDebito(cuf: $cuf) { ...NotaCreditoDebitoFragment }
  }
  ${NOTACREDITODEBITOFRAGMENT}
`;

export const useRestNotaCreditoDebito = (variables: RestNotaCreditoDebitoVariables, options?: Omit<UseQueryOptions<NotaCreditoDebito, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<NotaCreditoDebito, Error>({
    queryKey: ['restNotaCreditoDebito', variables],
    queryFn: async () => {
      const response = await client.request<{ restNotaCreditoDebito: NotaCreditoDebito }>(RESTNOTACREDITODEBITO, variables);
      return response.restNotaCreditoDebito;
    },
    ...options,
  });
};