// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { useQuery, UseQueryOptions } from '@tanstack/react-query';
import { client, gql } from '../client';
import { RESTNOTACREDITODEBITOCONNECTIONFRAGMENT } from '../fragments/RestNotaCreditoDebitoConnectionFragments';
import { EntidadParamsInput, RestNotaCreditoDebitoConnection } from '../types';

export interface RestNotaCreditoDebitoListadoVariables {
  limit: number;
  page?: number;
  reverse?: boolean;
  query?: string;
  entidad?: EntidadParamsInput;
}

export const RESTNOTACREDITODEBITOLISTADO = gql`
  query RestNotaCreditoDebitoListado($limit: Int!, $page: Int, $reverse: Boolean, $query: String, $entidad: EntidadParamsInput) {
    restNotaCreditoDebitoListado(limit: $limit, page: $page, reverse: $reverse, query: $query, entidad: $entidad) { ...RestNotaCreditoDebitoConnectionFragment }
  }
  ${RESTNOTACREDITODEBITOCONNECTIONFRAGMENT}
`;

export const useRestNotaCreditoDebitoListado = (variables: RestNotaCreditoDebitoListadoVariables, options?: Omit<UseQueryOptions<RestNotaCreditoDebitoConnection, Error>, 'queryKey' | 'queryFn'>) => {
  return useQuery<RestNotaCreditoDebitoConnection, Error>({
    queryKey: ['restNotaCreditoDebitoListado', variables],
    queryFn: async () => {
      const response = await client.request<{ restNotaCreditoDebitoListado: RestNotaCreditoDebitoConnection }>(RESTNOTACREDITODEBITOLISTADO, variables);
      return response.restNotaCreditoDebitoListado;
    },
    ...options,
  });
};