// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const ARQUEOCAJAFRAGMENT = gql`
  fragment ArqueoCajaFragment on ArqueoCaja {
    _id
    cajaId
    cajaCodigo
    sucursal {
      codigo
        direccion
        telefono
        departamento {
          codigo
              codigoPais
              sigla
              departamento
        }
        municipio
        integracionSiat
    }
    puntoVenta {
      codigo
        tipoPuntoVenta {
          codigoClasificador
              descripcion
        }
        nombre
        descripcion
    }
    usuario
    usuariosCaja
    usuarioApertura
    usuarioCierre
    modulo
    supervisor
    responsables
    montoInicial
    nroVentas
    totalVentas
    totalVentasEfectivo
    totalRetiros
    totalIngresos
    montoTeorico
    montoReal
    diferencia
    metodoPagoVenta {
      metodoPago {
          codigoClasificador
              descripcion
        }
        monto
        montoUsuario
    }
    retiros {
      motivo
        monto
        beneficiario
        usuario
        aprobador
        comprobante {
          tipo
              numero
        }
        fecha
        representacionGrafica {
          pdf
              rollo
        }
    }
    ingresos {
      motivo
        monto
        usuario
        aprobador
        fecha
    }
    cortesia {
      conteoPedidos
        conteoArticulos
        montoTotal
    }
    observaciones {
      fecha
        accion
        usuario
        observacion
    }
    fechaApertura
    fechaCierre
    turnoCaja {
      _id
        nombre
        horaInicio
        horaCierre
        bloquearVentas
        state
        usucre
        createdAt
        usumod
        updatedAt
    }
    representacionGrafica {
      # Datos simples (Tipo ya expandido previamente)
      pdf
      rollo
    }
    moneda {
      codigo
        descripcion
        sigla
    }
    state
    usucre
    createdAt
    usumod
    updatedAt
  }
`;