// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const CAJACONNECTIONFRAGMENT = gql`
  fragment CajaConnectionFragment on CajaConnection {
    pageInfo {
      hasNextPage
        hasPrevPage
        totalDocs
        limit
        page
        totalPages
    }
    docs {
      _id
        codigo
        sucursal {
          codigo
              direccion
              telefono
              departamento {
                codigo
                      codigoPais
                      sigla
                      departamento
              }
              municipio
              integracionSiat
        }
        puntoVenta {
          codigo
              tipoPuntoVenta {
                codigoClasificador
                      descripcion
              }
              nombre
              descripcion
        }
        usuarios {
          usuario
        }
        saldoInicial
        saldoActual
        responsable {
          # Datos simples (Tipo ya expandido previamente)
          usuario
        }
        usuarioApertura
        fechaUltimoCierre
        ultimoArqueoCajaId
        ubicacion
        state
        usucre
        createdAt
        usumod
        updatedAt
    }
  }
`;