// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const TURNOCAJAFRAGMENT = gql`
  fragment TurnoCajaFragment on TurnoCaja {
    _id
    nombre
    horaInicio
    horaCierre
    bloquearVentas
    state
    usucre
    createdAt
    usumod
    updatedAt
  }
`;