// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const RESTREPORTEPEDIDOVENTASPORARTICULOFRAGMENT = gql`
  fragment RestReportePedidoVentasPorArticuloFragment on RestReportePedidoVentasPorArticulo {
    tipoArticulo
    codigoArticulo
    nombreArticulo
    sucursal
    puntoVenta
    nroVentas
    montoVentas
    montoDescuento
    otrosCostos
    unidadMedida
    moneda
    totalFinal
    tuvoVariacionPrecio
    preciosRegistrados {
      precio
        cantidad
    }
  }
`;