// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const RESTPEDIDOAUDITORIACONNECTIONFRAGMENT = gql`
  fragment RestPedidoAuditoriaConnectionFragment on RestPedidoAuditoriaConnection {
    pageInfo {
      hasNextPage
        hasPrevPage
        totalDocs
        limit
        page
        totalPages
    }
    docs {
      pedidoId
        numeroPedido
        numeroOrden
        kardexPeriodo {
          codigo
              descripcion
              documentoSector {
                codigoClasificador
                      descripcion
              }
              state
              usucre
              createdAt
              usumod
              updatedAt
        }
        codigoSucursal
        codigoPuntoVenta
        accion
        usuario
        resumenCambios
        duracionMinutos
        articulos {
          articuloId
              nroItem
              tipoArticulo {
                codigo
                      descripcion
              }
              claseArticulo
              gestionArticulo
              grupoArticulo {
                codigoGrupoArticulo
                      nombreGrupoArticulo
              }
              codigoArticulo
              nombreArticulo
              almacen {
                _id
                      codigoAlmacen
                      nombre
                      ubicacion
                      sucursal {
                        codigo
                                direccion
                                telefono
                                departamento {
                                  codigo
                                            codigoPais
                                            sigla
                                            departamento
                                }
                                municipio
                                integracionSiat
                      }
                      tipo
                      activo
                      prioridad
                      state
                      usucre
                      createdAt
                      usumod
                      updatedAt
              }
              lote {
                _id
                      codigoLote
                      descripcion
                      codigoArticulo
                      sucursal {
                        # Datos simples (Tipo ya expandido previamente)
                        codigo
                        direccion
                        telefono
                        departamento {
                          codigo
                          codigoPais
                          sigla
                          departamento
                        }
                        municipio
                        integracionSiat
                      }
                      atributo1
                      atributo2
                      atributo3
                      fechaAdmision
                      fechaFabricacion
                      fechaVencimiento
                      state
                      usucre
                      createdAt
                      usumod
                      updatedAt
              }
              codigoGrupo
              sinProductoServicio {
                codigoActividad
                      codigoProducto
                      descripcionProducto
              }
              articuloPrecioBase {
                articuloUnidadMedida {
                        _id
                                codigoUnidadMedida
                                nombreUnidadMedida
                                sinUnidadMedida {
                                  codigoClasificador
                                            descripcion
                                }
                                longitud
                                ancho
                                altura
                                peso
                                volumen
                                state
                                usucre
                                createdAt
                                usumod
                                updatedAt
                      }
                      moneda {
                        _id
                                codigo
                                descripcion
                                sigla
                                tipoCambio
                                tipoCambioCompra
                                activo
                                state
                                usucre
                                usumod
                                createdAt
                                updatedAt
                      }
                      tipoCambio
                      estructuraValor {
                        tipoOperacion
                                valor
                                valorAnterior
                                valorConImpuesto
                                descuento
                                descuentoAdicional
                                descuentoTotal
                                descuentoP
                                descuentoAdicionalP
                                descuentoTotalP
                                valorNeto
                                impuestoUnitario
                                gastoAdicional
                                variacion
                                valorFinal
                                totales {
                                  subtotalBruto
                                            subtotalLineaVisual
                                            totalDescuento
                                            totalDescuentoP
                                            totalDescuentoAdicional
                                            totalDescuentoGeneral
                                            totalDescuentoAdicionalP
                                            totalDescuentoGeneralP
                                            subtotalNeto
                                            totalImpuestos
                                            totalGasto
                                            totalFinal
                                }
                      }
                      tipoOperacion
                      valor
                      cantidad
                      cantidadAnterior
                      cantidadFactor
                      descuento
                      descuentoAdicional
                      otrosCostos
                      impuesto
                      incluyeImpuesto
                      esDescuentoTotal
                      factorAjuste
              }
              articuloPrecio {
                # Datos simples (Tipo ya expandido previamente)
                articuloUnidadMedida {
                  _id
                  codigoUnidadMedida
                  nombreUnidadMedida
                  longitud
                  ancho
                  altura
                  peso
                  volumen
                  state
                  usucre
                  createdAt
                  usumod
                  updatedAt
                }
                moneda {
                  _id
                  codigo
                  descripcion
                  sigla
                  tipoCambio
                  tipoCambioCompra
                  activo
                  state
                  usucre
                  usumod
                  createdAt
                  updatedAt
                }
                tipoCambio
                estructuraValor {
                  tipoOperacion
                  valor
                  valorAnterior
                  valorConImpuesto
                  descuento
                  descuentoAdicional
                  descuentoTotal
                  descuentoP
                  descuentoAdicionalP
                  descuentoTotalP
                  valorNeto
                  impuestoUnitario
                  gastoAdicional
                  variacion
                  valorFinal
                }
                tipoOperacion
                valor
                cantidad
                cantidadAnterior
                cantidadFactor
                descuento
                descuentoAdicional
                otrosCostos
                impuesto
                incluyeImpuesto
                esDescuentoTotal
                factorAjuste
              }
              detalleExtra
              nota
              notaRapida {
                cantidad
                      valor
                      atributo1
                      atributo2
              }
              verificarStock
              impresoras {
                _id
                      sucursal {
                        codigo
                                direccion
                                telefono
                                departamento {
                                  # Datos simples (Tipo ya expandido previamente)
                                  codigo
                                  codigoPais
                                  sigla
                                  departamento
                                }
                                municipio
                                integracionSiat
                      }
                      puntoVenta {
                        codigo
                                tipoPuntoVenta {
                                  codigoClasificador
                                            descripcion
                                }
                                nombre
                                descripcion
                      }
                      nombre
                      descripcion
                      atributo1
                      atributo2
                      state
                      usucre
                      createdAt
                      usumod
                      updatedAt
              }
              cortesia
              variacionReceta {
                nroItem
                      articuloId
                      codigoArticulo
                      nombreArticulo
                      almacen {
                        # Datos simples (Tipo ya expandido previamente)
                        _id
                        codigoAlmacen
                        nombre
                        ubicacion
                        sucursal {
                          codigo
                          direccion
                          telefono
                          municipio
                          integracionSiat
                        }
                        tipo
                        activo
                        prioridad
                        state
                        usucre
                        createdAt
                        usumod
                        updatedAt
                      }
                      lote {
                        # Datos simples (Tipo ya expandido previamente)
                        _id
                        codigoLote
                        descripcion
                        codigoArticulo
                        sucursal {
                          codigo
                          direccion
                          telefono
                          municipio
                          integracionSiat
                        }
                        atributo1
                        atributo2
                        atributo3
                        fechaAdmision
                        fechaFabricacion
                        fechaVencimiento
                        state
                        usucre
                        createdAt
                        usumod
                        updatedAt
                      }
                      removido
                      esExtra
                      articuloPrecio {
                        # Datos simples (Tipo ya expandido previamente)
                        articuloUnidadMedida {
                          _id
                          codigoUnidadMedida
                          nombreUnidadMedida
                          longitud
                          ancho
                          altura
                          peso
                          volumen
                          state
                          usucre
                          createdAt
                          usumod
                          updatedAt
                        }
                        moneda {
                          _id
                          codigo
                          descripcion
                          sigla
                          tipoCambio
                          tipoCambioCompra
                          activo
                          state
                          usucre
                          usumod
                          createdAt
                          updatedAt
                        }
                        tipoCambio
                        estructuraValor {
                          tipoOperacion
                          valor
                          valorAnterior
                          valorConImpuesto
                          descuento
                          descuentoAdicional
                          descuentoTotal
                          descuentoP
                          descuentoAdicionalP
                          descuentoTotalP
                          valorNeto
                          impuestoUnitario
                          gastoAdicional
                          variacion
                          valorFinal
                        }
                        tipoOperacion
                        valor
                        cantidad
                        cantidadAnterior
                        cantidadFactor
                        descuento
                        descuentoAdicional
                        otrosCostos
                        impuesto
                        incluyeImpuesto
                        esDescuentoTotal
                        factorAjuste
                      }
                      nota
                      notaRapida {
                        # Datos simples (Tipo ya expandido previamente)
                        cantidad
                        valor
                        atributo1
                        atributo2
                      }
                      state
              }
              modificadores {
                articuloModificadorId
                      articuloId
                      nroItem
                      codigoArticulo
                      nombreArticulo
                      almacen {
                        # Datos simples (Tipo ya expandido previamente)
                        _id
                        codigoAlmacen
                        nombre
                        ubicacion
                        sucursal {
                          codigo
                          direccion
                          telefono
                          municipio
                          integracionSiat
                        }
                        tipo
                        activo
                        prioridad
                        state
                        usucre
                        createdAt
                        usumod
                        updatedAt
                      }
                      lote {
                        # Datos simples (Tipo ya expandido previamente)
                        _id
                        codigoLote
                        descripcion
                        codigoArticulo
                        sucursal {
                          codigo
                          direccion
                          telefono
                          municipio
                          integracionSiat
                        }
                        atributo1
                        atributo2
                        atributo3
                        fechaAdmision
                        fechaFabricacion
                        fechaVencimiento
                        state
                        usucre
                        createdAt
                        usumod
                        updatedAt
                      }
                      esOpcionGratuita
                      elegibleParaGratis
                      cantidadIncluida
                      articuloPrecio {
                        # Datos simples (Tipo ya expandido previamente)
                        articuloUnidadMedida {
                          _id
                          codigoUnidadMedida
                          nombreUnidadMedida
                          longitud
                          ancho
                          altura
                          peso
                          volumen
                          state
                          usucre
                          createdAt
                          usumod
                          updatedAt
                        }
                        moneda {
                          _id
                          codigo
                          descripcion
                          sigla
                          tipoCambio
                          tipoCambioCompra
                          activo
                          state
                          usucre
                          usumod
                          createdAt
                          updatedAt
                        }
                        tipoCambio
                        estructuraValor {
                          tipoOperacion
                          valor
                          valorAnterior
                          valorConImpuesto
                          descuento
                          descuentoAdicional
                          descuentoTotal
                          descuentoP
                          descuentoAdicionalP
                          descuentoTotalP
                          valorNeto
                          impuestoUnitario
                          gastoAdicional
                          variacion
                          valorFinal
                        }
                        tipoOperacion
                        valor
                        cantidad
                        cantidadAnterior
                        cantidadFactor
                        descuento
                        descuentoAdicional
                        otrosCostos
                        impuesto
                        incluyeImpuesto
                        esDescuentoTotal
                        factorAjuste
                      }
                      nota
                      notaRapida {
                        # Datos simples (Tipo ya expandido previamente)
                        cantidad
                        valor
                        atributo1
                        atributo2
                      }
                      state
              }
              state
        }
        totales {
          operacion {
                # Datos simples (Tipo ya expandido previamente)
                subtotalBruto
                subtotalLineaVisual
                totalDescuento
                totalDescuentoP
                totalDescuentoAdicional
                totalDescuentoGeneral
                totalDescuentoAdicionalP
                totalDescuentoGeneralP
                subtotalNeto
                totalImpuestos
                totalGasto
                totalFinal
              }
              sistema {
                # Datos simples (Tipo ya expandido previamente)
                subtotalBruto
                subtotalLineaVisual
                totalDescuento
                totalDescuentoP
                totalDescuentoAdicional
                totalDescuentoGeneral
                totalDescuentoAdicionalP
                totalDescuentoGeneralP
                subtotalNeto
                totalImpuestos
                totalGasto
                totalFinal
              }
        }
        esSospechoso
        motivosSospecha
        riesgoNivel
        riesgoPuntaje
        fechaRegistro
    }
  }
`;