// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const RESTANOMALIAFRAGMENT = gql`
  fragment RestAnomaliaFragment on RestAnomalia {
    codigoSucursal
    montoTotal {
      mu
        sigma
    }
    tiempoMinutos {
      # Datos simples (Tipo ya expandido previamente)
      mu
      sigma
    }
    cantidadPedidosAnalizados
    fechaInicioMuestra
    fechaFinMuestra
    ultimaActualizacion
    generadoPor
  }
`;