// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

import { gql } from '../client';

export const RESTREPORTEPEDIDOVENTASPORARTICULOPUNTOVENTAFRAGMENT = gql`
  fragment RestReportePedidoVentasPorArticuloPuntoVentaFragment on RestReportePedidoVentasPorArticuloPuntoVenta {
    tipoArticulo
    codigoArticulo
    nombreArticulo
    sucursal
    nroVentas
    montoVentas
    montoDescuento
    otrosCostos
    unidadMedida
    moneda
    totalFinal
    tuvoVariacionPrecio
    preciosRegistrados {
      precio
        cantidad
    }
  }
`;