// AUTO-GENERATED BY ISI-GQL developer for Nick Russell

/**
 * Date in DD/MM/YYYY format
 */
export type DateDMY = string;
/**
 * Date in DD/MM/YYYY HH:MM:SS format
 */
export type DateDMYHHMMSS = string;
/**
 * Fecha en formato DD/MM/YYYY HH:MM (Dia/Mes/Anio Hora:Minuto)
 */
export type DateDMYHHMM = string;
/**
 * Url de consulta documentos, para la obtención de la representación impresa, uso de Buffer para la generacion de archivos 
 */
export type UrlConsultaDocumento = string;
/**
 * Se usa para describir el motivo por el cual se anula un determinda documento Eje. Factura, Notas, etc
 */
export interface SinMotivoAnulacion {
  /** Código de Motivo de Anulación */
  codigoClasificador: string;
  /** Descripción del Motivo de Anulación */
  descripcion: string;
}

/**
 * La Homologación de productos y servicios permite al Contribuyente relacionar los códigos utilizados para sus productos y servicios con los códigos genéricos proporcionados por la Administración Tributaria
 */
export interface SinProductoServicio {
  /** Código de Actividad Económica */
  codigoActividad: string;
  /** Código de Producto o Servicio */
  codigoProducto: string;
  /** Descripción genérica del Producto o Servicio */
  descripcionProducto: string;
}

/**
 * Tipos de documentos que se pueden emitir
 */
export interface SinTipoDocumentoIdentidad {
  /** Código de Tipo de Documento */
  codigoClasificador: string;
  /** Descripción del Tipo de Documento */
  descripcion: string;
}

/**
 * Están definidos para que cada Factura Digital pueda ser enviada por un Servicio Web, lo cual asegura la independencia del mismo en caso de modificaciones o ajustes.
 */
export interface SinTipoDocumentoSector {
  /** Código de Tipo de Documento Sector */
  codigoClasificador?: string;
  /** Descripción del Tipo de Documento Sector */
  descripcion?: string;
}

/**
 * Es un lugar, dispositivo o medio de venta que está asociado a una sucursal o casa matriz y que por su forma de trabajo puede ser fijo (en el caso de puntos de venta para ferias) o móvil (en el caso de camiones de repartidores o de distribución). Los Puntos de Venta no están registrados en el Padrón Nacional de Contribuyentes
 */
export interface SinTipoPuntoVenta {
  /** Código de Tipo de Punto de Venta */
  codigoClasificador: string;
  /** Descripción del Tipo de Punto de Venta */
  descripcion: string;
}

/**
 * Las unidades de medida nos permiten cuantificar claramente las existencias de nuestro inventario, estas nos permiten  la correcta interpretación de las cantidades
 */
export interface SinUnidadMedida {
  /** Código de Unidad de Medida */
  codigoClasificador?: number;
  /** Descripción de Unidad de Medida */
  descripcion?: string;
}

/**
 * Urls de consulta de documentos, impresiones boletos, etc
 */
export interface UrlsConsultaDocumento {
  pdf?: UrlConsultaDocumento;
  xml?: UrlConsultaDocumento;
  rollo?: UrlConsultaDocumento;
  sin?: UrlConsultaDocumento;
}

/**
 * Entrada de datos paramétricos de la entidad como codigos de sucursal o codigos de puntos de venta - El código de sucursal y punto de venta enviado esta restringido a su la restriccion de sucursal y punto de venta - Para verificar las restricciones consulte el servicio usuarioRestriccion
 */
export interface EntidadParamsInput {
  /** Codigo de sucursal */
  codigoSucursal?: number;
  /** Código de punto de venta */
  codigoPuntoVenta?: number;
}

/**
 * Datos de entrada de un cliente registrado en base de datos
 */
export interface ClienteOperacionInput {
  /** Codigo del cliente definido por el cliente, en caso de no enviar, se asocia: - [numeroDocumento][complemento] */
  codigoCliente: string;
  /** Razon Social del cliente. - En caso de no enviar, se obtiene la razon social del cliente registrado. */
  razonSocial?: string;
  /** Correo electrónico del cliente. - En caso de registro de un nuevo cliente, se debe ingresar el email - En caso de existencia de usuario, puede usarse para reemplazar el email del cliente registrado. */
  email?: string;
  /** Telefono de referencia */
  telefono?: string;
  /** Dirección del cliente */
  direccion?: string;
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface ClienteOperacion {
  /** Razon Social del cliente. */
  razonSocial?: string;
  /** Codigo unico que se asigna al cliente. */
  codigoCliente?: string;
  /** Código del clasificador del tipo documento de identidad. */
  tipoDocumentoIdentidad?: SinTipoDocumentoIdentidad;
  /** Numero de documento del cliente */
  numeroDocumento?: string;
  /** Si es C.I., y contenga un numero de complemento */
  complemento?: string;
  /** Nombre del  titular de la cuenta. */
  nombres?: string;
  /** Apellidos del titular de la cuenta. */
  apellidos?: string;
  /** Correo electrónico de la persona, este campo es unico en la organización. */
  email?: string;
  /** Telefono de referencia */
  telefono?: string;
  /** Si el cliente tiene linea de credito - true: El cliente puede acceder a una linea de credito - false: El cliente no puede acceder a una linea de credito */
  lineaCredito?: boolean;
  /** Credito minimo para acceder a una linea de credito - 0 o nulo: No hay limite */
  creditoMinimo?: number;
  /** Credito maximo para acceder a una linea de credito - 0 o nulo: No hay limite */
  creditoMaximo?: number;
  /** Direccion de residencia del cliente */
  direccion?: string;
  /** Dirección en el cual el cliente desarrolla sus actividades económicas */
  direccionLaboral?: string;
  /** Nombre de la entidad donde el cliente desarrolla sus actividades económicas */
  entidadLaboral?: string;
  /** Máximo plazo (meses) de duración del un crédito - Se contabiliza en Nro de meses. */
  maximoPlazo?: number;
}

/**
 * Datos del punto de venta minificados
 */
export interface PuntoVenta {
  /** Código único del punto de venta */
  codigo?: number;
  /** - Comisionistas de acuerdo a normativa vigente; - Ventanilla de Cobranza autorizada por la ASFI según normativa; - Puntos de Ventas Móviles para venta de bienes o prestación de servicios; - Puntos de Venta YPFB para la venta de combustible a precio internacional; - Puntos de Venta (Cajeros o similares) para la venta de otros bienes y/o prestación de servicios. - Puntos de Venta conjunta, habilitada para emisión conjunta de documentos fiscales. */
  tipoPuntoVenta?: SinTipoPuntoVenta;
  /** Nombre, Alias del punto de venta */
  nombre?: string;
  /** Descripción del punto de venta */
  descripcion?: string;
}

/**
 * Datos del punto de venta, asociado a la factura.
 */
export interface OrgFacturaPuntoVenta {
  /** Codigo del punto de venta. */
  codigo?: number;
  /** Catalogo de Tipo de Punto de Venta. */
  tipoPuntoVenta?: SinTipoPuntoVenta;
  /** Nombre alias del punto de venta. */
  nombre?: string;
  /** Direccion del punto de venta. */
  descripcion?: string;
}

/**
 * Las sucursales son establecimientos secundarios donde se realiza alguna de las actividades económicas del Contribuyente, tienen una dirección física y están registradas en el Padrón Nacional de Contribuyentes. En el Sistema de Facturación, la emisión de las facturas se realiza por sucursal o casa matriz (sucursal 0).
 */
export interface Sucursal {
  /** Codigo único de la sucursal */
  codigo?: number;
  /** Direccion de la sucursal */
  direccion?: string;
  /** Teléfono de referencia */
  telefono?: string;
  /** Datos del departamento */
  departamento?: Departamento;
  /** Municipio donde se encuentra la sucursal */
  municipio?: string;
  /** Si cuenta con integracion SIAT */
  integracionSiat?: boolean;
}

/**
 * Estructura de datos para Departamento
 */
export interface Departamento {
  /** Código segun INE */
  codigo?: number;
  /** Código de Pais segun ISO 3166-1 */
  codigoPais?: number;
  /** Sigla del departamento */
  sigla?: string;
  /** Nombre del departamento */
  departamento?: string;
}

/**
 * Datos de la sucursal asociado a cada factura
 */
export interface OrgFacturaSucursal {
  /** Codigo de la sucursal */
  codigo?: number;
  /** Direccion regitrada en cada sucursal */
  direccion?: string;
  /** Telefono de referencia de la sucursal */
  telefono?: string;
  /** Nombre de departamento de la sucursal */
  departamento?: Departamento;
  /** Nombre de municipio de la sucursal */
  municipio?: string;
  /** Define si existe integración con SISTEMA DE ADMINISTRACIÓN TRIBUTARIA */
  integracionSiat?: boolean;
}

/**
 * Listado de monedas de uso para la empresa
 */
export interface Moneda {
  /** Identificador único interno del registro */
  _id?: string;
  /** Codigo de moneda */
  codigo?: number;
  /** Descripcion de la nueva moneda a adicionar */
  descripcion?: string;
  /** Sigla de la moneda BS, USD, etc */
  sigla?: string;
  /** Tipo de cambio de la moneda para la venta, BS: 1 */
  tipoCambio?: number;
  /** Tipo de cambio de la moneda para la compra, BS: 1 */
  tipoCambioCompra?: number;
  /** 1 = activo 0 = inactivo */
  activo?: number;
  /** Estado del registro */
  state?: string;
  /** Usuario que creo el registro */
  usucre?: string;
  /** Ultimo usuario que modificó el registro */
  usumod?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Ultima fecha de actualizacion del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Datos de acceso de un usuario registrado
 */
export interface MetodoPago {
  /** Razon Social del cliente. */
  codigoClasificador?: number;
  /** Codigo unico que se asigna al cliente. */
  descripcion?: string;
}

/**
 * Periodo de inventario.
 */
export interface KardexPeriodo {
  /** Código */
  codigo?: number;
  /** Descripcioón del kardex periodo */
  descripcion?: string;
  /** Documento sector del periodo */
  documentoSector?: SinTipoDocumentoSector;
  /** Estado del registro */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Datos del tipo de articulo.
 */
export interface Lote {
  /** Identificador único del registro */
  _id?: string;
  /** Código o numero de lote */
  codigoLote?: string;
  /** Descripcion adicional del lote */
  descripcion?: string;
  /** Código articulo global asociado al lote */
  codigoArticulo?: string;
  /** Datos de la sucursal asociado al lote */
  sucursal?: OrgFacturaSucursal;
  /** Atributo adicional 1 */
  atributo1?: string;
  /** Atributo adicional 2 */
  atributo2?: string;
  /** Atributo adicional 3 */
  atributo3?: string;
  /** Fecha de admisión del lote */
  fechaAdmision?: DateDMYHHMMSS;
  /** Fecha de fabricación */
  fechaFabricacion?: DateDMY;
  /** Fecha de vencimiento del lote */
  fechaVencimiento?: DateDMY;
  /** Estado del registro */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Datos del tipo de articulo.
 */
export interface Almacen {
  /** Codigo interno del almacen */
  _id?: string;
  /** Código que identifica al almacen */
  codigoAlmacen?: string;
  /** Nombre del almacen */
  nombre?: string;
  /** Ubicación física del almacen */
  ubicacion?: string;
  /** Definición del grupo de unidad de medida */
  sucursal?: OrgFacturaSucursal;
  /** Tipo de almacen - 1:DESPACHO, 2:REPOSICION, 3:PRODUCCION, 50:NO_VENTA, 90:BLOQUEADO, 99:EXPIRADO, 999:VIRTUAL */
  tipo?: string;
  /** Si el almacen esta activo */
  activo?: boolean;
  /** Prioridad del almacen - - 1:DESPACHO, 2:REPOSICION, 3:PRODUCCION, 50:NO_VENTA, 90:BLOQUEADO, 99:EXPIRADO, 999:VIRTUAL */
  prioridad?: number;
  /** Estado del registro */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Cálculos operaciones para el item.
 */
export interface TotalesPrecioCostoOperacion {
  /** Importe Bruto (Si no hubiera descuentos), (cantidad * valorBase) */
  subtotalBruto?: number;
  /** Subtotal visual para la línea del carrito (ignora prorrateos globales y gastos). - Contempla el descuento directo y asegura que el impuesto esté incluido. - Fórmula (Si incluye impuesto): = subtotalBruto - totalDescuento - Fórmula (Si NO incluye impuesto): = (subtotalBruto - totalDescuento) * (1 + tasaIva) */
  subtotalLineaVisual?: number;
  /** Sumatoria de los descuentos - No se toma en cuenta el descuento adicional global */
  totalDescuento?: number;
  /** Sumatoria de los descuentos calculado en porcentaje - No se toma en cuenta el descuento adicional global */
  totalDescuentoP?: number;
  /** Descuento adicional Global */
  totalDescuentoAdicional?: number;
  /** Total final de descuentos - totalDescuento + totalDescuentoAdicional */
  totalDescuentoGeneral?: number;
  /** Descuento adicional Global en porcentaje */
  totalDescuentoAdicionalP?: number;
  /** Total final de descuentos en porcentaje - totalDescuento + totalDescuentoAdicional */
  totalDescuentoGeneralP?: number;
  /** Base imponible  Cantidad * valorNeto (Valor total del inventario base o Ingreso total ventas) - incluye todos los descuentos - tasaIva = 1 + (iva / 100) */
  subtotalNeto?: number;
  /** Total Impuestos (Debito Fiscal generado por la línea), (cantidad * impuesto unitario) */
  totalImpuestos?: number;
  /** Cantidad * gastoAdicional */
  totalGasto?: number;
  /** Precio Final Unitario (Lo que paga el cliente por 1), incluye impuestos, y descuentos (cantidad * subtotalNeto) - Cantidad * valorFinal (Total Valor Entrada Stock o Total a Pagar Cliente) - Incluye todos los descuentos y gastos adicionales */
  totalFinal?: number;
}

/**
 * Resultados finales calculados para los detalles - Operacion es según la transacción entre cliente sistema. - Sistema = conversion de datos de operacion segpun moneda principal
 */
export interface TotalesGenerales {
  operacion?: TotalesPrecioCostoOperacion;
  sistema?: TotalesPrecioCostoOperacion;
}

/**
 * - Distribución de precios para almacen - De aquí se obtiene información del Margen de Utilidad Real = PrecioFinalEmpresa - CostoFinal
 */
export interface PrecioCostoOperacion {
  /** Contexto de la operación: - 'costo': Operación de entrada (Compras, Producción). - 'precio': Operación de salida (Ventas, Cotizaciones). */
  tipoOperacion?: string;
  /** El valor nominal actual de la operación. - COSTO: Precio unitario en la Factura del Proveedor. - PRECIO: Precio de Lista / Catálogo actual. */
  valor?: number;
  /** El valor de referencia histórico o estándar. - COSTO: Costo Promedio/Estándar anterior (Kardex). - PRECIO: Generalmente 0 (o Precio de Lista anterior para comparar subidas). */
  valorAnterior?: number;
  /** Precio unitario visual con el impuesto incluido. Ideal para la columna "Precio Unitario" en el carrito. Fórmula (Si incluye impuesto): = valor Fórmula (Si NO incluye impuesto): = valor * (1 + tasaIva) */
  valorConImpuesto?: number;
  /** Descuento directo unitario (Monto) */
  descuento?: number;
  /** Descuento adicional prorrateado (Monto). */
  descuentoAdicional?: number;
  /** Suma del descuento unitario directo + adicional unitario */
  descuentoTotal?: number;
  /** Porcentaje de descuento directo unitario */
  descuentoP?: number;
  /** Porcentaje de descuento adicional unitario prorrateado */
  descuentoAdicionalP?: number;
  /** Porcentaje de la suma de todos los descuentos (Directo + Adicional) */
  descuentoTotalP?: number;
  /** Valor financiero real "limpio" de la mercancía. - COSTO: Base Imponible (Costo sin IVA ni gastos). - PRECIO: Revenue / Ingreso Neto Real (Precio de Venta sin IVA). */
  valorNeto?: number;
  /** Monto del impuesto unitario. - COSTO: Crédito Fiscal (Impuesto recuperable). - PRECIO: Débito Fiscal (Impuesto a pagar al fisco). */
  impuestoUnitario?: number;
  /** Gastos vinculados (Fletes, Seguros, Aduanas). - COSTO: Se suma al valor del inventario. - PRECIO: 0 (Salvo casos especiales de envío). */
  gastoAdicional?: number;
  /** Desviación financiera. - COSTO: Diferencia entre (valorFinal - valorBaseAnterior). - PRECIO: 0. */
  variacion?: number;
  /** El monto final efectivo. - COSTO: Costo Landed (Neto + Gastos). Valor de entrada al Kardex. - PRECIO: Precio Final (Neto + IVA). Monto que paga el Cliente. */
  valorFinal?: number;
  /** Lista de totales calculados */
  totales?: TotalesPrecioCostoOperacion;
}

/**
 * Datos del articulo precio y operacion
 */
export interface ArticuloPrecioOperacion {
  /** Articulo Unidad de medida y sus respectivas homologaciones */
  articuloUnidadMedida?: ArticuloUnidadMedida;
  /** Estructura de moneda que incluye el tipo de cambio segun moneda principal - implementada para version 2026.2.17 */
  moneda?: Moneda;
  /** Tipo de cambio final, puede ser diferente al tipo de cambio de moneda - implementada para version 2026.2.17 */
  tipoCambio?: number;
  /** Desglose de montos y totales para la linea de operacion - implementada para version 2026.2.17 */
  estructuraValor?: PrecioCostoOperacion;
  /** Tipo de operacion, puede ser "precio" o "costo" - implementada para version 2026.2.17 */
  tipoOperacion?: string;
  /** monto final de operacion según sea de tipoOperacion = costo | precio - Valor que se ingresa de front-end - Reemplaza a valor precio del objeto "monedaPrecio" - Implementada para version 2026.2.17 */
  valor?: number;
  /** Cantidad de operacion */
  cantidad?: number;
  /** Historial de cantidad anterior - Generalmente usado para mostrar historial de cantidades en el tiempo */
  cantidadAnterior?: number;
  /** Equivalencia de la unidad (12 unidades por Caja) - Ejemplo: 1 Caja = 12 Unidades por caja, entonces, `cantidadFactor` = 12 */
  cantidadFactor?: number;
  /** Descuento de linea */
  descuento?: number;
  /** En caso de contar con descuento adicional - El valor prorrateado entre todos los articulos asociados a la transacción */
  descuentoAdicional?: number;
  /** Otros costos asociados a la operación - El valor prorrateado entre todos los articulos asociados a la transacción */
  otrosCostos?: number;
  /** Monto impuesto porcentual - El porcentaje del impuesto aplicado a la transacción - Para Bolivia = 13% */
  impuesto?: number;
  /** - Si incluye impuestos, true o false - Default false */
  incluyeImpuesto?: boolean;
  /** ¿El descuento es global (true) o unitario (false)? - No confundir con descuento adicional */
  esDescuentoTotal?: boolean;
  /** Factor de ajuste para el calculo de precio, solo consultable por el usuario */
  factorAjuste?: number;
}

/**
 * Datos de entrada de la unidad de medida montos monedas y precios
 */
export interface ArticuloPrecioOperacionInput {
  /** Código de articulo de unidad de medida */
  codigoArticuloUnidadMedida: string;
  /** Cantidad de operacion o items solicitados segun la unidad de medida seleccionada */
  cantidad: number;
  /** Valor, Precio, costo o monto de entrada */
  precio: number;
  /** Descuento en caso aplique El valor descuento es por fila, independientemente de la cantidad */
  descuento: number;
  /** Si el descuento de linea es total o por unidad - true: descuento total - false: descuento por unidad - Default true */
  esDescuentoTotal?: boolean;
  /** Monto impuesto porcentual que se aplican a la operación - Impuesto % que va de 0% a 100% - Enviar 0 default */
  impuesto: number;
  /** Si la operacion a realizar incluye impuesto - Default false */
  incluyeImpuesto?: boolean;
  /** Tipo de valor asignado al valor|precio|costo - Valores admitidos "precio", "costo", "delivery", "null" - "null" es para cuando no se aplica valor precio default */
  tipoValor?: string;
}

/**
 * Datos del articulo Unidad de medida, tambien se contempla la homologación del mismo.
 */
export interface ArticuloUnidadMedida {
  /** Identificador único interno del registro */
  _id?: string;
  /** Código que identifica a la unidad de medida */
  codigoUnidadMedida?: string;
  /** Nombre de la unidad de medida */
  nombreUnidadMedida?: string;
  /** Nombre de la unidad de medida */
  sinUnidadMedida?: SinUnidadMedida;
  /** Longitud del articulo según la unidad de medida */
  longitud?: number;
  /** Ancho del articulo según la unidad de medida */
  ancho?: number;
  /** Altura del articulo según la unidad de medida */
  altura?: number;
  /** Peso del articulo según la unidad de medida */
  peso?: number;
  /** Volumen del articulo según la unidad de medida */
  volumen?: number;
  /** Estado del registro */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Datos del tipo de articulo.
 */
export interface TipoArticuloOperacion {
  /** Código único que identifica al tipo de articulo. */
  codigo?: string;
  /** Descripción del tipo de articulo. */
  descripcion?: string;
}

/**
 * Grupo de articulo Ejemplo impresora, cables, computadoras, etc
 */
export interface GrupoArticulo {
  /** Código único que identifica al grupo de articulo */
  codigoGrupoArticulo?: string;
  /** Nombre o descripcion */
  nombreGrupoArticulo?: string;
}

/**
 * Datos de articulo minimizado para operaciones entre todas la tablas
 */
export interface ArticuloOperacion {
  /** Identificador interno del articulo - en algunos casos no se depliega */
  articuloId?: string;
  /** Nro de item correlativo */
  nroItem?: number;
  /** Tipo de articulo */
  tipoArticulo?: TipoArticuloOperacion;
  /** 'PRODUCTO' | 'SERVICIO' | 'COMPRA' */
  claseArticulo?: string;
  /** Gestionado por LOTES, SERIE, etc */
  gestionArticulo?: string;
  /** Ejemplo impresora, poleras, etc */
  grupoArticulo?: GrupoArticulo;
  /** Codigo del articulo / producto */
  codigoArticulo?: string;
  /** Nombre registrado del articulo */
  nombreArticulo?: string;
  /** Ubicacion del articulo */
  almacen?: Almacen;
  /** En caso de ubicarlo en un determinado lote */
  lote?: Lote;
  /** Código del grupo unidad de medida referenciado */
  codigoGrupo?: string;
  /** Homologación de productos */
  sinProductoServicio?: SinProductoServicio;
  /** Precio, unidad de medida y moneda segun la moneda principal */
  articuloPrecioBase?: ArticuloPrecioOperacion;
  /** Precio, unidad de medida y moneda segun la registrada por el usuario */
  articuloPrecio?: ArticuloPrecioOperacion;
  /** Detalle Extra para el item */
  detalleExtra?: string;
  /** Nota asociada al item */
  nota?: string;
  /** Nota rapida asociada al item */
  notaRapida?: NotaRapida[];
  /** Si es item que verfica existencia de stock */
  verificarStock?: boolean;
  /** Traza de impresora/as asociadas al articulo - En caso se realice actualizacion de impresoras, estas no afectan al registro */
  impresoras?: Impresora[];
  /** Si es un articulo para cortesía. - El precio del articulo se cambia a 0 solo cuando se finaliza el pedido. - Para otros estados, se mantiene el precio original */
  cortesia?: boolean;
  /** Datos operativos de receta */
  variacionReceta?: ArticuloOperacionReceta[];
  modificadores?: ArticuloOperacionModificador[];
  /** Estado del registro - ELABORADO: Articulo que no ha sufrido cambios en el ciclo de vida del item - ACTUALIZADO: Se ha modificado algún valor del item - ELIMINADO: Se ha eliminado el item - NUEVO: Nuevo ingreso de item */
  state?: string;
}

/**
 * Rastro o huella de la ultima transacción de registros / actualizacion del argumento Articulos / Productos.
 */
export interface UltimaTransaccion {
  /** 'CREACION', 'EDICION', 'FINALIZACION' */
  accion?: string;
  /** Ultimo estado del registro */
  stateAnterior?: string;
  /** Quién hizo ese cambio */
  usuario?: string;
  /** Cuándo ocurrió */
  fecha?: DateDMYHHMMSS;
  /** Las fotografías del momento exacto antes del nuevo cambio */
  articulos?: ArticuloOperacion[];
  /** Totales generados */
  totales?: TotalesGenerales;
  /** Moneda de operación */
  moneda?: Moneda;
  /** Tipo de cambio */
  tipoCambio?: number;
  /** Descuento adicional */
  descuentoAdicional?: number;
  /** Otros costos */
  otrosCostos?: number;
}

/**
 * Nota rapida asociada al articulo
 */
export interface NotaRapida {
  /** Valor string que puede asociarse a cantidad */
  cantidad?: number;
  /** Valor o descripcion de la nota */
  valor?: string;
  /** Atributo 1 */
  atributo1?: string;
  /** Atributo 2 */
  atributo2?: string;
}

/**
 * Datos de entrada para asociar el articulo a las tablas relacionales
 */
export interface ArticuloOperacionInput {
  /** Nro de item en caso de contar con un item - Si envía null se asume nuevo registro - Si se envía un valor, busca el articulo en base a este nroItem */
  nroItem?: number;
  /** Código del articulo */
  codigoArticulo: string;
  /** Codigo de almacen */
  codigoAlmacen: string;
  /** En caso de tener un lote */
  codigoLote?: string;
  /** Definición de cantidad, precios, unidad medida. */
  articuloPrecio: ArticuloPrecioOperacionInput;
  /** Reglas de negocio que permiten la modificación de la receta - Array vacío [] significa que es receta estandar sin modificaciones. */
  variacionReceta?: ArticuloRecetaOperacionInput[];
  /** Productos externos anexados - Array vacío [] si es un producto simple */
  modificadores?: ArticuloModificadorOperacionInput[];
  /** Detalle Extra para el item */
  detalleExtra?: string;
  /** Nota rapida asociada al item */
  notaRapida?: NotaRapidaInput[];
  /** Si el articulo es para cortesía. */
  cortesia?: boolean;
}

/**
 * Nota rapida asociadas al articulo
 */
export interface NotaRapidaInput {
  /** Valor string que puede asociarse a cantidad */
  cantidad?: number;
  /** Valor de la nota */
  valor?: string;
  /** Atributo 1 */
  atributo1?: string;
  /** Atributo 2 */
  atributo2?: string;
}

export interface ArticuloOperacionComplementoInput {
  /** Código del articulo */
  codigoArticulo: string;
  /** Codigo de almacen */
  codigoAlmacen: string;
  /** En caso de tener un lote */
  codigoLote?: string;
  /** Definición de cantidad, precios, unidad medida. */
  articuloPrecio: ArticuloPrecioOperacionInput;
  /** Detalle extra para el item */
  detalleExtra?: string;
  /** Nota asociada al item */
  nota?: string;
}

/**
 * Metodo de pago segun la operacion
 */
export interface MetodoPagoVenta {
  /** Según el clasificador de métodos de pago */
  metodoPago?: MetodoPago;
  /** Monto de pago */
  monto?: number;
}

/**
 * Datos del tipo de articulo.
 */
export interface Impresora {
  /** Identificador único del registro */
  _id?: string;
  /** Ubicación de la impresora */
  sucursal?: Sucursal;
  /** Rastro de punto de venta */
  puntoVenta?: PuntoVenta;
  /** Nombre de la impresora */
  nombre?: string;
  /** Descripcion adicional de la impresora */
  descripcion?: string;
  /** Atributo adicional 1 */
  atributo1?: string;
  /** Atributo adicional 2 */
  atributo2?: string;
  /** Estado del registro */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
}

/**
 * Articulo Operacion Modificador
 */
export interface ArticuloOperacionModificador {
  /** Referencia a la tabla principal */
  articuloModificadorId: string;
  articuloId: string;
  nroItem?: number;
  codigoArticulo?: string;
  nombreArticulo?: string;
  almacen?: Almacen;
  lote?: Lote;
  /** Lo que pidió el cliente (Viene del Front-end) */
  esOpcionGratuita?: boolean;
  /** La regla que lo autorizó (Viene de la BD y se guarda como snapshot) */
  elegibleParaGratis?: boolean;
  /** Cuánto equivalía esta opción en la BD al momento de la venta */
  cantidadIncluida?: number;
  /** El mismo motor pesado de la línea principal */
  articuloPrecio?: ArticuloPrecioOperacion;
  nota?: string;
  notaRapida?: NotaRapida[];
  /** Estado de la linea */
  state?: string;
}

/**
 * Opciones seleccionadas de los grupos de modificadores (Ej. Bebidas, Guarniciones)
 */
export interface ArticuloModificadorOperacionInput {
  /** Nro de item en caso de contar con un item - Si envía null se asume nuevo registro - Si se envía un valor, busca el articulo en base a este nroItem */
  nroItem?: number;
  /** El ID de ArticuloModificador (Para leer maxSeleccion y opcionesGratuitas) */
  articuloModificadorId: string;
  /** Código del articulo */
  codigoArticulo: string;
  /** Codigo de almacen */
  codigoAlmacen: string;
  /** En caso de tener un lote */
  codigoLote?: string;
  /** Definición de cantidad, precios, unidad medida. */
  articuloPrecio: ArticuloPrecioOperacionInput;
  /** true = Consume un cupo de 'opcionesGratuitas' de ArticuloModificador */
  esOpcionGratuita?: boolean;
  /** Nota rapida asociada al item Instrucciones (Ej. "Con poco hielo", "Sin sal") */
  notaRapida?: NotaRapidaInput[];
}

/**
 * Usado en respuesta de operacion de tablas dependientes, POS, REST, ETC
 */
export interface ArticuloOperacionReceta {
  nroItem?: number;
  articuloId?: string;
  codigoArticulo?: string;
  nombreArticulo?: string;
  almacen?: Almacen;
  lote?: Lote;
  removido?: boolean;
  esExtra?: boolean;
  /** El motor pesado (Solo tendrá montos > 0 si esExtra = true) */
  articuloPrecio?: ArticuloPrecioOperacion;
  nota?: string;
  notaRapida?: NotaRapida[];
  /** Estado de la linea */
  state?: string;
}

/**
 * Datos de entrada para asociar el articulo con sus respectiva receta (si tiene), ademas de modificar la estructura de la misma - usado en ArticuloOperacionInput
 */
export interface ArticuloRecetaOperacionInput {
  /** Nro de item en caso de contar con un item - Si envía null se asume nuevo registro - Si se envía un valor, busca el articulo en base a este nroItem */
  nroItem?: number;
  /** Código del articulo */
  codigoArticulo: string;
  /** Codigo de almacen */
  codigoAlmacen: string;
  /** En caso de tener un lote */
  codigoLote?: string;
  /** Definición de cantidad, precios, unidad medida. */
  articuloPrecio: ArticuloPrecioOperacionInput;
  /** Nota rapida asociada al item */
  notaRapida?: NotaRapidaInput[];
  /** Bandera de personalización: ¿El cliente puede pedir que le quiten este ingrediente? (Ej: "Sin Cebolla" -> true. "Sin Pan" -> false). true = Cliente pidió quitarlo (NO descuenta kardex extra, NO cobra) */
  removido?: boolean;
  /** Bandera de personalización: ¿El cliente puede pedir extra de este ingrediente? Si es true, el POS permitirá cobrar una porción (unidad medida) adicional. true = Cliente pidió más cantidad de la estándar */
  esExtra?: boolean;
}

/**
 * Datos de entrada para registro de una mesa
 */
export interface RestMesaInput {
  /** Nombre de mesa Ej. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, m1, m2, etc En caso de usar una mesa generica registrar 0 */
  nombre?: string;
  /** Posible cantidad de comenzales en la mesa - Se puede usar para marcar el nro de items de pedidos */
  nroComensales?: number;
  /** Ubicación de la mesa */
  ubicacion?: string;
}

/**
 * Datos e identificacion de la mesa para los comenzales
 */
export interface RestMesa {
  /** Nombre de mesa Ej. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, m1, m2, 1_2, 1_2_3, etc, perez */
  nombre?: string;
  /** Posible cantidad de comenzales en la mesa */
  nroComensales?: number;
  /** Ubicación de la mesa */
  ubicacion?: string;
}

export interface RestPedidoExpressInput {
  /** Nombre Mesa. - Campo obligatorio */
  mesa: RestMesaInput;
  /** Productos que son añadidos al pedido, pueden ser articulos o grupos de articulos */
  productos: ArticuloOperacionInput[];
  /** Código de moneda de la transacción */
  codigoMoneda: number;
  /** Tipo Cambio de la transacción */
  tipoCambio: number;
  /** Resuelve el tipo de pedido - null = pedido normal - DELIVERY = pedido por delivery - LLEVAR = pedido para llevar */
  tipo?: string;
  /** Nota relacionada al pedido - La información no se comparte con documentos relacionados, Ej. nota venta, factura */
  nota?: string;
  /** Nota rapida alternativa a notas */
  notaRapida?: NotaRapidaInput[];
  /** Términos de entrega del pedido */
  terminos?: string;
  /** Fecha de entrega del pedido */
  fechaEntrega?: DateDMYHHMM;
  /** Dirección de entrega del pedido */
  direccionEntrega?: string;
  /** Identificador relacional del espacio - No realiza la validación de entidad vs espacio entidad - Si no se envía, se utiliza el espacio principal, en caso de no existir, se crea el espacio principal */
  espacioId?: string;
  /** Atributo Auxiliar 1 */
  atributo1?: string;
  /** Atributo Auxiliar 2 */
  atributo2?: string;
  /** Atributo Auxiliar 3 */
  atributo3?: string;
  /** Atributo Auxiliar 4 */
  atributo4?: string;
}

/**
 * Datos del pedido
 */
export interface RestPedido {
  /** Identificador único interno del pedido */
  _id?: string;
  /** Código del pedido autoincrementable dependiendo de la sucursal donde se realiza la transacción */
  numeroPedido?: number;
  /** Número de orden simple actualizable por periodo determinado - Ej. Primer dia del mes se reinicia a 1 - Ej. Segundo dia del mes se reinicia a 1 */
  numeroOrden?: number;
  /** Marca Kardex relacionado Si es null, significa que aun no se realizó el movimiento de inventario */
  marcaKardex?: string;
  /** Datos de la sucursal */
  sucursal?: OrgFacturaSucursal;
  /** Datos del punto de venta */
  puntoVenta?: OrgFacturaPuntoVenta;
  /** Periodo al que corresponde el inventario */
  kardexPeriodo?: KardexPeriodo;
  /** Nombre Mesa. */
  mesa?: RestMesa;
  /** Productos que son añadidos al pedido, pueden ser articulos o kit de articulos */
  productos?: ArticuloOperacion[];
  /** Productos o items que han sido eliminados de forma definitiva, pueden ser articulos o kit de articulos */
  productosEliminados?: ArticuloOperacion[];
  /** Rastro o huella de la ultima transacción de registros / actualizacion del argumento Productos. - Si los datos de productos son iguales a ultima transaccion, entonces, no se realiza modificacion en el valor. - Si los datos de productos son diferentes, entonces, se sobre escribe el valor con los datos de productos anterior. */
  ultimaTransaccion?: UltimaTransaccion;
  /** Moneda de transaccion */
  moneda?: Moneda;
  /** Tipo de cambio de la transaccion */
  tipoCambio?: number;
  /** Resuelve el tipo de pedido - null = pedido normal - 'DELIVERY' = pedido por delivery - 'LLEVAR' = pedido para llevar */
  tipo?: string;
  /** Descuento Adicional que afecta a todo el detalle */
  descuentoAdicional?: number;
  /** Otros Costos de flete, alquiler, etc */
  otrosCostos?: number;
  /** Descripcion de otros costos */
  descripcionOtrosCostos?: string;
  /** Fecha del documento - Generalmente es la fecha de inicio del pedido */
  fechaDocumento?: DateDMYHHMM;
  /** Fecha contable del documento - Generalmente es la fecha de finalización del pedido */
  fechaContable?: DateDMYHHMM;
  fechaCancelacion?: DateDMYHHMMSS;
  fechaAnulacion?: DateDMYHHMMSS;
  /** Cliente de la operación */
  cliente?: ClienteOperacion;
  /** Método de pago utilizado para la finalización del pedido - No es incluyente al momento de generar la factura, pero si es referencial - Se depreca en la siguiente versión */
  metodoPago?: MetodoPago;
  /** En caso el metodo de pago sea con tarjeta, debe enviar el nro de tarjeta - Se depreca en la siguiente versión */
  numeroTarjeta?: string;
  /** Estructura de métodos de pago */
  metodoPagoVenta?: MetodoPagoVenta[];
  /** Monto total del pedido - Sumatoria de los montos en metodoPagoVenta debe coincider con monto total */
  montoTotal?: number;
  /** Monto Total base según la moneda primaria */
  montoTotalBase?: number;
  /** Calculos de los totales según detalle de productos */
  totales?: TotalesGenerales;
  /** Fecha de entrega para nota de venta de pedido */
  fechaEntrega?: DateDMYHHMM;
  /** Dirección de entrega de la mercaderia */
  direccionEntrega?: string;
  /** Detalle Extra que afecta a todo el pedido */
  detalleExtra?: string;
  /** Tipo de documento relacionado - FACTURA, NOTA_VENTA, NOTA_COMPRA */
  tipoDocumento?: string;
  /** En caso se haya generado la factura, se muestra el número de factura */
  refNroDocumento?: string;
  /** En caso se haya generado la factura, se muestra el cuf de la factura */
  refDocumento?: string;
  /** Nota del pedido */
  nota?: string;
  /** Nota rapida alternativa a notas */
  notaRapida?: NotaRapida[];
  /** Terminos de entrega del pedido */
  terminos?: string;
  /** Representación Gráfica de la nota de venta generada automaticamente */
  representacionGrafica?: UrlsConsultaDocumento;
  /** Motivo de la anulación - Solo se usa cuando se realice la anulacion de la factura */
  motivoAnulacion?: SinMotivoAnulacion;
  /** En caso se haya realizado la anulación, se muestra la descripción del motivo */
  descripcionAnulacion?: string;
  /** Atributos de tabla restaurante espacios */
  espacio?: string;
  /** Atributo auxiliar 1 */
  atributo1?: string;
  /** Atributo auxiliar 2 */
  atributo2?: string;
  /** Atributo auxiliar 3 */
  atributo3?: string;
  /** Atributo auxiliar 4 */
  atributo4?: string;
  /** Estado del registro **COMPLETADO** Mesa ya pidió la cuenta y se generar posterior a imprimir ticket de venta, pero si se siguen comandando productos la mesa cambiara nuevamente al OCUPADO. **FINALIZADO** Cuando ya finaliza el flujo o ser realiza el pago **ANULADO** Cuando se anula un pedido finalizado */
  state?: string;
  /** Usuario de creación del registro */
  usucre?: string;
  /** Fecha de creación del registro */
  createdAt?: DateDMYHHMMSS;
  /** Usuario de modificación del registro */
  usumod?: string;
  /** Fecha de modificación del registro */
  updatedAt?: DateDMYHHMMSS;
  /** Relación con la apertura de caja */
  arqueoCajaId?: string;
}
